[[component]]
kind      = "bitstream_filter"
name      = "h264_mp4toannexb"
long_name = "Convert an H.264 bitstream from length prefixed to Annex B"
codec     = "h264"
ctor      = "vaco_bsf_h2645::h264_mp4toannexb::DESC"

[[component]]
kind      = "bitstream_filter"
name      = "hevc_mp4toannexb"
long_name = "Convert an HEVC bitstream from length prefixed to Annex B"
codec     = "hevc"
ctor      = "vaco_bsf_h2645::hevc_mp4toannexb::DESC"
