//! GENERATED by `cargo xtask gen-registry`. Do not edit.
//!
//! Assembled from `vaco-component.toml` fragments so that adding a component
//! touches only that component's own crate (plan 19 §3.4).

// No components registered yet.
