//! `[FRAME_TAGS]`/`"tags"`, rendered from `vaco_frame::Frame::metadata()`,
//! byte-for-byte against captured `ffprobe` output.
//!
//! GENERATED BY OBSERVATION, NOT BY HAND. Reference: `ffprobe version 8.1`
//! (Homebrew, arm64 macOS, 2026), `libavformat 62.12.100`, under `LC_ALL=C`.
//!
//! ```sh
//! ffprobe -f lavfi \
//!   -i "color=c=black:s=64x64:d=1:r=10[a];color=c=white:s=64x64:d=1:r=10[b]; \
//!        [a][b]concat=n=2:v=1:a=0,format=yuv420p,freezedetect=n=0.001:d=0.5" \
//!   -show_frames -of default
//! ```
//!
//! # Why this is `[FRAME_TAGS]` alone and not the whole `[FRAME]` block
//!
//! `vaco-probe` refuses `-show_frames` outright (`FRAMES_UNSUPPORTED`,
//! `src/lib.rs`): v0.1 has no decoder anywhere in the workspace (D5), and a
//! frame section reports **decoded** frame properties this crate cannot
//! produce yet (D14.4 moved it to v0.2). That is unrelated to interface gap
//! 11, which is only about the metadata block — `FRAME_TAGS` plumbing already
//! existed (`sections.rs`) for stream/format/chapter/program tags, and had
//! nothing frame-level to fill it from because `Frame` had no metadata
//! dictionary at all.
//!
//! What this file proves is the piece gap 11 actually closes: given a
//! `vaco_frame::Frame` carrying the metadata a filter attached (here,
//! `freezedetect`'s three keys, built directly rather than through a decoder
//! — the same "replay the description, not the pipeline" split
//! `reference.rs`/`packets.rs` already use), `show::tags` — the **same**
//! generic renderer already used for `STREAM_TAGS`/`FORMAT_TAGS`/
//! `CHAPTER_TAGS`/`PROGRAM_TAGS` — reproduces the reference's `[FRAME_TAGS]`
//! block spelling, order and formatting exactly. No new renderer was needed;
//! `Frame::metadata()`'s `&[(String, String)]` return type is deliberately
//! the shape `tags` already takes. Wiring a real `[FRAME]` block (pts,
//! pict_type, `pix_fmt`, …) is `-show_frames` v0.2 work, gated on a decoder,
//! and out of this gap's scope.
//!
//! `freezedetect`'s own module doc
//! (`crates/filter/vaco-filter-temporal/src/freezedetect.rs`) has the
//! producer-side measurement notes: value formatting, and which frame's
//! timestamp `freeze_end`/`freeze_duration` use.

#![allow(
    clippy::expect_used,
    reason = "a test that cannot set up is a failed test"
)]

use vaco_frame::{Frame, FrameData};
use vaco_probe::emit::Emit;
use vaco_probe::show;
use vaco_textformat::sections::SectionId;
use vaco_textformat::{FormatOpts, OptionalFields, TextFormat, writers};

// ------------------------------------------------------------ captured bytes

/// The confirming frame (index 5, t=0.5s): `freeze_start` alone.
const FREEZE_START_DEFAULT: &str = "\
[FRAME]
TAG:lavfi.freezedetect.freeze_start=0
[/FRAME]
";

/// The frame that breaks the run (index 10, t=1.0s): `freeze_duration` then
/// `freeze_end`, together — insertion order, not alphabetical (`d` before
/// `e` is coincidence here; `signalstats`' own key order is not alphabetical
/// either).
const FREEZE_END_DEFAULT: &str = "\
[FRAME]
TAG:lavfi.freezedetect.freeze_duration=1
TAG:lavfi.freezedetect.freeze_end=1
[/FRAME]
";

/// A frame with nothing to report has no `TAG:` line and no `[FRAME_TAGS]`
/// section at all — the reference opens no section for empty metadata
/// (`show::tags`'s own doc comment, already true for the other `*_TAGS`
/// sections and unchanged here).
const NO_EVENT_DEFAULT: &str = "\
[FRAME]
[/FRAME]
";

// `SectionId::FRAME` is opened standalone here (no enclosing `[FRAMES]`
// array — that wrapper is `-show_frames` v0.2 work, gated on a decoder), so
// the JSON writer nests it under its own `"frame"` key exactly the way any
// standalone named section does. That nesting comes from `TextFormat`'s
// generic section handling, already exercised by `reference.rs`/`packets.rs`
// for `"streams"`/`"packets"`; only the `"tags"` object inside it is this
// gap's concern.
const FREEZE_START_JSON: &str = "{
    \"frame\": {
        \"tags\": {
            \"lavfi.freezedetect.freeze_start\": \"0\"
        }
    }
}
";

const FREEZE_END_JSON: &str = "{
    \"frame\": {
        \"tags\": {
            \"lavfi.freezedetect.freeze_duration\": \"1\",
            \"lavfi.freezedetect.freeze_end\": \"1\"
        }
    }
}
";

// ------------------------------------------------------------------ harness

fn render(spec: &str, frame: &Frame) -> String {
    let mut sink = Vec::new();
    {
        let w = writers::make(spec).expect("writer");
        let mut tf = TextFormat::new(w, &mut sink, FormatOpts::default());
        tf.open(SectionId::ROOT).expect("root");
        {
            let mut e = Emit::new(&mut tf, OptionalFields::Auto);
            e.tf().open(SectionId::FRAME).expect("frame");
            show::tags(&mut e, SectionId::FRAME_TAGS, frame.metadata()).expect("tags");
            e.tf().close().expect("close frame");
        }
        tf.close().expect("close root");
        let _ = tf.finish().expect("finish");
    }
    String::from_utf8(sink).expect("utf-8")
}

fn bare_gray8_frame() -> Frame {
    Frame::from_data(FrameData::Video {
        format: vaco_pixfmt::PixFmt::Gray8,
        width: 4,
        height: 4,
        planes: smallvec::SmallVec::new(),
    })
}

// -------------------------------------------------------------------- tests

#[test]
fn freeze_start_tag_is_byte_identical() {
    let mut frame = bare_gray8_frame();
    frame.set_metadata("lavfi.freezedetect.freeze_start", "0");
    assert_eq!(render("default", &frame), FREEZE_START_DEFAULT);
    assert_eq!(render("json", &frame), FREEZE_START_JSON);
}

#[test]
fn freeze_end_and_duration_tags_are_byte_identical_and_ordered() {
    let mut frame = bare_gray8_frame();
    // Set in the same order `freezedetect::step` sets them.
    frame.set_metadata("lavfi.freezedetect.freeze_duration", "1");
    frame.set_metadata("lavfi.freezedetect.freeze_end", "1");
    assert_eq!(render("default", &frame), FREEZE_END_DEFAULT);
    assert_eq!(render("json", &frame), FREEZE_END_JSON);
}

#[test]
fn a_frame_with_no_metadata_opens_no_tags_section() {
    let frame = bare_gray8_frame();
    assert_eq!(render("default", &frame), NO_EVENT_DEFAULT);
    // No `"tags"` key at all in JSON either — observed on the reference: a
    // raw file's `[FRAME]` with no metadata has no `TAG:` lines, and `-of
    // json` has no `"tags"` key. `show::tags` already encodes this for every
    // other `*_TAGS` section; nothing frame-specific to get wrong here.
    assert_eq!(render("json", &frame), "{\n    \"frame\": {\n\n    }\n}\n");
}
