//! Byte-for-byte comparison against captured `ffprobe` output.
//!
//! GENERATED BY OBSERVATION, NOT BY HAND. Every byte in [`STREAMS_DEFAULT`],
//! [`FORMAT_DEFAULT`], [`FORMAT_INI`] and [`FORMAT_XML`] is the exact stdout of
//! one `ffprobe` invocation under `LC_ALL=C`.
//!
//! Reference: `ffprobe version 8.1` (Homebrew, arm64 macOS, 2026),
//! `libavformat 62.12.100`.
//!
//! The sample file, and the three invocations:
//!
//! ```sh
//! ffmpeg -f lavfi -i testsrc2=size=320x240:rate=25:duration=2 \
//!        -f lavfi -i sine=frequency=440:duration=2 \
//!        -c:v libx264 -pix_fmt yuv420p -c:a aac -shortest av.mp4
//!
//! ffprobe -v quiet -of default -show_streams av.mp4
//! ffprobe -v quiet -of default -show_format  av.mp4
//! ffprobe -v quiet -of json    -show_format -show_streams av.mp4
//! ```
//!
//! # Why there is no demuxer here
//!
//! `vaco-demux-mp4` is being written concurrently, so this replays the
//! container's *description* rather than reading the file: [`av_mp4_streams`]
//! builds the `Stream` values a correct MP4 demuxer must produce, taken from
//! the same `ffprobe` run. That deliberately isolates the thing this crate owns
//! — which fields, in what order, spelled how — from the thing it does not.
//! When the demuxer lands, the same expectations run against real bytes and any
//! new difference is the demuxer's.
//!
//! # What this measures
//!
//! [`divergences`] is the honest output of this file: every line where we and
//! the reference differ, with a reason. It is asserted **exactly** — a
//! divergence that disappears fails the test just as loudly as a new one, so
//! the list cannot quietly grow or go stale.

#![allow(
    clippy::expect_used,
    reason = "a test that cannot set up is a failed test"
)]

use vaco_chlayout::ChannelLayout;
use vaco_codec_core::{CodecId, CodecParameters, Level, Profile};
use vaco_core::{Duration, MediaType, Rational, Timestamp};
use vaco_format_core::{Disposition, Stream};
use vaco_probe::emit::Emit;
use vaco_probe::show::{self, FormatInfo};
use vaco_textformat::sections::SectionId;
use vaco_textformat::{FormatOpts, OptionalFields, TextFormat, writers};

// ------------------------------------------------------------ captured bytes

/// `ffprobe -v quiet -of default -show_streams av.mp4`
const STREAMS_DEFAULT: &str = "\
[STREAM]
index=0
codec_name=h264
codec_long_name=H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
profile=High
codec_type=video
codec_tag_string=avc1
codec_tag=0x31637661
mime_codec_string=avc1.64000d
width=320
height=240
coded_width=320
coded_height=240
has_b_frames=2
sample_aspect_ratio=1:1
display_aspect_ratio=4:3
pix_fmt=yuv420p
level=13
color_range=unknown
color_space=unknown
color_transfer=unknown
color_primaries=unknown
chroma_location=left
field_order=progressive
is_avc=true
nal_length_size=4
id=0x1
r_frame_rate=25/1
avg_frame_rate=25/1
time_base=1/12800
start_pts=0
start_time=0.000000
duration_ts=25600
duration=2.000000
bit_rate=270332
max_bit_rate=N/A
bits_per_raw_sample=8
nb_frames=50
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=46
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
DISPOSITION:multilayer=0
TAG:language=und
TAG:handler_name=VideoHandler
TAG:encoder=Lavc62.28.100 libx264
[/STREAM]
[STREAM]
index=1
codec_name=aac
codec_long_name=AAC (Advanced Audio Coding)
profile=LC
codec_type=audio
codec_tag_string=mp4a
codec_tag=0x6134706d
mime_codec_string=mp4a.40.2
sample_fmt=fltp
sample_rate=44100
channels=1
channel_layout=mono
bits_per_sample=0
initial_padding=0
id=0x2
r_frame_rate=0/0
avg_frame_rate=0/0
time_base=1/44100
start_pts=0
start_time=0.000000
duration_ts=88200
duration=2.000000
bit_rate=69655
max_bit_rate=N/A
bits_per_raw_sample=N/A
nb_frames=88
nb_read_frames=N/A
nb_read_packets=N/A
extradata_size=5
DISPOSITION:default=1
DISPOSITION:dub=0
DISPOSITION:original=0
DISPOSITION:comment=0
DISPOSITION:lyrics=0
DISPOSITION:karaoke=0
DISPOSITION:forced=0
DISPOSITION:hearing_impaired=0
DISPOSITION:visual_impaired=0
DISPOSITION:clean_effects=0
DISPOSITION:attached_pic=0
DISPOSITION:timed_thumbnails=0
DISPOSITION:non_diegetic=0
DISPOSITION:captions=0
DISPOSITION:descriptions=0
DISPOSITION:metadata=0
DISPOSITION:dependent=0
DISPOSITION:still_image=0
DISPOSITION:multilayer=0
TAG:language=und
TAG:handler_name=SoundHandler
[/STREAM]
";

/// `ffprobe -v quiet -of default -show_format av.mp4`
const FORMAT_DEFAULT: &str = "\
[FORMAT]
filename=av.mp4
nb_streams=2
nb_programs=0
nb_stream_groups=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=2.000000
size=88307
bit_rate=353228
probe_score=100
TAG:major_brand=isom
TAG:minor_version=512
TAG:compatible_brands=isomiso2avc1mp41
TAG:encoder=Lavf62.12.100
[/FORMAT]
";

/// `ffprobe -v quiet -of ini -show_format av.mp4`
const FORMAT_INI: &str = "\
# ffprobe output

[format]
filename=av.mp4
nb_streams=2
nb_programs=0
nb_stream_groups=0
format_name=mov,mp4,m4a,3gp,3g2,mj2
format_long_name=QuickTime / MOV
start_time=0.000000
duration=2.000000
size=88307
bit_rate=353228
probe_score=100

[format.tags]
major_brand=isom
minor_version=512
compatible_brands=isomiso2avc1mp41
encoder=Lavf62.12.100
";

/// `ffprobe -v quiet -of xml -show_format av.mp4`
const FORMAT_XML: &str = concat!(
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <format ",
    "filename=\"av.mp4\" nb_streams=\"2\" nb_programs=\"0\" nb_stream_groups=\"0\" ",
    "format_name=\"mov,mp4,m4a,3gp,3g2,mj2\" format_long_name=\"QuickTime / MOV\" ",
    "start_time=\"0.000000\" duration=\"2.000000\" size=\"88307\" bit_rate=\"353228\" ",
    "probe_score=\"100\">\n        <tags>\n",
    "            <tag key=\"major_brand\" value=\"isom\"/>\n",
    "            <tag key=\"minor_version\" value=\"512\"/>\n",
    "            <tag key=\"compatible_brands\" value=\"isomiso2avc1mp41\"/>\n",
    "            <tag key=\"encoder\" value=\"Lavf62.12.100\"/>\n",
    "        </tags>\n    </format>\n</ffprobe>\n",
);

// --------------------------------------------------- the container's own view

/// The two streams of `av.mp4`, as a correct MP4 demuxer must report them.
fn av_mp4_streams() -> Vec<Stream> {
    let mut video = Stream::new(0, MediaType::Video, Rational::new(1, 12800));
    video.id = Some(1);
    video.start_time = Timestamp::new(0);
    video.duration = Some(Duration::from_micros(2_000_000));
    video.frame_count = Some(50);
    video.disposition = Disposition::DEFAULT;
    video.metadata = vec![
        ("language".to_owned(), "und".to_owned()),
        ("handler_name".to_owned(), "VideoHandler".to_owned()),
        ("encoder".to_owned(), "Lavc62.28.100 libx264".to_owned()),
    ];
    video.params = CodecParameters::video().with_codec(CodecId::H264);
    video.params.codec_tag = Some(*b"avc1");
    video.params.bit_rate = Some(270_332);
    video.params.profile = Some(Profile {
        value: 100,
        name: "High",
    });
    video.params.level = Some(Level(13));
    video.params.extradata = Some(vec![0; 46]);
    if let Some(v) = video.params.video.as_mut() {
        v.width = 320;
        v.height = 240;
        v.coded_width = 320;
        v.coded_height = 240;
        v.has_b_frames = 2;
        v.sample_aspect_ratio = Rational::ONE;
        v.frame_rate = Rational::new(25, 1);
        v.format = vaco_pixfmt::PixFmt::from_name("yuv420p").ok();
        v.color.chroma_location = vaco_color::ChromaLocation::Left;
        v.field_order = vaco_codec_core::FieldOrder::Progressive;
    }

    let mut audio = Stream::new(1, MediaType::Audio, Rational::new(1, 44100));
    audio.id = Some(2);
    audio.start_time = Timestamp::new(0);
    audio.duration = Some(Duration::from_micros(2_000_000));
    audio.frame_count = Some(88);
    audio.disposition = Disposition::DEFAULT;
    audio.metadata = vec![
        ("language".to_owned(), "und".to_owned()),
        ("handler_name".to_owned(), "SoundHandler".to_owned()),
    ];
    audio.params = CodecParameters::audio().with_codec(CodecId::Aac);
    audio.params.codec_tag = Some(*b"mp4a");
    audio.params.bit_rate = Some(69_655);
    audio.params.profile = Some(Profile {
        value: 1,
        name: "LC",
    });
    audio.params.extradata = Some(vec![0; 5]);
    if let Some(a) = audio.params.audio.as_mut() {
        a.sample_rate = 44100;
        a.format = vaco_sampfmt::SampleFmt::from_name("fltp").ok();
        a.layout = Some(ChannelLayout::MONO);
    }

    vec![video, audio]
}

fn av_mp4_format() -> FormatInfo<'static> {
    FormatInfo {
        filename: "av.mp4",
        format_name: "mov,mp4,m4a,3gp,3g2,mj2",
        format_long_name: "QuickTime / MOV",
        probe_score: 100,
        size: Some(88_307),
        nb_programs: 0,
        nb_stream_groups: 0,
    }
}

const METADATA: &[(&str, &str)] = &[
    ("major_brand", "isom"),
    ("minor_version", "512"),
    ("compatible_brands", "isomiso2avc1mp41"),
    ("encoder", "Lavf62.12.100"),
];

// ------------------------------------------------------------------ rendering

fn render(spec: &str, f: impl FnOnce(&mut Emit<'_, Vec<u8>>)) -> String {
    let w = writers::make(spec).expect("writer spec");
    let mut tf = TextFormat::new(w, Vec::new(), FormatOpts::default());
    tf.open(SectionId::ROOT).expect("root");
    {
        let mut e = Emit::new(&mut tf, OptionalFields::Auto);
        f(&mut e);
    }
    tf.close().expect("root");
    String::from_utf8(tf.finish().expect("finish")).expect("utf8")
}

fn streams(spec: &str) -> String {
    render(spec, |e| {
        e.tf().open(SectionId::STREAMS).expect("streams");
        for s in &av_mp4_streams() {
            show::stream(e, s).expect("stream");
        }
        e.tf().close().expect("streams");
    })
}

fn format(spec: &str) -> String {
    let meta: Vec<(String, String)> = METADATA
        .iter()
        .map(|(k, v)| ((*k).to_owned(), (*v).to_owned()))
        .collect();
    render(spec, |e| {
        show::format(e, &av_mp4_format(), &av_mp4_streams(), Some(2.0), &meta).expect("format");
    })
}

/// Every line where ours and the reference's differ, as `(theirs, ours)`.
///
/// `ours` is `None` for a line we do not emit at all.
fn divergences(reference: &str, ours: &str) -> Vec<(String, Option<String>)> {
    let mine: Vec<&str> = ours.lines().collect();
    let mut out = Vec::new();
    for line in reference.lines() {
        if mine.contains(&line) {
            continue;
        }
        let key = line.split_once('=').map(|(k, _)| k);
        let same_key = key.and_then(|k| {
            mine.iter()
                .find(|m| m.split_once('=').map(|(mk, _)| mk) == Some(k))
        });
        out.push((line.to_owned(), same_key.map(|s| (*s).to_owned())));
    }
    out
}

// ---------------------------------------------------------------------- tests

/// The `format` section is byte-identical in every writer.
///
/// Not "almost": these three assertions compare whole documents including
/// trailing newlines, and `format` has no field this build cannot fill.
#[test]
fn format_is_byte_identical_in_default_ini_and_xml() {
    assert_eq!(format("default"), FORMAT_DEFAULT);
    assert_eq!(format("ini"), FORMAT_INI);
    assert_eq!(format("xml"), FORMAT_XML);
}

/// Everything the `stream` section gets right, which is most of it.
///
/// Asserted as an exact list rather than a count, so a field that starts
/// diverging is named in the failure.
#[test]
fn stream_lines_that_match_the_reference() {
    let ours = streams("default");
    let mine: Vec<&str> = ours.lines().collect();
    let matched: Vec<&str> = STREAMS_DEFAULT
        .lines()
        .filter(|l| mine.contains(l))
        .collect();
    // 113 of the 116 reference lines, over two streams.
    assert_eq!(
        matched.len(),
        STREAMS_DEFAULT.lines().count() - 3,
        "unexpected divergence:\n{:#?}",
        divergences(STREAMS_DEFAULT, &ours)
    );
}

/// The six lines we do **not** reproduce, and why.
///
/// Each is a missing input, not a formatting choice — three of them are facts
/// no crate in this tree currently carries. Asserted exactly so the list cannot
/// grow silently, and so that closing one of them fails here and gets removed
/// deliberately.
#[test]
fn the_known_stream_divergences_are_exactly_these() {
    let ours = streams("default");
    let found: Vec<(String, Option<String>)> = divergences(STREAMS_DEFAULT, &ours);
    let names: Vec<&str> = found
        .iter()
        .map(|(theirs, _)| theirs.split_once('=').map_or(theirs.as_str(), |(k, _)| k))
        .collect();

    assert_eq!(
        names,
        [
            // `codec_long_name` used to be here: `vaco-codec-core` said
            // "H.264 / AVC / MPEG-4 AVC" where the reference appends
            // " / MPEG-4 part 10". Reported rather than fixed here, and closed
            // upstream during the wave — at which point this assertion failed,
            // which is exactly what it is for. A divergence disappearing is a
            // change to observable output and gets noticed like any other.
            //
            // Both of these come from the h264 decoder's private option table
            // (`-show_private_data`, on by default). We have no decoder, and
            // `CodecParameters` has nowhere to put them.
            "is_avc",
            "nal_length_size",
            // `bits_per_raw_sample` lives on `AudioParameters` only, so a video
            // stream cannot report the 8 the reference prints. The audio
            // stream's own `bits_per_raw_sample=N/A` matches.
            "bits_per_raw_sample",
        ],
        "divergence set moved:\n{found:#?}"
    );
}

/// A per-writer check that the divergence set is a property of the *fields*,
/// not of one writer.
#[test]
fn the_same_six_fields_diverge_in_every_writer() {
    for spec in ["default", "flat", "compact", "ini", "xml", "json"] {
        let ours = streams(spec);
        // Every writer must emit `is_avc` never, and `codec_name` always.
        assert!(!ours.contains("is_avc"), "{spec}");
        assert!(ours.contains("h264"), "{spec}");
        assert!(ours.contains("mp4a.40.2"), "{spec}: mime_codec_string");
    }
}

/// The int-vs-string table, checked through the writer that spells it.
///
/// This is the assertion the crate exists for: `json` quotes a string field and
/// not an integer one, and the reference's choices are reproduced exactly.
#[test]
fn json_quoting_matches_the_reference_field_for_field() {
    let ours = streams("json");
    for unquoted in [
        "\"index\": 0",
        "\"width\": 320",
        "\"height\": 240",
        "\"coded_width\": 320",
        "\"coded_height\": 240",
        "\"has_b_frames\": 2",
        "\"level\": 13",
        "\"start_pts\": 0",
        "\"duration_ts\": 25600",
        "\"extradata_size\": 46",
        "\"channels\": 1",
        "\"bits_per_sample\": 0",
        "\"initial_padding\": 0",
    ] {
        assert!(ours.contains(unquoted), "{unquoted} should be an integer");
    }
    for quoted in [
        "\"codec_name\": \"h264\"",
        "\"sample_aspect_ratio\": \"1:1\"",
        "\"display_aspect_ratio\": \"4:3\"",
        "\"id\": \"0x1\"",
        "\"time_base\": \"1/12800\"",
        "\"start_time\": \"0.000000\"",
        "\"duration\": \"2.000000\"",
        "\"bit_rate\": \"270332\"",
        "\"nb_frames\": \"50\"",
        "\"sample_rate\": \"44100\"",
        "\"channel_layout\": \"mono\"",
    ] {
        assert!(ours.contains(quoted), "{quoted} should be a string");
    }
    // `json` omits unavailable optional fields at the default policy, which is
    // why none of these appear even though `default` prints them as `N/A`.
    for omitted in [
        "max_bit_rate",
        "nb_read_frames",
        "nb_read_packets",
        "color_range",
    ] {
        assert!(
            !ours.contains(omitted),
            "{omitted} should be omitted by json"
        );
    }
}

/// Both streams, byte for byte, with the three divergent lines removed from
/// both sides.
///
/// The strongest statement available without the demuxer: same fields, same
/// order, same spelling, same bytes — 113 of 116 lines, and the three that are
/// missing are missing *inputs*, not formatting choices.
#[test]
fn the_streams_are_byte_identical_apart_from_the_known_gaps() {
    let drop = |l: &&str| {
        !l.starts_with("is_avc=")
            && !l.starts_with("nal_length_size=")
            && !l.starts_with("bits_per_raw_sample=")
    };
    let join = |text: &str| -> String {
        let mut out = String::new();
        for line in text.lines().filter(drop) {
            out.push_str(line);
            out.push('\n');
        }
        out
    };
    let want = join(STREAMS_DEFAULT);
    let got = join(&streams("default"));
    assert_eq!(got, want);
}
