//! End-to-end oracle: [`ProresDecoder`] against real `ffmpeg -c:v prores_ks`
//! output, decoded here and compared to `ffmpeg`'s own reference decode of
//! the same bytes — **Y, U and V measured separately** (a whole-frame or
//! luma-only comparison can hide a chroma-only defect entirely, the exact
//! failure mode this project's own VP8/Theora work already flagged).
//!
//! # Fixtures
//!
//! Two real files, generated by `ffmpeg 8.1`'s own `prores_ks` encoder from
//! a `testsrc2` pattern (genuine spatial detail, not flat color, so the
//! DCT/entropy path is actually exercised) and muxed into `.mov`:
//!
//! - `422hq.mov` — profile 2 (`apcn`, "422 HQ"), `yuv422p10le`, 64x64, 2
//!   frames.
//! - `444.mov` — profile 4 (`ap4h`, "4444"), `yuv444p10le` *input*, which
//!   `ffmpeg` itself re-encodes at the profile's native 12-bit depth
//!   (`ffprobe` reports the resulting stream as `yuv444p12le`) — this is the
//!   real-world confirmation for this crate's own `chroma_format`-derived
//!   bit-depth rule (see the crate's top-level doc).
//!
//! `{name}.yuv` is `ffmpeg -i {name}.mov -f rawvideo -pix_fmt <same>`'s own
//! decode of the whole file, both frames concatenated — the reference this
//! test compares against, plane by plane.
//!
//! # Result
//!
//! Exact on every plane's DC structure with a small rounding scatter from
//! the classical (non-integer-mandated) IDCT: RDD 36 SS7.4 explicitly
//! permits any IEEE-1180-accurate implementation, not a single mandated
//! integer one, so a few±1-code differences against one *particular*
//! reference decoder's own IDCT rounding is the expected, unstructured
//! outcome the owner's byte-exactness ruling describes — not a defect.
//! This test asserts a small bound instead of byte-identity for exactly that
//! reason, and reports the measured max/mean per plane so a future
//! regression (a *structured* jump, not a rounding scatter) is visible.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::indexing_slicing,
    clippy::panic,
    reason = "test code over fixed fixtures"
)]

use vaco_codec_core::{CodecId, Decoder};
use vaco_codec_prores::ProresDecoder;
use vaco_format_core::discovery::NoParsers;
use vaco_format_core::{Demuxer, FormatOptions};
use vaco_frame::FrameData;
use vaco_io::MediaSource;
use vaco_limits::Limits;

struct DecodedPlanes {
    y: Vec<u8>,
    u: Vec<u8>,
    v: Vec<u8>,
}

/// Decode every video packet in `path` with [`ProresDecoder`], returning each
/// frame's raw Y/U/V plane bytes (tightly packed, no stride padding).
fn decode_all_frames(path: &str) -> Vec<DecodedPlanes> {
    let bytes = std::fs::read(path).expect("reads fixture");
    let src: Box<dyn MediaSource> = Box::new(vaco_io::MemorySource::new(bytes));
    let mut demux = vaco_demux_mp4::Mp4Demuxer::open(
        src,
        &NoParsers,
        &FormatOptions::default(),
        vaco_demux_mp4::Mp4Options::default(),
    )
    .expect("opens mov");
    let stream_idx = demux
        .streams()
        .iter()
        .find(|s| s.params.codec_id == Some(CodecId::Prores))
        .expect("has a prores stream")
        .index;

    let mut dec = ProresDecoder::new(Limits::permissive());
    let mut out = Vec::new();
    loop {
        let Ok(packet) = demux.read_packet() else {
            break;
        };
        if packet.stream_index != stream_idx {
            continue;
        }
        dec.send_packet(Some(&packet)).expect("decodes packet");
        let frame = dec.receive_frame().expect("produces a frame");
        let FrameData::Video { planes, format, width, height } = &frame.data else {
            panic!("expected a video frame");
        };
        let sample_bytes = 2usize; // every format this test exercises is >8-bit
        let (cw, ch) = chroma_dims(*format, *width, *height);
        let y = tight_plane(&planes[0], *width as usize, *height as usize, sample_bytes);
        let u = tight_plane(&planes[1], cw, ch, sample_bytes);
        let v = tight_plane(&planes[2], cw, ch, sample_bytes);
        out.push(DecodedPlanes { y, u, v });
    }
    out
}

fn chroma_dims(format: vaco_pixfmt::PixFmt, w: u32, h: u32) -> (usize, usize) {
    match format {
        vaco_pixfmt::PixFmt::Yuv422p10le | vaco_pixfmt::PixFmt::Yuva422p10le => {
            (w.div_ceil(2) as usize, h as usize)
        }
        _ => (w as usize, h as usize),
    }
}

fn tight_plane(plane: &vaco_frame::Plane, w: usize, h: usize, sample_bytes: usize) -> Vec<u8> {
    let mut out = vec![0u8; w * h * sample_bytes];
    let src = plane.data.as_slice();
    let row_bytes = w * sample_bytes;
    for row in 0..h {
        let src_off = row * plane.stride;
        let dst_off = row * row_bytes;
        if let (Some(s), Some(d)) = (
            src.get(src_off..src_off + row_bytes),
            out.get_mut(dst_off..dst_off + row_bytes),
        ) {
            d.copy_from_slice(s);
        }
    }
    out
}

/// Split a raw planar `.yuv` reference file into per-frame Y/U/V byte slices,
/// 16-bit little-endian samples throughout.
fn split_reference(
    path: &str,
    width: usize,
    height: usize,
    chroma_width: usize,
    chroma_height: usize,
) -> Vec<DecodedPlanes> {
    let data = std::fs::read(path).expect("reads reference yuv");
    let luma_len = width * height * 2;
    let chroma_len = chroma_width * chroma_height * 2;
    let frame_len = luma_len + 2 * chroma_len;
    let mut out = Vec::new();
    let mut offset = 0;
    while offset + frame_len <= data.len() {
        let luma = data[offset..offset + luma_len].to_vec();
        let chroma_u = data[offset + luma_len..offset + luma_len + chroma_len].to_vec();
        let chroma_v = data[offset + luma_len + chroma_len..offset + frame_len].to_vec();
        out.push(DecodedPlanes { y: luma, u: chroma_u, v: chroma_v });
        offset += frame_len;
    }
    out
}

/// Max and mean absolute per-sample difference over two equal-length,
/// 16-bit-LE-packed byte buffers.
fn compare_plane(name: &str, got: &[u8], want: &[u8]) -> (i32, f64) {
    assert_eq!(got.len(), want.len(), "{name}: plane length mismatch");
    let mut max_diff = 0i32;
    let mut sum = 0i64;
    let mut count = 0i64;
    for (a, b) in got.chunks_exact(2).zip(want.chunks_exact(2)) {
        let av = i32::from(u16::from_le_bytes([a[0], a[1]]));
        let bv = i32::from(u16::from_le_bytes([b[0], b[1]]));
        let d = (av - bv).abs();
        max_diff = max_diff.max(d);
        sum += i64::from(d);
        count += 1;
    }
    let mean = sum as f64 / count.max(1) as f64;
    println!("{name}: max diff = {max_diff}, mean diff = {mean:.4} over {count} samples");
    (max_diff, mean)
}

#[test]
fn prores_422hq_matches_ffmpeg_per_plane() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
    let got = decode_all_frames(&format!("{dir}/422hq.mov"));
    let want = split_reference(&format!("{dir}/422hq.yuv"), 64, 64, 32, 64);
    assert_eq!(got.len(), 2, "expected 2 decoded frames");
    assert_eq!(want.len(), 2, "expected 2 reference frames");
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        let (ymax, ymean) = compare_plane(&format!("frame {i} Y"), &g.y, &w.y);
        let (umax, umean) = compare_plane(&format!("frame {i} U"), &g.u, &w.u);
        let (vmax, vmean) = compare_plane(&format!("frame {i} V"), &g.v, &w.v);
        // A generous but real bound: a structured defect (wrong geometry, a
        // channel swap, a scan-table transposition) produces differences in
        // the hundreds or thousands of codes, not a handful from IDCT
        // rounding. See this file's module doc.
        assert!(ymax <= 8 && ymean < 2.0, "frame {i} Y diverges structurally: max={ymax} mean={ymean}");
        assert!(umax <= 8 && umean < 2.0, "frame {i} U diverges structurally: max={umax} mean={umean}");
        assert!(vmax <= 8 && vmean < 2.0, "frame {i} V diverges structurally: max={vmax} mean={vmean}");
    }
}

#[test]
fn prores_multislice_wide_frame_matches_ffmpeg_per_plane() {
    // 256x144 = 16x9 macroblocks, encoded with `-mbs_per_slice 2`, so each
    // macroblock row is split into 8 slices — the multi-slice path
    // `422hq`/`444` (both single-slice-per-row at this size) do not exercise.
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
    let got = decode_all_frames(&format!("{dir}/wide422.mov"));
    let want = split_reference(&format!("{dir}/wide422.yuv"), 256, 144, 128, 144);
    assert_eq!(got.len(), 1);
    assert_eq!(want.len(), 1);
    let (ymax, ymean) = compare_plane("Y", &got[0].y, &want[0].y);
    let (umax, umean) = compare_plane("U", &got[0].u, &want[0].u);
    let (vmax, vmean) = compare_plane("V", &got[0].v, &want[0].v);
    assert!(ymax <= 8 && ymean < 2.0, "Y diverges structurally: max={ymax} mean={ymean}");
    assert!(umax <= 8 && umean < 2.0, "U diverges structurally: max={umax} mean={umean}");
    assert!(vmax <= 8 && vmean < 2.0, "V diverges structurally: max={vmax} mean={vmean}");
}

#[test]
fn prores_4444_alpha_matches_ffmpeg() {
    // 4444 with an encoded alpha channel (`alphamerge` against a solid white
    // matte) — exercises `scanned_alpha()` (SS7.1.2/SS7.5.2), which none of
    // this file's other fixtures carry.
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
    let bytes = std::fs::read(format!("{dir}/alpha444.mov")).expect("reads fixture");
    let src: Box<dyn MediaSource> = Box::new(vaco_io::MemorySource::new(bytes));
    let mut demux = vaco_demux_mp4::Mp4Demuxer::open(
        src,
        &NoParsers,
        &FormatOptions::default(),
        vaco_demux_mp4::Mp4Options::default(),
    )
    .expect("opens mov");
    let mut dec = ProresDecoder::new(Limits::permissive());
    let packet = demux.read_packet().expect("has a packet");
    dec.send_packet(Some(&packet)).expect("decodes");
    let frame = dec.receive_frame().expect("produces a frame");
    let FrameData::Video { planes, format, .. } = &frame.data else {
        panic!("expected a video frame");
    };
    assert_eq!(*format, vaco_pixfmt::PixFmt::Yuva444p12le);
    let alpha = tight_plane(&planes[3], 64, 64, 2);
    let want = std::fs::read(format!("{dir}/alpha444.yuv")).expect("reads reference");
    // yuva444p12le layout: Y, U, V, A planes, each 64*64 samples * 2 bytes.
    let plane_len = 64 * 64 * 2;
    let want_alpha = &want[plane_len * 3..plane_len * 4];
    let (max, mean) = compare_plane("alpha", &alpha, want_alpha);
    assert!(max <= 8 && mean < 2.0, "alpha diverges structurally: max={max} mean={mean}");
}

#[test]
fn prores_4444_matches_ffmpeg_per_plane() {
    let dir = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
    let got = decode_all_frames(&format!("{dir}/444.mov"));
    let want = split_reference(&format!("{dir}/444.yuv"), 64, 64, 64, 64);
    assert_eq!(got.len(), 2, "expected 2 decoded frames");
    assert_eq!(want.len(), 2, "expected 2 reference frames");
    for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
        let (ymax, ymean) = compare_plane(&format!("frame {i} Y"), &g.y, &w.y);
        let (umax, umean) = compare_plane(&format!("frame {i} U"), &g.u, &w.u);
        let (vmax, vmean) = compare_plane(&format!("frame {i} V"), &g.v, &w.v);
        assert!(ymax <= 8 && ymean < 2.0, "frame {i} Y diverges structurally: max={ymax} mean={ymean}");
        assert!(umax <= 8 && umean < 2.0, "frame {i} U diverges structurally: max={umax} mean={umean}");
        assert!(vmax <= 8 && vmean < 2.0, "frame {i} V diverges structurally: max={vmax} mean={vmean}");
    }
}
