//! Quantisation dither for the float → integer path.
//!
//! # Scope, stated plainly
//!
//! Four methods are implemented: `none`, `rectangular`, `triangular` and
//! `triangular_hp`. The seven noise-shaping curves are **accepted by name,
//! warned about, and aliased to `triangular_hp`** — the §B.13.3 pattern for an
//! option we cannot honour: accept the name, do the sensible thing, and say so
//! at a log level the user will see. They are not implemented because the
//! Lipshitz-family coefficients need the JAES 1991 paper in hand and the
//! Shibata-named curves have to be generated by us (§B.6), and neither fits in
//! this pass.
//!
//! The reference's default is `none`, which is directly observable: `flt → s16`
//! is a clean deterministic function of the input value with no per-sample
//! variation at all. So dither is opt-in on both sides and nothing here changes
//! the default path.
//!
//! # Determinism
//!
//! The noise is a pure function of `(seed, channel, absolute sample position)`.
//! No wall clock, no global state, no per-call generator — so re-running gives
//! the same bytes, and, critically, **chunking the stream differently gives the
//! same bytes**. That is what lets the differential harness compare dithered
//! output at all, and it is why the dither path is still Class A despite being
//! "random".

use vaco_core::Error;

use crate::convert::Internal;

/// The `dither_method` option surface.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum DitherMethod {
    #[default]
    None,
    Rectangular,
    Triangular,
    TriangularHighpass,
    NsLipshitz,
    NsFWeighted,
    NsModifiedEWeighted,
    NsImprovedEWeighted,
    NsShibata,
    NsLowShibata,
    NsHighShibata,
}

impl DitherMethod {
    /// # Errors
    /// [`Error::Option`] for an unknown name.
    pub fn from_name(name: &str) -> Result<Self, Error> {
        Ok(match name {
            "none" => Self::None,
            "rectangular" => Self::Rectangular,
            "triangular" => Self::Triangular,
            "triangular_hp" => Self::TriangularHighpass,
            "lipshitz" => Self::NsLipshitz,
            "f_weighted" => Self::NsFWeighted,
            "modified_e_weighted" => Self::NsModifiedEWeighted,
            "improved_e_weighted" => Self::NsImprovedEWeighted,
            "shibata" => Self::NsShibata,
            "low_shibata" => Self::NsLowShibata,
            "high_shibata" => Self::NsHighShibata,
            _ => {
                return Err(Error::Option {
                    name: "dither_method".to_owned(),
                    detail: format!("unknown dither method `{name}`"),
                });
            }
        })
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Rectangular => "rectangular",
            Self::Triangular => "triangular",
            Self::TriangularHighpass => "triangular_hp",
            Self::NsLipshitz => "lipshitz",
            Self::NsFWeighted => "f_weighted",
            Self::NsModifiedEWeighted => "modified_e_weighted",
            Self::NsImprovedEWeighted => "improved_e_weighted",
            Self::NsShibata => "shibata",
            Self::NsLowShibata => "low_shibata",
            Self::NsHighShibata => "high_shibata",
        }
    }

    /// Whether this is one of the noise-shaping names we alias.
    #[must_use]
    pub const fn is_noise_shaping(self) -> bool {
        matches!(
            self,
            Self::NsLipshitz
                | Self::NsFWeighted
                | Self::NsModifiedEWeighted
                | Self::NsImprovedEWeighted
                | Self::NsShibata
                | Self::NsLowShibata
                | Self::NsHighShibata
        )
    }

    /// The method actually applied. See the module docs.
    #[must_use]
    pub fn resolve(self) -> Self {
        if self.is_noise_shaping() {
            tracing::warn!(
                requested = self.name(),
                "noise-shaping dither is not implemented; using triangular_hp"
            );
            Self::TriangularHighpass
        } else {
            self
        }
    }
}

/// The dither stage.
#[derive(Clone, Copy, Debug)]
pub struct Dither {
    method: DitherMethod,
    /// Amplitude of one quantisation step, in internal (±1.0) units.
    step: f64,
    scale: f64,
    seed: u64,
}

impl Dither {
    /// `bits` is the significant depth of the output format, or the value of
    /// `output_sample_bits` when the caller overrides it.
    #[must_use]
    pub fn new(method: DitherMethod, bits: u32, scale: f64, seed: u64) -> Self {
        let bits = bits.clamp(1, 64);
        // One LSB of a `bits`-deep integer, in the internal ±1.0 scale.
        let step = (-(f64::from(bits) - 1.0)).exp2();
        Self {
            method: method.resolve(),
            step,
            scale: if scale.is_finite() && scale >= 0.0 {
                scale
            } else {
                1.0
            },
            seed,
        }
    }

    #[must_use]
    pub const fn is_noop(&self) -> bool {
        matches!(self.method, DitherMethod::None)
    }

    /// Add noise to `n` samples of `plane` starting at `off`, for channel `ch`,
    /// where the first sample is at absolute stream position `pos`.
    pub fn apply<T: Internal>(&self, plane: &mut [T], off: usize, n: usize, ch: u32, pos: u64) {
        if self.is_noop() || self.scale == 0.0 {
            return;
        }
        let Some(slice) = plane.get_mut(off..off + n) else {
            return;
        };
        let amp = self.step * self.scale;
        for (i, v) in slice.iter_mut().enumerate() {
            let p = pos.wrapping_add(i as u64);
            let d = match self.method {
                DitherMethod::Rectangular => uniform(self.seed, ch, p) * amp,
                DitherMethod::Triangular => {
                    (uniform(self.seed, ch, p) + uniform(self.seed ^ 0x9e37, ch, p)) * amp
                }
                // d[n] = u[n] - u[n-1]: triangular by construction and
                // first-order highpass, so the same variance sits where the ear
                // is least sensitive.
                DitherMethod::TriangularHighpass => {
                    (uniform(self.seed, ch, p) - uniform(self.seed, ch, p.wrapping_sub(1))) * amp
                }
                _ => 0.0,
            };
            *v = v.add(T::from_f64(d));
        }
    }
}

/// A uniform deviate in `[-0.5, 0.5)`, a pure function of its arguments.
///
/// `SplitMix64`'s finaliser over a mixed key. It is not a cryptographic
/// generator and does not need to be; what it needs is to be stateless, so that
/// sample `p` gets the same noise however the caller chunked the stream.
fn uniform(seed: u64, ch: u32, pos: u64) -> f64 {
    let mut z = seed
        .wrapping_mul(0x9e37_79b9_7f4a_7c15)
        .wrapping_add(pos.wrapping_mul(0xbf58_476d_1ce4_e5b9))
        .wrapping_add(u64::from(ch).wrapping_mul(0x94d0_49bb_1331_11eb));
    z = z.wrapping_add(0x9e37_79b9_7f4a_7c15);
    z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    z ^= z >> 31;
    // 53 bits of mantissa, mapped to [-0.5, 0.5).
    ((z >> 11) as f64) * (1.0 / 9_007_199_254_740_992.0) - 0.5
}
