//! Quantisation dither for the float → integer path.
//!
//! # Scope, stated plainly
//!
//! All eleven `dither_method` values are implemented: `none`, `rectangular`,
//! `triangular`, `triangular_hp`, and the seven noise-shaping curves
//! (`lipshitz`, `f_weighted`, `modified_e_weighted`, `improved_e_weighted`,
//! `shibata`, `low_shibata`, `high_shibata`).
//!
//! The reference's default is `none`, which is directly observable: `flt → s16`
//! is a clean deterministic function of the input value with no per-sample
//! variation at all. So dither is opt-in on both sides and nothing here changes
//! the default path.
//!
//! # The noise-shaping curves are ours, not the reference's
//!
//! Plan 17 §B.6 states the clean-room problem plainly: the Lipshitz /
//! F-weighted / E-weighted family is published in Lipshitz, Vanderkooy &
//! Wannamaker, "Minimally Audible Noise Shaping" (JAES 39(11), 1991), and the
//! Shibata curves originate in SSRC, whose licensing is not on D3's
//! allowlist. Attempting either — reproducing the paper's exact tap values
//! from memory, or reading an SSRC-derived implementation — would be a
//! provenance failure even where it might be legally fine, because neither
//! could be *verified* here rather than merely asserted.
//!
//! So every one of the seven curves in `noise_shape` is **generated by us**,
//! the same decision plan 17 already made for Shibata specifically, just
//! applied uniformly: a minimum-phase error-feedback FIR is fit — by
//! homomorphic (cepstral) spectral factorization of a target noise power
//! spectrum, then truncated with a light exponential taper for stability of
//! the truncation — to a target curve derived from Terhardt's published
//! absolute-threshold-of-hearing approximation (Terhardt, "Calculating
//! virtual pitch", Hearing Research 1(2), 1979; the formula itself, not any
//! particular codebase's use of it, is the citation). `f_weighted` through
//! `improved_e_weighted` are the same design at increasing filter order (3,
//! 5, 7, 9 taps); `low_shibata`/`shibata`/`high_shibata` share one 14-tap
//! design scaled to 0.5×/1.0×/1.5× strength. See `noise_shape`'s doc for the
//! generation method in full and the measured perceptual-weighting numbers.
//! The option names are preserved for command-line compatibility; the curves
//! will not be bit-identical to the reference's, and are graded Equivalent
//! under the psychoacoustic criterion plan 17 §B.6 sets: *at least as good*,
//! not *the same*.
//!
//! # Determinism
//!
//! `none`/`rectangular`/`triangular`/`triangular_hp` are a pure function of
//! `(seed, channel, absolute sample position)` — no wall clock, no global
//! state, no per-call generator, so re-running gives the same bytes and
//! chunking the stream differently gives the same bytes too.
//!
//! Noise shaping cannot be: real error feedback is a filter over the
//! *content* (each `e[n]` depends on the actual sample value fed at every
//! prior position, not on position alone), which is exactly what makes it
//! shape noise around the signal rather than around a fixed pattern. It is
//! still deterministic — the same stream produces the same output on every
//! run — and it still needs to be *chunk-invariant* in the correct sense:
//! the same total sequential processing regardless of how a caller splits
//! `convert` calls. That is why [`NoiseShapeState`] exists as real persisted
//! state in the pipeline rather than being folded into the stateless
//! `Dither` value the way the other four methods are; see
//! `Pipeline::ns_state` in `resampler.rs`.

use vaco_core::Error;

use crate::convert::Internal;

pub mod noise_shape;

/// The `dither_method` option surface.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum DitherMethod {
    #[default]
    None,
    Rectangular,
    Triangular,
    TriangularHighpass,
    NsLipshitz,
    NsFWeighted,
    NsModifiedEWeighted,
    NsImprovedEWeighted,
    NsShibata,
    NsLowShibata,
    NsHighShibata,
}

impl DitherMethod {
    /// # Errors
    /// [`Error::Option`] for an unknown name.
    pub fn from_name(name: &str) -> Result<Self, Error> {
        Ok(match name {
            "none" => Self::None,
            "rectangular" => Self::Rectangular,
            "triangular" => Self::Triangular,
            "triangular_hp" => Self::TriangularHighpass,
            "lipshitz" => Self::NsLipshitz,
            "f_weighted" => Self::NsFWeighted,
            "modified_e_weighted" => Self::NsModifiedEWeighted,
            "improved_e_weighted" => Self::NsImprovedEWeighted,
            "shibata" => Self::NsShibata,
            "low_shibata" => Self::NsLowShibata,
            "high_shibata" => Self::NsHighShibata,
            _ => {
                return Err(Error::Option {
                    name: "dither_method".to_owned(),
                    detail: format!("unknown dither method `{name}`"),
                });
            }
        })
    }

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::None => "none",
            Self::Rectangular => "rectangular",
            Self::Triangular => "triangular",
            Self::TriangularHighpass => "triangular_hp",
            Self::NsLipshitz => "lipshitz",
            Self::NsFWeighted => "f_weighted",
            Self::NsModifiedEWeighted => "modified_e_weighted",
            Self::NsImprovedEWeighted => "improved_e_weighted",
            Self::NsShibata => "shibata",
            Self::NsLowShibata => "low_shibata",
            Self::NsHighShibata => "high_shibata",
        }
    }

    /// Whether this is one of the seven noise-shaping curves.
    #[must_use]
    pub const fn is_noise_shaping(self) -> bool {
        self.noise_shape_coeffs().is_some()
    }

    /// The error-feedback taps for a noise-shaping method, most-recent-error
    /// first (`coeffs[0]` multiplies `e[n-1]`), or `None` otherwise. See
    /// [`noise_shape`] for how these are generated.
    #[must_use]
    pub const fn noise_shape_coeffs(self) -> Option<&'static [f64]> {
        Some(match self {
            Self::NsLipshitz => &noise_shape::LIPSHITZ,
            Self::NsFWeighted => &noise_shape::F_WEIGHTED,
            Self::NsModifiedEWeighted => &noise_shape::MODIFIED_E_WEIGHTED,
            Self::NsImprovedEWeighted => &noise_shape::IMPROVED_E_WEIGHTED,
            Self::NsShibata => &noise_shape::SHIBATA,
            Self::NsLowShibata => &noise_shape::LOW_SHIBATA,
            Self::NsHighShibata => &noise_shape::HIGH_SHIBATA,
            Self::None | Self::Rectangular | Self::Triangular | Self::TriangularHighpass => {
                return None;
            }
        })
    }
}

/// The dither stage's fixed parameters. Genuinely stateless (`Copy`) even
/// though the struct also configures noise shaping: the *coefficients* are a
/// `'static` table selected by `method`, and the actual per-channel
/// feedback state lives separately in [`NoiseShapeState`], because that part
/// cannot be a pure function of position (see the module docs).
#[derive(Clone, Copy, Debug)]
pub struct Dither {
    method: DitherMethod,
    /// Amplitude of one quantisation step, in internal (±1.0) units.
    step: f64,
    scale: f64,
    seed: u64,
}

impl Dither {
    /// `bits` is the significant depth of the output format, or the value of
    /// `output_sample_bits` when the caller overrides it.
    #[must_use]
    pub fn new(method: DitherMethod, bits: u32, scale: f64, seed: u64) -> Self {
        let bits = bits.clamp(1, 64);
        // One LSB of a `bits`-deep integer, in the internal ±1.0 scale.
        let step = (-(f64::from(bits) - 1.0)).exp2();
        Self {
            method,
            step,
            scale: if scale.is_finite() && scale >= 0.0 {
                scale
            } else {
                1.0
            },
            seed,
        }
    }

    #[must_use]
    pub const fn is_noop(&self) -> bool {
        matches!(self.method, DitherMethod::None)
    }

    #[must_use]
    pub const fn is_noise_shaping(&self) -> bool {
        self.method.is_noise_shaping()
    }

    /// Tap count for a noise-shaping method, `0` otherwise. Sizes
    /// [`NoiseShapeState`].
    #[must_use]
    pub const fn taps(&self) -> usize {
        match self.method.noise_shape_coeffs() {
            Some(c) => c.len(),
            None => 0,
        }
    }

    /// Add noise to `n` samples of `plane` starting at `off`, for channel `ch`,
    /// where the first sample is at absolute stream position `pos`.
    ///
    /// For the four position-seeded methods only — see [`Dither::apply_shaped`]
    /// for noise shaping.
    pub fn apply<T: Internal>(&self, plane: &mut [T], off: usize, n: usize, ch: u32, pos: u64) {
        if self.is_noop() || self.scale == 0.0 || self.is_noise_shaping() {
            return;
        }
        let Some(slice) = plane.get_mut(off..off + n) else {
            return;
        };
        let amp = self.step * self.scale;
        for (i, v) in slice.iter_mut().enumerate() {
            let p = pos.wrapping_add(i as u64);
            let d = match self.method {
                DitherMethod::Rectangular => uniform(self.seed, ch, p) * amp,
                DitherMethod::Triangular => {
                    (uniform(self.seed, ch, p) + uniform(self.seed ^ 0x9e37, ch, p)) * amp
                }
                // d[n] = u[n] - u[n-1]: triangular by construction and
                // first-order highpass, so the same variance sits where the ear
                // is least sensitive.
                DitherMethod::TriangularHighpass => {
                    (uniform(self.seed, ch, p) - uniform(self.seed, ch, p.wrapping_sub(1))) * amp
                }
                _ => 0.0,
            };
            *v = v.add(T::from_f64(d));
        }
    }

    /// Error-feedback noise shaping: see the module docs for why this needs
    /// `history` (this channel's ring buffer, most-recent-error first,
    /// length [`Dither::taps`]) rather than being a pure function of
    /// position.
    ///
    /// TPDF dither (position-seeded, as in [`Dither::apply`]) is added at the
    /// same time — real error feedback alone still leaves the quantisation
    /// error correlated with the signal at the instant of rounding; adding
    /// dither before feeding the shaped value onward decorrelates that, which
    /// is standard practice for a shaped quantiser and not a reference to any
    /// external design (a dithered quantiser is textbook, not an expression
    /// of anyone's).
    pub fn apply_shaped<T: Internal>(
        &self,
        plane: &mut [T],
        off: usize,
        n: usize,
        ch: u32,
        pos: u64,
        history: &mut [f64],
    ) {
        let Some(coeffs) = self.method.noise_shape_coeffs() else {
            return;
        };
        if self.scale == 0.0 {
            return;
        }
        let Some(slice) = plane.get_mut(off..off + n) else {
            return;
        };
        let amp = self.step * self.scale;
        // A small TPDF term (a quarter of the shaping-free amplitude) breaks
        // up the periodic "idle tones" a pure error-feedback loop produces on
        // near-constant input — a well-known limit-cycle failure mode of
        // undithered noise shaping — without being large enough to swamp the
        // shaped component's own spectral benefit, which measurably happens
        // at full-strength TPDF (see the commit history on this file: an
        // earlier attempt at full-amplitude TPDF-plus-shaping measured worse,
        // not better, than plain TPDF alone under the same perceptual test).
        let tpdf_amp = amp * 0.25;
        for (i, v) in slice.iter_mut().enumerate() {
            let p = pos.wrapping_add(i as u64);
            let tpdf = (uniform(self.seed, ch, p) + uniform(self.seed ^ 0x9e37, ch, p)) * tpdf_amp;
            let mut feedback = 0.0;
            for (c, e) in coeffs.iter().zip(history.iter()) {
                feedback += c * e;
            }
            let x = v.to_f64();
            let driven = x + feedback * self.scale + tpdf;
            // Our own estimate of what the downstream integer quantiser will
            // do, purely to compute the error this filter feeds forward —
            // the *real* quantisation happens later, in `convert`, with
            // whatever rounding rule that path measured off the reference.
            let quantised = (driven / self.step).round() * self.step;
            let e = driven - quantised;
            history.copy_within(0..history.len().saturating_sub(1), 1);
            if let Some(h0) = history.first_mut() {
                *h0 = e;
            }
            *v = T::from_f64(driven);
        }
    }
}

/// A uniform deviate in `[-0.5, 0.5)`, a pure function of its arguments.
///
/// `SplitMix64`'s finaliser over a mixed key. It is not a cryptographic
/// generator and does not need to be; what it needs is to be stateless, so that
/// sample `p` gets the same noise however the caller chunked the stream.
fn uniform(seed: u64, ch: u32, pos: u64) -> f64 {
    let mut z = seed
        .wrapping_mul(0x9e37_79b9_7f4a_7c15)
        .wrapping_add(pos.wrapping_mul(0xbf58_476d_1ce4_e5b9))
        .wrapping_add(u64::from(ch).wrapping_mul(0x94d0_49bb_1331_11eb));
    z = z.wrapping_add(0x9e37_79b9_7f4a_7c15);
    z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
    z ^= z >> 31;
    // 53 bits of mantissa, mapped to [-0.5, 0.5).
    ((z >> 11) as f64) * (1.0 / 9_007_199_254_740_992.0) - 0.5
}

/// Per-channel error-feedback history for noise-shaping dither.
///
/// Deliberately **not** `Copy`, unlike [`Dither`]: this is genuine mutable
/// state that must persist across `convert` calls (see the module docs on
/// why it cannot be folded into a position-seeded pure function).
#[derive(Clone, Debug)]
pub struct NoiseShapeState {
    /// One ring buffer per channel; `history[ch][0]` is `e[n-1]`.
    history: Vec<Vec<f64>>,
}

impl NoiseShapeState {
    #[must_use]
    pub fn new(channels: usize, taps: usize) -> Self {
        Self {
            history: vec![vec![0.0; taps]; channels],
        }
    }

    pub fn reset(&mut self) {
        for h in &mut self.history {
            for v in h.iter_mut() {
                *v = 0.0;
            }
        }
    }

    pub fn channel_mut(&mut self, ch: usize) -> Option<&mut Vec<f64>> {
        self.history.get_mut(ch)
    }
}
