//! Audio sample-format conversion, channel rematrixing and rate conversion —
//! the `swresample` equivalent.
//!
//! Three independent stages plus a composition of them:
//!
//! | Type | Job |
//! |---|---|
//! | [`convert::convert`] | sample-format conversion, packed ↔ planar |
//! | [`MixMatrix`] / [`Rematrix`] | channel layout remapping and mixing |
//! | [`RateConvert`] | polyphase sample-rate conversion |
//! | [`Dither`] | quantisation dither for the down-conversion path |
//! | [`Resampler`] | all four, wired together |
//!
//! Each stage is public and independently usable. A codec that only needs
//! `s16 → f32` calls [`convert::convert`]; a mixer that only needs 5.1 → stereo
//! builds a [`MixMatrix`]. The reference exposes only the fused context.
//!
//! Every rounding decision here is a *measured* property of the reference
//! binary, not a design choice — [`convert`] states each one with the probe
//! that established it. Rate conversion is exact-rational: the phase
//! accumulator is a pair of integers, never a float, so with
//! `exact_rational` (the default) and a reduced denominator ≤
//! [`rate::MAX_EXACT_PHASES`] a stream of any length cannot drift. Timestamp
//! compensation (soft, hard, `async`, `first_pts` and the manual
//! [`Resampler::advance_pts`]/[`Resampler::set_compensation`] API) lives in
//! [`timestamp`], driven by measurements against the reference's `aresample`
//! filter. The seven noise-shaping curves in [`dither::noise_shape`] are
//! generated by us, not transcribed from the reference or SSRC, for the
//! clean-room reasons that module states. The Dolby Pro Logic
//! IIx/IIz/EX/Headphone `matrix_encoding` values reproduce the reference's
//! own fallback to an unencoded downmix, in [`mix::build_matrix`].

#![forbid(unsafe_code)]

pub mod buf;
pub mod convert;
pub mod design;
pub mod dither;
pub mod mix;
pub mod opts;
pub mod rate;
mod resampler;
pub mod timestamp;

pub use buf::{AudioMut, AudioRef, AudioSpec};
pub use dither::{Dither, DitherMethod};
pub use mix::{MatrixEncoding, MatrixShape, MixLevels, MixMatrix, Rematrix, build_matrix};
pub use opts::{Engine, FilterType, ResampleOptions};
pub use rate::RateConvert;
pub use resampler::{Resampler, default_layout};
pub use timestamp::MAX_COMPENSATION_SAMPLES;

/// The crate's error type is the shared taxonomy.
pub use vaco_core::Error;

/// `Result` with the shared error type.
pub type Result<T, E = Error> = core::result::Result<T, E>;
