// GENERATED DATA, hand-checked. See `docs/app/vaco-cli-core.md` for the
// extraction and probing method that produced it.
//
// Names, argument placeholders, scopes and specifier kinds are interface facts
// about ffmpeg 8.1 (D9 permits reproducing those). The help strings are NOT the
// reference's; they were written for Vaco, because D9 forbids reproducing help
// text. `-h` output therefore cannot be byte-identical, by design.
//
// `-i` does not appear in `ffmpeg -h full` at all — it is hidden from the
// grouped help — so it is appended by hand at the end.
static FFMPEG_OPTIONS: &[OptDesc] = &[

    o("L", None, bit::EXIT | bit::GLOBAL, "print the licence"),
    alias("license", None, bit::EXIT | bit::GLOBAL, "print the licence", "L", ""),
    o("h", Some("topic"), bit::EXIT | bit::GLOBAL, "print help on a topic"),
    o("version", None, bit::EXIT | bit::GLOBAL, "print the version"),
    o("muxers", None, bit::EXIT | bit::GLOBAL, "list muxers"),
    o("demuxers", None, bit::EXIT | bit::GLOBAL, "list demuxers"),
    o("devices", None, bit::EXIT | bit::GLOBAL, "list devices"),
    o("decoders", None, bit::EXIT | bit::GLOBAL, "list decoders"),
    o("encoders", None, bit::EXIT | bit::GLOBAL, "list encoders"),
    o("filters", None, bit::EXIT | bit::GLOBAL, "list filters"),
    o("pix_fmts", None, bit::EXIT | bit::GLOBAL, "list pixel formats"),
    o("layouts", None, bit::EXIT | bit::GLOBAL, "list channel layouts"),
    o("sample_fmts", None, bit::EXIT | bit::GLOBAL, "list sample formats"),
    alias("?", Some("topic"), bit::EXIT | bit::GLOBAL | bit::EXPERT, "print help on a topic", "h", ""),
    alias("help", Some("topic"), bit::EXIT | bit::GLOBAL | bit::EXPERT, "print help on a topic", "h", ""),
    alias("-help", Some("topic"), bit::EXIT | bit::GLOBAL | bit::EXPERT, "print help on a topic", "h", ""),
    o("buildconf", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "print the build configuration"),
    o("formats", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list container formats"),
    o("codecs", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list codecs"),
    o("bsfs", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list bitstream filters"),
    o("protocols", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list protocols"),
    o("dispositions", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list stream dispositions"),
    o("colors", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list named colours"),
    o("sources", Some("device"), bit::EXIT | bit::GLOBAL | bit::EXPERT, "list a device's input sources"),
    o("sinks", Some("device"), bit::EXIT | bit::GLOBAL | bit::EXPERT, "list a device's output sinks"),
    o("hwaccels", None, bit::EXIT | bit::GLOBAL | bit::EXPERT, "list hardware acceleration methods"),
    alias("v", Some("loglevel"), bit::HAS_ARG | bit::GLOBAL, "set the log level", "loglevel", ""),
    o("y", None, bit::GLOBAL, "overwrite output files without asking"),
    o("n", None, bit::GLOBAL, "refuse to overwrite output files"),
    o("print_graphs", None, bit::GLOBAL, "dump the execution graph to stderr"),
    o("print_graphs_file", Some("filename"), bit::HAS_ARG | bit::GLOBAL, "write the execution graph to a file"),
    o("print_graphs_format", Some("format"), bit::HAS_ARG | bit::GLOBAL, "choose the execution graph's writer"),
    o("stats", None, bit::GLOBAL, "print a progress report while running"),
    o("loglevel", Some("loglevel"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "set the log level"),
    o("report", None, bit::GLOBAL | bit::EXPERT, "write a debug log file for this run"),
    o("max_alloc", Some("bytes"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "cap a single allocation"),
    o("cpuflags", Some("flags"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "override detected CPU features"),
    o("cpucount", Some("count"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "override the detected CPU count"),
    o("hide_banner", Some("hide_banner"), bit::GLOBAL | bit::EXPERT, "suppress the version banner"),
    o("ignore_unknown", None, bit::GLOBAL | bit::EXPERT, "drop streams of unknown type"),
    o("copy_unknown", None, bit::GLOBAL | bit::EXPERT, "copy streams of unknown type"),
    o("recast_media", None, bit::GLOBAL | bit::EXPERT, "allow forcing a decoder of another media type"),
    o("benchmark", None, bit::GLOBAL | bit::EXPERT, "report timing for the whole run"),
    o("benchmark_all", None, bit::GLOBAL | bit::EXPERT, "report timing for every task"),
    o("progress", Some("url"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "write machine-readable progress to a URL"),
    o("stdin", None, bit::GLOBAL | bit::EXPERT, "enable or disable standard-input interaction"),
    o("timelimit", Some("limit"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "abort after this much CPU time"),
    o("dump", None, bit::GLOBAL | bit::EXPERT, "dump every input packet"),
    o("hex", None, bit::GLOBAL | bit::EXPERT, "include payloads in packet dumps"),
    o("frame_drop_threshold", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "threshold for dropping a late frame"),
    o("copyts", None, bit::GLOBAL | bit::EXPERT, "do not rebase input timestamps"),
    o("start_at_zero", None, bit::GLOBAL | bit::EXPERT, "shift copied timestamps to start at zero"),
    o("copytb", Some("mode"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "choose the time base when stream copying"),
    o("dts_delta_threshold", Some("threshold"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "discontinuity threshold on decode timestamps"),
    o("dts_error_threshold", Some("threshold"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "error threshold on decode timestamps"),
    o("xerror", Some("error"), bit::GLOBAL | bit::EXPERT, "exit on the first error"),
    o("abort_on", Some("flags"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "conditions that abort the run"),
    o("filter_threads", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "threads for simple filter graphs"),
    o("filter_buffered_frames", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "frames a filter graph may buffer"),
    o("filter_complex", Some("graph_description"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "define a complex filter graph"),
    o("filter_complex_threads", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "threads for complex filter graphs"),
    alias("lavfi", Some("graph_description"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "define a complex filter graph", "filter_complex", ""),
    o("filter_complex_script", Some("filename"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "read a complex filter graph from a file"),
    o("auto_conversion_filters", None, bit::GLOBAL | bit::EXPERT, "insert format conversion filters automatically"),
    o("stats_period", Some("time"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "how often to refresh progress output"),
    o("debug_ts", None, bit::GLOBAL | bit::EXPERT, "trace timestamps"),
    o("max_error_rate", Some("maximum error rate"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "decoding error ratio that fails the run"),
    o("vstats", None, bit::GLOBAL | bit::EXPERT, "write video coding statistics"),
    o("vstats_file", Some("file"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "file for video coding statistics"),
    o("vstats_version", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "video statistics format version"),
    o("sdp_file", Some("file"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "write the SDP description to a file"),
    o("init_hw_device", Some("args"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "create a hardware device"),
    o("filter_hw_device", Some("device"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "hardware device for filtering"),
    o("adrift_threshold", Some("threshold"), bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "deprecated, has no effect"),
    o("qphist", None, bit::GLOBAL | bit::EXPERT, "deprecated, has no effect"),
    o("vsync", None, bit::HAS_ARG | bit::GLOBAL | bit::EXPERT, "deprecated, use fps_mode"),
    o("f", Some("fmt"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT, "force the container format"),
    o("t", Some("duration"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT, "stop after this duration"),
    o("to", Some("time_stop"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT, "stop at this position"),
    o("ss", Some("time_off"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT, "start at this position"),
    o("bitexact", None, bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::EXPERT, "restrict output to bit-exact operations"),
    o("thread_queue_size", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::EXPERT, "packets the demuxer may queue"),
    o("sseof", Some("time_off"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "start at this position relative to the end"),
    o("seek_timestamp", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "seek by timestamp rather than by position"),
    o("accurate_seek", None, bit::PER_FILE | bit::INPUT | bit::EXPERT, "decode up to the exact seek position"),
    o("isync", Some("sync ref"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "input whose clock this input follows"),
    o("itsoffset", Some("time_off"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "shift this input's timestamps"),
    o("re", None, bit::PER_FILE | bit::INPUT | bit::EXPERT, "read the input at its native rate"),
    o("readrate", Some("speed"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "read the input at this multiple of native rate"),
    o("readrate_initial_burst", Some("seconds"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "read this much before rate limiting starts"),
    o("readrate_catchup", Some("speed"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "rate used to catch up after falling behind"),
    o("dump_attachment", Some("filename"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::TAKES_SPEC | bit::EXPERT, "write an attachment to a file"),
    o("stream_loop", Some("loop count"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::EXPERT, "repeat the input this many times"),
    o("find_stream_info", None, bit::PER_FILE | bit::INPUT | bit::EXPERT, "probe the input before opening it"),
    o("metadata", Some("key=value"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::TAKES_SPEC, "set a metadata entry"),
    o("map", Some("[-]input_file_id[:stream_specifier][,sync_file_id[:stream_specifier]]"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "select an input stream for the output"),
    o("map_metadata", Some("outfile[,metadata]:infile[,metadata]"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::TAKES_SPEC | bit::EXPERT, "copy metadata from an input"),
    o("map_chapters", Some("input_file_index"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "copy chapters from an input"),
    o("fs", Some("limit_size"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "stop once the output reaches this size"),
    o("timestamp", Some("time"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "set the recording timestamp"),
    o("program", Some("title=string:st=number..."), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::TAKES_SPEC | bit::EXPERT, "create a program from the given streams"),
    o("stream_group", Some("id=number:st=number..."), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::TAKES_SPEC | bit::EXPERT, "create a stream group from the given streams"),
    alias("dframes", Some("number"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "stop after this many data frames", "frames", "d"),
    o("target", Some("type"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "apply a preset for a standard target"),
    o("shortest", None, bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "stop when the shortest input ends"),
    o("shortest_buf_duration", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "buffering allowed while waiting for the shortest input"),
    alias("qscale", Some("q"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "use a fixed quality scale", "q", ""),
    o("profile", Some("profile"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "select the encoder profile"),
    o("attach", Some("filename"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "attach a file to the output"),
    o("muxdelay", Some("seconds"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "maximum demux-to-decode delay"),
    o("muxpreload", Some("seconds"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "initial demux-to-decode delay"),
    o("fpre", Some("filename"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT, "load options from a preset file"),
    o("c", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM, "select the codec, or copy to remux"),
    o("filter", Some("filter_graph"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM, "apply a filter graph"),
    alias("codec", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "select the codec, or copy to remux", "c", ""),
    o("pre", Some("preset"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "load a named preset"),
    o("itsscale", Some("scale"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT, "scale this stream's timestamps"),
    o("copyinkf", None, bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "copy leading non-keyframes"),
    o("copypriorss", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "keep frames that precede the start time"),
    o("frames", Some("number"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "stop after this many frames"),
    o("tag", Some("fourcc/tag"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "force the codec tag"),
    o("q", Some("q"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "use a fixed quality scale"),
    o("filter_script", Some("filename"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "read a filter graph from a file"),
    o("reinit_filter", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT, "rebuild the filter graph when input parameters change"),
    o("drop_changed", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT, "drop frames instead of rebuilding the filter graph"),
    o("discard", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT, "discard packets matching a condition"),
    o("disposition", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "set the output stream's disposition"),
    o("bits_per_raw_sample", Some("number"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "declare the sample depth"),
    o("stats_enc_pre", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "write encoder statistics before encoding"),
    o("stats_enc_post", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "write encoder statistics after encoding"),
    o("stats_mux_pre", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "write muxer statistics before muxing"),
    o("stats_enc_pre_fmt", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "format of the pre-encode statistics"),
    o("stats_enc_post_fmt", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "format of the post-encode statistics"),
    o("stats_mux_pre_fmt", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "format of the pre-mux statistics"),
    o("time_base", Some("ratio"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "suggest the output stream's time base"),
    o("enc_time_base", Some("ratio"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "set the encoder's time base"),
    o("bsf", Some("bitstream_filters"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "bitstream filters to apply"),
    o("max_muxing_queue_size", Some("packets"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "packets buffered while streams initialise"),
    o("muxing_queue_data_threshold", Some("bytes"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT, "bytes buffered before the queue limit applies"),
    o("r", Some("rate"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::VIDEO, "set the frame rate"),
    o("aspect", Some("aspect"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::VIDEO, "set the display aspect ratio"),
    o("vn", None, bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::VIDEO, "drop video streams"),
    alias("vcodec", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::VIDEO, "select the video codec", "c", "v"),
    alias("vf", Some("filter_graph"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::VIDEO, "apply a video filter graph", "filter", "v"),
    alias("b", Some("bitrate"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::VIDEO, "set the video bitrate", "b", "v"),
    alias("vframes", Some("number"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::VIDEO, "stop after this many video frames", "frames", "v"),
    o("fpsmax", Some("rate"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "cap the output frame rate"),
    o("pix_fmt", Some("format"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "set the pixel format"),
    o("display_rotation", Some("angle"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "set the display rotation"),
    o("display_hflip", None, bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "flip the display horizontally"),
    o("display_vflip", None, bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "flip the display vertically"),
    o("rc_override", Some("override"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "rate control override for an interval"),
    o("timecode", Some("hh:mm:ss[:;.]ff"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::VIDEO, "set the starting timecode"),
    o("pass", Some("n"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "select the encoding pass"),
    o("passlogfile", Some("prefix"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "prefix for the two-pass log"),
    o("intra_matrix", Some("matrix"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "intra quantiser matrix"),
    o("inter_matrix", Some("matrix"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "inter quantiser matrix"),
    o("chroma_intra_matrix", Some("matrix"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "chroma intra quantiser matrix"),
    alias("vtag", Some("fourcc/tag"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::EXPERT | bit::VIDEO, "force the video codec tag", "tag", "v"),
    o("fps_mode", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "how frame rate is reconciled"),
    o("force_fps", None, bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "do not negotiate the frame rate"),
    o("streamid", Some("streamIndex:value"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::VIDEO, "set an output stream's id"),
    o("force_key_frames", Some("timestamps"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "force key frames at these positions"),
    o("hwaccel", Some("hwaccel name"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "use hardware-accelerated decoding"),
    o("hwaccel_device", Some("devicename"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "device for hardware decoding"),
    o("hwaccel_output_format", Some("format"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "pixel format produced by hardware decoding"),
    o("autorotate", None, bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "apply the input's rotation metadata"),
    o("autoscale", None, bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "scale automatically at the end of the filter graph"),
    o("apply_cropping", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "apply the input's cropping metadata"),
    o("fix_sub_duration_heartbeat", None, bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "use this stream to split open subtitles"),
    alias("vpre", Some("preset"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::VIDEO, "load a video preset", "pre", "v"),
    o("top", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::VIDEO, "deprecated, use the setfield filter"),
    alias("aq", Some("quality"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::AUDIO, "set the audio quality", "q", "a"),
    o("ar", Some("rate"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::AUDIO, "set the sample rate"),
    o("ac", Some("channels"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::AUDIO, "set the channel count"),
    o("an", None, bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::AUDIO, "drop audio streams"),
    alias("acodec", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::AUDIO, "select the audio codec", "c", "a"),
    alias("ab", Some("bitrate"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::AUDIO, "set the audio bitrate", "b", "a"),
    alias("af", Some("filter_graph"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::AUDIO, "apply an audio filter graph", "filter", "a"),
    alias("aframes", Some("number"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::AUDIO, "stop after this many audio frames", "frames", "a"),
    o("apad", None, bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::AUDIO, "pad the audio with silence"),
    alias("atag", Some("fourcc/tag"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::AUDIO, "force the audio codec tag", "tag", "a"),
    o("sample_fmt", Some("format"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::AUDIO, "set the sample format"),
    o("channel_layout", Some("layout"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::AUDIO, "set the channel layout"),
    o("ch_layout", Some("layout"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::PER_STREAM | bit::EXPERT | bit::AUDIO, "set the channel layout"),
    o("guess_layout_max", None, bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::AUDIO, "channel count up to which the layout is guessed"),
    alias("apre", Some("preset"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::AUDIO, "load an audio preset", "pre", "a"),
    o("sn", None, bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::SUBTITLE, "drop subtitle streams"),
    alias("scodec", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::SUBTITLE, "select the subtitle codec", "c", "s"),
    alias("stag", Some("fourcc/tag"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::SUBTITLE, "force the subtitle codec tag", "tag", "s"),
    o("fix_sub_duration", None, bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::SUBTITLE, "derive subtitle durations from the next event"),
    o("canvas_size", Some("size"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::PER_STREAM | bit::EXPERT | bit::SUBTITLE, "set the subtitle canvas size"),
    alias("spre", Some("preset"), bit::HAS_ARG | bit::PER_FILE | bit::OUTPUT | bit::EXPERT | bit::SUBTITLE, "load a subtitle preset", "pre", "s"),
    alias("dcodec", Some("codec"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::EXPERT | bit::DATA, "select the data codec", "c", "d"),
    o("dn", None, bit::PER_FILE | bit::INPUT | bit::OUTPUT | bit::EXPERT | bit::DATA, "drop data streams"),
    o("i", Some("input_file"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OPENS_INPUT, "read from this input URL"),
];
