// GENERATED DATA, hand-checked. Same provenance as the ffmpeg table.
//
// ffprobe presents one flat "Main options" section, so scope is derived
// differently: everything that prints and exits is EXIT|GLOBAL, `-i` opens the
// input, and the remainder is GLOBAL — ffprobe has no per-file option groups at
// all, which is why its `-select_streams` is a single global value rather than
// a per-stream one.
static FFPROBE_OPTIONS: &[OptDesc] = &[

    o("L", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "print the licence"),
    alias("license", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "print the licence", "L", ""),
    o("h", Some("topic"), bit::EXIT | bit::GLOBAL | bit::HAS_ARG | bit::OPTIONAL_ARG, ValueKind::Custom, "print help on a topic"),
    alias("?", Some("topic"), bit::EXIT | bit::GLOBAL | bit::HAS_ARG | bit::OPTIONAL_ARG, ValueKind::Custom, "print help on a topic", "h", ""),
    alias("help", Some("topic"), bit::EXIT | bit::GLOBAL | bit::HAS_ARG | bit::OPTIONAL_ARG, ValueKind::Custom, "print help on a topic", "h", ""),
    alias("-help", Some("topic"), bit::EXIT | bit::GLOBAL | bit::HAS_ARG | bit::OPTIONAL_ARG, ValueKind::Custom, "print help on a topic", "h", ""),
    o("version", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "print the version"),
    o("buildconf", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "print the build configuration"),
    o("formats", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list container formats"),
    o("muxers", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list muxers"),
    o("demuxers", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list demuxers"),
    o("devices", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list devices"),
    o("codecs", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list codecs"),
    o("decoders", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list decoders"),
    o("encoders", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list encoders"),
    o("bsfs", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list bitstream filters"),
    o("protocols", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list protocols"),
    o("filters", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list filters"),
    o("pix_fmts", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list pixel formats"),
    o("layouts", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list channel layouts"),
    o("sample_fmts", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list sample formats"),
    o("dispositions", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list stream dispositions"),
    o("colors", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list named colours"),
    o("loglevel", Some("loglevel"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "set the log level"),
    alias("v", Some("loglevel"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "set the log level", "loglevel", ""),
    o("report", None, bit::GLOBAL, ValueKind::None, "write a debug log file for this run"),
    o("max_alloc", Some("bytes"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "cap a single allocation"),
    o("cpuflags", Some("flags"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Expr, "override detected CPU features"),
    o("cpucount", Some("count"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Expr, "override the detected CPU count"),
    o("hide_banner", Some("hide_banner"), bit::GLOBAL, ValueKind::None, "suppress the version banner"),
    o("sources", Some("device"), bit::EXIT | bit::GLOBAL, ValueKind::None, "list a device's input sources"),
    o("sinks", Some("device"), bit::EXIT | bit::GLOBAL, ValueKind::None, "list a device's output sinks"),
    o("f", Some("format"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "force the container format"),
    o("unit", None, bit::GLOBAL, ValueKind::None, "print units alongside values"),
    o("prefix", None, bit::GLOBAL, ValueKind::None, "use SI prefixes on values"),
    o("byte_binary_prefix", None, bit::GLOBAL, ValueKind::None, "use binary prefixes for byte counts"),
    o("sexagesimal", None, bit::GLOBAL, ValueKind::None, "print times as HH:MM:SS.mmm"),
    o("pretty", None, bit::GLOBAL, ValueKind::None, "format values for reading"),
    o("output_format", Some("format"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "select the output writer"),
    alias("print_format", None, bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "select the output writer", "output_format", ""),
    alias("of", Some("format"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "select the output writer", "output_format", ""),
    o("select_streams", Some("stream_specifier"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "restrict output to matching streams"),
    o("sections", None, bit::EXIT | bit::GLOBAL, ValueKind::None, "list the output sections"),
    o("data_dump_format", None, bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "format for dumped payloads"),
    o("show_data", None, bit::GLOBAL, ValueKind::None, "dump packet and frame payloads"),
    o("show_data_hash", None, bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "hash packet and frame payloads"),
    o("show_error", None, bit::GLOBAL, ValueKind::None, "print the error section"),
    o("show_format", None, bit::GLOBAL, ValueKind::None, "print the container section"),
    o("show_frames", None, bit::GLOBAL, ValueKind::None, "print one section per frame"),
    o("show_entries", Some("entry_list"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "restrict output to these sections and fields"),
    o("show_log", None, bit::HAS_ARG | bit::GLOBAL, ValueKind::Int, "print the decoder log"),
    o("show_packets", None, bit::GLOBAL, ValueKind::None, "print one section per packet"),
    o("show_programs", None, bit::GLOBAL, ValueKind::None, "print the program sections"),
    o("show_stream_groups", None, bit::GLOBAL, ValueKind::None, "print the stream group sections"),
    o("show_streams", None, bit::GLOBAL, ValueKind::None, "print the stream sections"),
    o("show_chapters", None, bit::GLOBAL, ValueKind::None, "print the chapter sections"),
    o("count_frames", None, bit::GLOBAL, ValueKind::None, "count frames per stream"),
    o("count_packets", None, bit::GLOBAL, ValueKind::None, "count packets per stream"),
    o("show_program_version", None, bit::GLOBAL, ValueKind::None, "print this program's version section"),
    o("show_library_versions", None, bit::GLOBAL, ValueKind::None, "print the library version sections"),
    o("show_versions", None, bit::GLOBAL, ValueKind::None, "print every version section"),
    o("show_pixel_formats", None, bit::GLOBAL, ValueKind::None, "print the pixel format sections"),
    o("show_optional_fields", None, bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "when to print fields that may be absent"),
    o("show_private_data", None, bit::GLOBAL, ValueKind::None, "print codec-private fields"),
    alias("private", None, bit::GLOBAL, ValueKind::None, "print codec-private fields", "show_private_data", ""),
    o("analyze_frames", None, bit::GLOBAL, ValueKind::None, "decode frames to fill in missing information"),
    o("bitexact", None, bit::GLOBAL, ValueKind::None, "restrict output to bit-exact operations"),
    o("read_intervals", Some("read_intervals"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Custom, "restrict reading to these intervals"),
    o("i", Some("input_file"), bit::HAS_ARG | bit::PER_FILE | bit::INPUT | bit::OPENS_INPUT, ValueKind::Str, "read from this input URL"),
    o("o", Some("output_file"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "write output to this file"),
    o("print_filename", Some("print_file"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "override the filename printed in the output"),
    o("find_stream_info", None, bit::GLOBAL, ValueKind::None, "probe the input before opening it"),
    o("c", Some("decoder_name"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "force a decoder"),
    alias("codec", Some("decoder_name"), bit::HAS_ARG | bit::GLOBAL, ValueKind::Str, "force a decoder", "c", ""),
];
