//! `cellauto` — a one-dimensional elementary cellular automaton (Wolfram's
//! rule numbering, 0..255), one new generation per output row, in `monob`.
//!
//! `ffmpeg -h filter=cellauto` documents `filename`/`f`, `pattern`/`p`,
//! `rate`/`r`, `size`/`s` (no stated default — this crate uses `320x240`,
//! its own choice, documented below), `rule` (default 110, Wolfram's
//! Turing-complete rule), `random_fill_ratio`/`ratio`, `random_seed`/`seed`,
//! `scroll` (default true), `start_full`/`full`, and `stitch` (default
//! true, wrap the row's edges).
//!
//! # What is exact, and what is not
//!
//! **The rule itself is exact and closed-form**, independent of any
//! reference implementation: Wolfram's own elementary-CA definition. A
//! cell's next state is bit `(left*4 + centre*2 + right)` of the 8-bit
//! `rule` number — this is checked directly in this module's tests against
//! held-out `(left, centre, right) -> next` triples for `rule = 110` and
//! `rule = 30`, both well-known and independently checkable from the rule
//! *number* alone (rule 110's rightmost bit is `0`, so `(1,1,1) -> 0`;
//! rule 30 is antisymmetric in a way rule 110 is not).
//!
//! **`pattern`/`filename`** (an explicit initial row, given as a string of
//! `_`/`x`-style cells) drive the automaton deterministically from there —
//! exact, given the rule above.
//!
//! **Without an explicit pattern**, the reference randomly fills the
//! initial row per `random_fill_ratio`/`random_seed`. This crate's `seed`
//! handling does not reproduce the reference's own RNG bit stream — see
//! [`crate::rng`] — so **the random-fill default path is algorithmically
//! faithful (a real Bernoulli fill at the requested ratio) but not
//! bit-exact**, and this crate's `320x240` default frame size is its own
//! choice rather than a measured one, since `-h` states no default. See
//! `docs/filter/vaco-filter-source.md`.

use vaco_core::{MediaType, Rational, Result, Timestamp};
use vaco_filter_core::adapt::{SourceFilter, Sourced};
use vaco_filter_core::negotiate::{Constraint, FormatSet, NodeFormats};
use vaco_filter_core::{FilterContext, FilterDesc, FilterFlags, LinkFormat, Pad};
use vaco_frame::Frame;
use vaco_opts::OptionsExt as _;
use vaco_pixfmt::PixFmt;

use crate::rng::{SplitMix64, resolve_seed};
use vaco_filter_graph::registry::{Instance, Instantiate};

#[derive(Debug, Clone, vaco_opts::Options)]
#[options(name = "cellauto", help = "create pattern generated by an elementary cellular automaton")]
pub(crate) struct Opts {
    #[opt(name = "pattern", alias = "p", help = "set initial pattern", default = String::new(), flags(filtering))]
    pub pattern: String,
    #[opt(name = "rate", alias = "r", help = "set video rate", default = vaco_opts::VideoRate(Rational::new(25, 1)), flags(filtering))]
    pub rate: vaco_opts::VideoRate,
    #[opt(name = "size", alias = "s", help = "set video size", default = (320, 240), flags(filtering))]
    pub size: (u32, u32),
    #[opt(name = "rule", help = "set rule", default = 110, range = 0..=255, flags(filtering))]
    pub rule: i32,
    #[opt(name = "random_fill_ratio", alias = "ratio", help = "set fill ratio for filling initial grid randomly", default = 0.618_034, range = 0.0..=1.0, flags(filtering))]
    pub random_fill_ratio: f64,
    #[opt(name = "random_seed", alias = "seed", help = "set the seed for filling the initial grid randomly", default = -1_i64, flags(filtering))]
    pub random_seed: i64,
    #[opt(name = "scroll", help = "scroll pattern downward", default = true, flags(filtering))]
    pub scroll: bool,
    #[opt(name = "stitch", help = "stitch boundaries", default = true, flags(filtering))]
    pub stitch: bool,
}

impl Opts {
    fn parse(args: Option<&str>) -> std::result::Result<Self, String> {
        let mut o = Self::default();
        if let Some(text) = args {
            o.set_from_string(text, "=", ":").map_err(|e| e.to_string())?;
        }
        Ok(o)
    }
}

pub const DESC: FilterDesc = FilterDesc {
    name: "cellauto",
    description: "Create pattern generated by an elementary cellular automaton",
    inputs: &[],
    outputs: &[Pad {
        name: "default",
        media_type: MediaType::Video,
    }],
    flags: FilterFlags::empty(),
};

/// One elementary-CA generation step, per Wolfram's rule numbering.
///
/// `rule` bit `left*4 + centre*2 + right` gives the next state of a cell
/// whose 3-neighbourhood is `(left, centre, right)`.
pub(crate) fn step(row: &[bool], rule: u8, stitch: bool) -> Vec<bool> {
    let n = row.len();
    let mut out = vec![false; n];
    for (i, slot) in out.iter_mut().enumerate() {
        let left = if i == 0 {
            if stitch {
                row.last().copied().unwrap_or(false)
            } else {
                false
            }
        } else {
            row.get(i - 1).copied().unwrap_or(false)
        };
        let centre = row.get(i).copied().unwrap_or(false);
        let right = if i + 1 == n {
            if stitch {
                row.first().copied().unwrap_or(false)
            } else {
                false
            }
        } else {
            row.get(i + 1).copied().unwrap_or(false)
        };
        let idx = (u8::from(left) << 2) | (u8::from(centre) << 1) | u8::from(right);
        *slot = (rule >> idx) & 1 == 1;
    }
    out
}

fn parse_pattern(pattern: &str, width: usize) -> Vec<bool> {
    let mut row: Vec<bool> = pattern.chars().map(|c| c != '0' && c != '_').collect();
    row.resize(width, false);
    row
}

fn random_row(width: usize, ratio: f64, seed: u64) -> Vec<bool> {
    let mut rng = SplitMix64::new(seed);
    (0..width).map(|_| rng.next_f64() < ratio).collect()
}

#[derive(Debug)]
struct Source {
    width: u32,
    height: u32,
    rule: u8,
    stitch: bool,
    row: Vec<bool>,
    frame_rate: Rational,
    next: i64,
}

impl SourceFilter for Source {
    fn configure(&mut self, ctx: &mut FilterContext<'_>) -> Result<()> {
        if let Some(mut out) = ctx.output_link(0).cloned() {
            if let LinkFormat::Video {
                width,
                height,
                time_base,
                frame_rate,
                ..
            } = &mut out
            {
                *width = self.width;
                *height = self.height;
                *time_base = self.frame_rate.inverse();
                *frame_rate = self.frame_rate;
            }
            ctx.set_output_link(0, out);
        }
        Ok(())
    }

    fn produce(&mut self, ctx: &mut FilterContext<'_>) -> Result<Option<Frame>> {
        let mut frame = ctx
            .pool()
            .acquire_video(PixFmt::Gray8, self.width, self.height)?;
        if let Some(mut plane) = frame.plane_mut(0) {
            for row_idx in 0..plane.rows() {
                if let Some(dst) = plane.row_mut(row_idx) {
                    for (px, &cell) in dst.iter_mut().zip(self.row.iter()) {
                        *px = if cell { 255 } else { 0 };
                    }
                }
                self.row = step(&self.row, self.rule, self.stitch);
            }
        }
        frame.pts = Timestamp::new(self.next);
        frame.time_base = self.frame_rate.inverse();
        frame.duration = vaco_core::Duration(1);
        self.next = self.next.saturating_add(1);
        Ok(Some(frame))
    }

    fn end_pts(&self) -> Timestamp {
        Timestamp::new(self.next)
    }

    fn flush_state(&mut self) {
        self.next = 0;
    }
}

/// Same defensive purpose as `life`'s `MAX_CELLS`: the initial row is a
/// plain `Vec<bool>`, not a `vaco_frame` plane, so nothing else bounds it.
const MAX_ROW_CELLS: u64 = 1 << 26;

pub(crate) fn create(req: &Instantiate<'_>) -> std::result::Result<Instance, String> {
    let opts = Opts::parse(req.args)?;
    let (width, height) = opts.size;
    if u64::from(width) > MAX_ROW_CELLS {
        return Err(format!(
            "cellauto: width {width} exceeds the {MAX_ROW_CELLS}-cell limit"
        ));
    }
    let rate = opts.rate.0;
    #[allow(
        clippy::cast_sign_loss,
        clippy::cast_possible_truncation,
        reason = "rule is range-checked to 0..=255"
    )]
    let rule = opts.rule as u8;
    let row = if opts.pattern.is_empty() {
        let seed = resolve_seed(opts.random_seed, 0xCE11_AE10);
        random_row(width as usize, opts.random_fill_ratio, seed)
    } else {
        parse_pattern(&opts.pattern, width as usize)
    };
    let source = Source {
        width,
        height,
        rule,
        stitch: opts.stitch,
        row,
        frame_rate: rate,
        next: 0,
    };
    Ok(Instance {
        desc: DESC,
        formats: NodeFormats {
            inputs: Vec::new(),
            outputs: vec![FormatSet {
                pixel_formats: Some(Constraint::Exact(PixFmt::Gray8)),
                ..FormatSet::default()
            }],
            ties: Vec::new(),
            label: req.instance.to_owned(),
        },
        filter: Box::new(Sourced::new(source)),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rule_110_matches_the_wolfram_definition() {
        // Rule 110 = 0b01101110. Bit index = left*4+centre*2+right.
        // (1,1,1) -> bit 7 = 0.
        let row = vec![true, true, true];
        let next = step(&row, 110, true);
        assert_eq!(next, vec![false, false, false]);
    }

    #[test]
    fn rule_30_matches_the_wolfram_definition() {
        // Rule 30 = 0b00011110. A single live cell in a stitched all-dead
        // row: (0,0,1)->bit1=1, (0,1,0)->bit2=1, (1,0,0)->bit4=1 for the
        // cell itself and its two neighbours; everything else is 0.
        let mut row = vec![false; 7];
        if let Some(c) = row.get_mut(3) {
            *c = true;
        }
        let next = step(&row, 30, true);
        assert_eq!(next, vec![false, false, true, true, true, false, false]);
    }

    #[test]
    fn stitch_wraps_the_edges() {
        let row = vec![true, false, false, false, true];
        // With stitch, the left neighbour of index 0 is the last cell, and
        // vice versa -- verified indirectly by checking rule 0 (always
        // dead) does not panic on either edge and rule 255 (always alive)
        // fills solid regardless of boundary handling.
        let all_dead = step(&row, 0, true);
        assert!(all_dead.iter().all(|&c| !c));
        let all_alive = step(&row, 255, true);
        assert!(all_alive.iter().all(|&c| c));
    }

    #[test]
    fn pattern_parses_x_and_underscore() {
        let row = parse_pattern("x_x_x", 5);
        assert_eq!(row, vec![true, false, true, false, true]);
    }

    #[test]
    fn creatable_with_no_arguments() {
        let req = Instantiate {
            name: "cellauto",
            instance: "cellauto",
            args: None,
            arguments: &[],
        };
        assert!(create(&req).is_ok());
    }

    #[test]
    fn explicit_pattern_is_deterministic() {
        let req = Instantiate {
            name: "cellauto",
            instance: "cellauto",
            args: Some("pattern=x:rule=110:size=8x4"),
            arguments: &[],
        };
        assert!(create(&req).is_ok());
    }
}
