#!/usr/bin/env python3
"""Generate the `vaco` public facade from metadata and one JSON descriptor."""

from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
import re
from typing import Any


REPOSITORY = Path(__file__).resolve().parents[1]


def load(path: Path) -> dict[str, Any]:
    """Load one Cargo metadata or facade descriptor JSON document."""
    with path.open(encoding="utf-8") as file:
        return json.load(file)


def closure(metadata: dict[str, Any], roots: list[str]) -> tuple[dict[str, Any], set[str]]:
    """Follow only normal/build dependency edges from the descriptor roots."""
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    pending = [package["id"] for package in packages.values() if package["name"] in roots]
    found = {packages[package_id]["name"] for package_id in pending}
    if set(roots) != found:
        raise ValueError(f"missing facade roots: {', '.join(sorted(set(roots) - found))}")
    result: set[str] = set()
    while pending:
        package_id = pending.pop()
        if package_id in result:
            continue
        result.add(package_id)
        pending.extend(
            dependency["pkg"]
            for dependency in nodes[package_id].get("deps", [])
            if any(kind.get("kind") in (None, "build") for kind in dependency["dep_kinds"])
        )
    return packages, result


def rust_name(package: str) -> str:
    """Return Cargo's default Rust crate name for a package identifier."""
    return package.replace("-", "_")


def public_name(package: str, group: str = "") -> str:
    """Make a collision-resistant module name beneath a curated namespace."""
    prefixes = {
        "codec": (("vaco-codec-", ""), ("vaco-parse-", "parse_")),
        "filter": (("vaco-filter-", ""),),
        "format": (
            ("vaco-format-", ""),
            ("vaco-demux-", "demux_"),
            ("vaco-mux-", "mux_"),
            ("vaco-bsf-", "bsf_"),
        ),
        "io": (("vaco-protocol-", ""),),
    }
    for prefix, replacement in prefixes.get(group, ()):
        if package.startswith(prefix):
            return f"{replacement}{package.removeprefix(prefix).replace('-', '_')}"
    return package.removeprefix("vaco-").replace("-", "_")


def namespace(package: dict[str, Any], descriptor: dict[str, Any]) -> str:
    """Classify a package by the descriptor's path prefixes."""
    relative = Path(package["manifest_path"]).resolve().relative_to(REPOSITORY).as_posix()
    for prefix, group in descriptor["namespaces"].items():
        if relative.startswith(prefix):
            return group
    raise ValueError(f"no facade namespace for {package['name']} at {relative}")


def render(
    descriptor: dict[str, Any], default_metadata: dict[str, Any], all_metadata: dict[str, Any]
) -> tuple[str, str, str]:
    """Emit the facade manifest, library, and package README from one descriptor."""
    roots = descriptor["source_roots"]
    default_packages, default_closure = closure(default_metadata, roots)
    all_packages, all_closure = closure(all_metadata, roots)
    default_names = {default_packages[package_id]["name"] for package_id in default_closure}
    internal = [
        package
        for package_id, package in all_packages.items()
        if package_id in all_closure
        and Path(package["manifest_path"]).resolve().is_relative_to(REPOSITORY)
    ]
    internal.sort(key=lambda package: package["name"])
    registry = next(package for package in internal if package["name"] == descriptor["registry_package"])
    registry_features = registry["features"]
    feature_for_package: dict[str, list[str]] = {}
    for feature, members in registry_features.items():
        for member in members:
            if member.startswith("dep:"):
                feature_for_package.setdefault(member.removeprefix("dep:"), []).append(feature)

    manifest = [
        "# @generated by scripts/gen-vaco-facade.py; do not edit by hand.",
        "[package]",
        'name = "vaco"',
        'description = "Vaco public media API plus vvmpeg and vvprobe binaries."',
        "version.workspace = true",
        "edition.workspace = true",
        "rust-version.workspace = true",
        "license.workspace = true",
        "repository.workspace = true",
        "authors.workspace = true",
        'readme = "README.md"',
        "",
        "[lib]",
        'name = "vaco"',
        'path = "src/lib.rs"',
        "",
        "[[bin]]",
        'name = "vvmpeg"',
        'path = "src/bin/vvmpeg.rs"',
        "",
        "[[bin]]",
        'name = "vvprobe"',
        'path = "src/bin/vvprobe.rs"',
        "",
        "[features]",
        "default = []",
    ]
    dependencies: list[str] = []
    library = [
        "//! Vaco's stable, namespaced public API.",
        "//!",
        "//! This file is generated from `release/vaco-public-api.json`; edit the",
        "//! descriptor and rerun `scripts/gen-vaco-facade.py`, not this output.",
        "#![forbid(unsafe_code)]",
        "#![doc = include_str!(\"../README.md\")]",
        "",
        "/// Presentation helpers used by the installed command wrappers.",
        "pub mod command {",
        "    /// Rebrand exact, static presentation lines without changing user data.",
        "    #[must_use]",
        "    pub fn rebrand_static_lines(bytes: &[u8], replacements: &[(&[u8], &[u8])]) -> Vec<u8> {",
        "        let mut rendered = Vec::new();",
        "        for line in bytes.split_inclusive(|byte| *byte == b'\\n') {",
        "            let (body, newline) = line",
        "                .strip_suffix(b\"\\n\")",
        "                .map_or((line, false), |body| (body, true));",
        "            if let Some((_, installed)) = replacements.iter().find(|(legacy, _)| body == *legacy) {",
        "                rendered.extend_from_slice(installed);",
        "                if newline {",
        "                    rendered.push(b'\\n');",
        "                }",
        "            } else {",
        "                rendered.extend_from_slice(line);",
        "            }",
        "        }",
        "        rendered",
        "    }",
        "}",
        "",
    ]
    groups: dict[str, list[tuple[dict[str, Any], list[str]]]] = {}
    for package in internal:
        if package["name"] == "vaco":
            continue
        group = namespace(package, descriptor)
        is_default = package["name"] in default_names
        features = [] if is_default else sorted(feature_for_package.get(package["name"], []))
        if not is_default and not features:
            features = [f"api-{public_name(package['name'], group)}"]
        for feature in features:
            entries = [f"dep:{package['name']}"]
            if feature in registry_features:
                entries.insert(0, f"{descriptor['registry_package']}/{feature}")
            manifest.append(f'"{feature}" = [{", ".join(json.dumps(item) for item in entries)}]')
        manifest_path = Path(package["manifest_path"]).resolve()
        target_dir = REPOSITORY / "crates/app/vaco"
        path = manifest_path.parent.relative_to(target_dir.parent) if False else Path(
            __import__("os").path.relpath(manifest_path.parent, target_dir)
        )
        optional = "" if is_default else ", optional = true"
        dependencies.append(
            f'{package["name"]} = {{ path = "{path.as_posix()}", version = "={package["version"]}"{optional} }}'
        )
        root_export = descriptor["root_exports"].get(package["name"])
        if root_export:
            if features:
                conditions = ", ".join(f"feature = {json.dumps(feature)}" for feature in features)
                library.append(
                    f"#[cfg(feature = {json.dumps(features[0])})]"
                    if len(features) == 1
                    else f"#[cfg(any({conditions}))]"
                )
            library.append(f"pub use {rust_name(package['name'])} as {root_export};")
        else:
            groups.setdefault(group, []).append((package, features))
    manifest.extend(["", "[dependencies]", *dependencies, ""])
    manifest.append("[lints]")
    manifest.append("workspace = true")
    manifest.extend(["", "[package.metadata.vaco]", "layer = 7"])
    for group, packages in sorted(groups.items()):
        library.extend(["", f"pub mod {group} {{"])
        alias_counts: dict[str, int] = {}
        for package, _ in packages:
            alias = public_name(package["name"], group)
            alias_counts[alias] = alias_counts.get(alias, 0) + 1
        for package, features in packages:
            if features:
                conditions = ", ".join(f"feature = {json.dumps(feature)}" for feature in features)
                library.append(
                    f"    #[cfg(feature = {json.dumps(features[0])})]"
                    if len(features) == 1
                    else f"    #[cfg(any({conditions}))]"
                )
            alias = public_name(package["name"], group)
            if alias_counts[alias] > 1:
                alias = package["name"].removeprefix("vaco-").replace("-", "_")
            library.append(f"    pub use {rust_name(package['name'])} as {alias};")
        library.append("}")
    readme = """# vaco

`vaco` is Vaco's public Rust facade. `cargo install vaco` installs exactly
`vvmpeg` and `vvprobe`:

```sh
cargo install vaco
vvmpeg -i input.mp4 output.mkv
vvprobe -show_format -show_streams input.mp4
```

## Library

The facade uses namespaces, rather than a collision-prone prelude. This is a
real API entry point for stream-specifier logic:

```rust
use vaco::core::core::MediaType;

assert_eq!(MediaType::Video.specifier_char(), 'v');
```

Packets use the same bounded allocation model as the rest of the pipeline:

```rust
use vaco::{
    core::{core::Error, limits::{Budget, Limits}},
    media::packet::Packet,
};

fn make_packet() -> Result<Packet, Error> {
    let mut budget = Budget::new(Limits::strict());
    Packet::from_slice(&mut budget, &[0, 0, 1, 0x67])
}

let packet = make_packet()?;
assert_eq!(packet.payload(), &[0, 0, 1, 0x67]);
# Ok::<(), Error>(())
```

Registries expose the components enabled in this build:

```rust
assert!(vaco::registry::demuxer_by_name("mp4").is_some());
```

## Scope, compatibility, and licensing

Vaco is an experimental, clean-room Rust media stack; its ordinary crates
forbid unsafe Rust. `vvmpeg` and `vvprobe` follow parts of the ffmpeg/ffprobe
command model, but compatibility is incomplete across codecs, formats,
filters, protocols, options, and output details. Patent-gated APIs are opt-in.

FFmpeg is a mature, broader C ecosystem; its effective licence depends on the
configured LGPL/GPL components. Vaco is GPL-3.0-or-later and does not read
FFmpeg source: it uses published specifications and black-box reference-binary
checks. Same-session CPU-work comparisons show mixed performance, with codec
paths still behind; Vaco is not yet a performance-sensitive production
replacement for FFmpeg.
"""
    return "\n".join(manifest) + "\n", "\n".join(library) + "\n", readme


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--default-metadata", required=True, type=Path)
    parser.add_argument("--all-features-metadata", required=True, type=Path)
    parser.add_argument("--descriptor", type=Path, default=REPOSITORY / "release/vaco-public-api.json")
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args()
    manifest, library, readme = render(
        load(args.descriptor), load(args.default_metadata), load(args.all_features_metadata)
    )
    output = args.output_dir
    (output / "src/bin").mkdir(parents=True, exist_ok=True)
    (output / "Cargo.toml").write_text(manifest, encoding="utf-8")
    (output / "src/lib.rs").write_text(library, encoding="utf-8")
    (output / "README.md").write_text(readme, encoding="utf-8")
    (output / "tests").mkdir(parents=True, exist_ok=True)
    (output / "tests/command_branding.rs").write_text(
        "#![allow(\n"
        "    clippy::expect_used,\n    clippy::panic,\n    clippy::unwrap_used,\n"
        "    reason = \"a failing assertion in a test is a failing test\"\n)]\n\n"
        "use std::process::{Command, Output};\n\n"
        "fn command(name: &str) -> Command {\n"
        "    match name {\n"
        "        \"vvmpeg\" => Command::new(env!(\"CARGO_BIN_EXE_vvmpeg\")),\n"
        "        \"vvprobe\" => Command::new(env!(\"CARGO_BIN_EXE_vvprobe\")),\n"
        "        _ => panic!(\"unknown facade command: {name}\"),\n"
        "    }\n}\n\n"
        "fn output(name: &str, arguments: &[&str]) -> Output {\n"
        "    command(name).args(arguments).output().expect(\"run facade command\")\n}\n\n"
        "#[test]\nfn installed_commands_brand_their_help() {\n"
        "    let vvmpeg = output(\"vvmpeg\", &[\"--help\"]);\n"
        "    let vvprobe = output(\"vvprobe\", &[\"--help\"]);\n"
        "    let vvmpeg_stderr = String::from_utf8_lossy(&vvmpeg.stderr);\n"
        "    let vvprobe_stdout = String::from_utf8_lossy(&vvprobe.stdout);\n"
        "    assert!(vvmpeg.status.success(), \"{vvmpeg:?}\");\n"
        "    assert!(vvprobe.status.success(), \"{vvprobe:?}\");\n"
        "    assert!(vvmpeg_stderr.contains(\"vvmpeg version\"), \"{vvmpeg_stderr}\");\n"
        "    assert!(vvprobe_stdout.contains(\"usage: vvprobe \"), \"{vvprobe_stdout}\");\n}\n\n"
        "#[test]\nfn vvmpeg_preserves_a_user_path_containing_legacy_name() {\n"
        "    let output = output(\"vvmpeg\", &[\"-i\", \"vaco-user-path-does-not-exist.mp4\", \"-f\", \"null\", \"-\"]);\n"
        "    let stderr = String::from_utf8_lossy(&output.stderr);\n"
        "    assert!(!output.status.success(), \"{output:?}\");\n"
        "    assert!(stderr.contains(\"vvmpeg version\"), \"{stderr}\");\n"
        "    assert!(stderr.contains(\"vaco-user-path-does-not-exist.mp4\"), \"{stderr}\");\n}\n",
        encoding="utf-8",
    )
    (output / "src/bin/vvmpeg.rs").write_text(
        "use std::io::Write;\n\n"
        "const LEGACY_BANNER: &str = concat!(\"vaco version \", env!(\"CARGO_PKG_VERSION\"), \" Copyright (c) 2026 the Vaco authors\");\n"
        "const INSTALLED_BANNER: &str = concat!(\"vvmpeg version \", env!(\"CARGO_PKG_VERSION\"), \" Copyright (c) 2026 the Vaco authors\");\n"
        "const LEGACY_VERSION: &str = concat!(\"vaco version \", env!(\"CARGO_PKG_VERSION\"));\n"
        "const INSTALLED_VERSION: &str = concat!(\"vvmpeg version \", env!(\"CARGO_PKG_VERSION\"));\n"
        "const LEGACY_LICENSE: &str = \"vaco is licensed under GPL-3.0-or-later.\";\n"
        "const INSTALLED_LICENSE: &str = \"vvmpeg is licensed under GPL-3.0-or-later.\";\n"
        "const LEGACY_USAGE: &str = \"usage: vaco [options] -i <input> ... [options] <output> ...\";\n"
        "const INSTALLED_USAGE: &str = \"usage: vvmpeg [options] -i <input> ... [options] <output> ...\";\n\n"
        "fn branding() -> [(&'static [u8], &'static [u8]); 4] {\n"
        "    [(LEGACY_BANNER.as_bytes(), INSTALLED_BANNER.as_bytes()), (LEGACY_VERSION.as_bytes(), INSTALLED_VERSION.as_bytes()), (LEGACY_LICENSE.as_bytes(), INSTALLED_LICENSE.as_bytes()), (LEGACY_USAGE.as_bytes(), INSTALLED_USAGE.as_bytes())]\n}\n\n"
        "fn main() {\n"
        "    let argv: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();\n"
        "    let mut out = Vec::new();\n    let mut err = Vec::new();\n"
        "    let code = vaco::cli::run(&argv, &mut out, &mut err);\n"
        "    let stdout = std::io::stdout();\n    let stderr = std::io::stderr();\n"
        "    let mut stdout = std::io::BufWriter::new(stdout.lock());\n    let mut stderr = stderr.lock();\n"
        "    let branding = branding();\n"
        "    let _ = stdout.write_all(&vaco::command::rebrand_static_lines(&out, &branding));\n"
        "    let _ = stderr.write_all(&vaco::command::rebrand_static_lines(&err, &branding));\n"
        "    let _ = stdout.flush();\n    std::process::exit(code.code());\n}\n",
        encoding="utf-8",
    )
    (output / "src/bin/vvprobe.rs").write_text(
        "use std::io::Write as _;\nuse std::process::ExitCode;\n\n"
        "const LEGACY_BANNER: &str = concat!(\"vaco-probe version \", env!(\"CARGO_PKG_VERSION\"), \" Copyright (c) 2026 the Vaco authors\");\n"
        "const INSTALLED_BANNER: &str = concat!(\"vvprobe version \", env!(\"CARGO_PKG_VERSION\"), \" Copyright (c) 2026 the Vaco authors\");\n"
        "const LEGACY_VERSION: &str = concat!(\"vaco-probe version \", env!(\"CARGO_PKG_VERSION\"));\n"
        "const INSTALLED_VERSION: &str = concat!(\"vvprobe version \", env!(\"CARGO_PKG_VERSION\"));\n"
        "const LEGACY_LICENSE: &str = \"vaco-probe is licensed under GPL-3.0-or-later.\";\n"
        "const INSTALLED_LICENSE: &str = \"vvprobe is licensed under GPL-3.0-or-later.\";\n"
        "const LEGACY_USAGE: &str = \"usage: vaco-probe [OPTIONS] INPUT_FILE\";\n"
        "const INSTALLED_USAGE: &str = \"usage: vvprobe [OPTIONS] INPUT_FILE\";\n\n"
        "fn branding() -> [(&'static [u8], &'static [u8]); 4] {\n"
        "    [(LEGACY_BANNER.as_bytes(), INSTALLED_BANNER.as_bytes()), (LEGACY_VERSION.as_bytes(), INSTALLED_VERSION.as_bytes()), (LEGACY_LICENSE.as_bytes(), INSTALLED_LICENSE.as_bytes()), (LEGACY_USAGE.as_bytes(), INSTALLED_USAGE.as_bytes())]\n}\n\n"
        "fn main() -> ExitCode {\n"
        "    let argv: Vec<std::ffi::OsString> = std::env::args_os().skip(1).collect();\n"
        "    let mut out = Vec::new();\n    let mut err = Vec::new();\n"
        "    let exit = vaco::probe::run(&argv, &mut out, &mut err);\n"
        "    let stdout = std::io::stdout();\n    let stderr = std::io::stderr();\n"
        "    let mut stdout = std::io::BufWriter::new(stdout.lock());\n    let mut stderr = stderr.lock();\n"
        "    let branding = branding();\n"
        "    if let Err(error) = stdout.write_all(&vaco::command::rebrand_static_lines(&out, &branding))\n"
        "        && error.kind() != std::io::ErrorKind::BrokenPipe\n"
        "    {\n"
        "        let _ = writeln!(stderr, \"{error}\");\n"
        "        return ExitCode::FAILURE;\n"
        "    }\n"
        "    let _ = stderr.write_all(&vaco::command::rebrand_static_lines(&err, &branding));\n"
        "    if let Err(error) = stdout.flush()\n"
        "        && error.kind() != std::io::ErrorKind::BrokenPipe\n"
        "    {\n"
        "        let _ = writeln!(stderr, \"{error}\");\n"
        "        return ExitCode::FAILURE;\n"
        "    }\n"
        "    match exit {\n"
        "        vaco::probe::Exit::Ok => ExitCode::SUCCESS,\n"
        "        vaco::probe::Exit::Failure => ExitCode::FAILURE,\n"
        "    }\n}\n",
        encoding="utf-8",
    )
    subprocess.run(
        [
            "rustfmt",
            "--edition",
            "2024",
            output / "src/lib.rs",
            output / "src/bin/vvmpeg.rs",
            output / "src/bin/vvprobe.rs",
            output / "tests/command_branding.rs",
        ],
        check=True,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
