#!/usr/bin/env bash
# Reproducible-build verification (QA-10, #182).
#
# Builds the release binaries for a fixed package set TWICE, from two
# separate target directories so neither build can incrementally reuse the
# other's objects, and compares the resulting binaries byte-for-byte.
#
# A check that has never caught a difference is not known to work (see
# AGENT-CONSTRAINTS.md's reasoning for vaco-checkasm), so this script does
# not silently accept a match: it prints what it compared and how, and on a
# mismatch it runs a short diagnostic pass (embedded paths, Mach-O/ELF
# load-command differences, `strings` diff) rather than just failing.
#
# Usage: scripts/verify-reproducible-build.sh [package ...]
#   Defaults to vaco-cli and vaco-probe (the two shipped binaries).
set -uo pipefail

cd "$(git rev-parse --show-toplevel)" || exit 1

PACKAGES=("$@")
if [ ${#PACKAGES[@]} -eq 0 ]; then
    PACKAGES=(vaco-cli vaco-probe)
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/vaco-repro.XXXXXX")"
A="$WORK/build-a"
B="$WORK/build-b"
trap 'echo "(scratch kept at $WORK for inspection)"' EXIT

# SOURCE_DATE_EPOCH pins any timestamp a proc-macro or dependency might
# embed (https://reproducible-builds.org/docs/source-date-epoch/, honoured
# directly by cargo-cyclonedx and several crates). Fixed rather than
# `$(date +%s)` so a re-run of this script is comparing the same target,
# not moving it every time.
export SOURCE_DATE_EPOCH=1735689600 # 2025-01-01T00:00:00Z, arbitrary and fixed

build() {
    local target_dir="$1"
    # --target-dir, never CARGO_TARGET_DIR (see Justfile's own header):
    # sccache hashes CARGO_* env vars into its cache key, which would make
    # the two builds below share a cache entry and prove nothing.
    cargo build --release --locked --target-dir "$target_dir" \
        $(printf -- '-p %s ' "${PACKAGES[@]}")
}

echo "== build A: $A =="
build "$A" || { echo "build A failed"; exit 1; }
echo "== build B: $B =="
build "$B" || { echo "build B failed"; exit 1; }

HOST_TRIPLE="$(rustc -vV | sed -n 's/^host: //p')"

fail=0
for pkg in "${PACKAGES[@]}"; do
    # Binary name may differ from package name (vaco-cli -> vaco).
    bin="$pkg"
    [ "$pkg" = "vaco-cli" ] && bin="vaco"
    pa="$A/release/$bin"
    pb="$B/release/$bin"
    if [ ! -f "$pa" ] || [ ! -f "$pb" ]; then
        echo "$pkg: binary not found at $pa or $pb (checked target triple: $HOST_TRIPLE)"
        fail=1
        continue
    fi
    ha=$(shasum -a 256 "$pa" | cut -d' ' -f1)
    hb=$(shasum -a 256 "$pb" | cut -d' ' -f1)
    sa=$(stat -f%z "$pa" 2>/dev/null || stat -c%s "$pa")
    sb=$(stat -f%z "$pb" 2>/dev/null || stat -c%s "$pb")
    if [ "$ha" = "$hb" ]; then
        echo "$pkg: IDENTICAL  sha256=$ha  size=$sa"
        continue
    fi

    fail=1
    echo "$pkg: DIFFERS  sizes: A=$sa B=$sb  sha256: A=$ha B=$hb"
    echo "  -- diagnosing --"

    # 1. Embedded absolute paths that could vary between checkouts (not
    #    between these two builds, which share a checkout, but worth
    #    recording since a release runner's checkout path WILL vary run to
    #    run unless pinned).
    if command -v strings >/dev/null; then
        pa_paths="$WORK/$pkg.a.paths"
        pb_paths="$WORK/$pkg.b.paths"
        strings -a "$pa" | grep -E '/(Users|home|builds?|runner)/' | sort -u > "$pa_paths"
        strings -a "$pb" | grep -E '/(Users|home|builds?|runner)/' | sort -u > "$pb_paths"
        if ! diff -q "$pa_paths" "$pb_paths" >/dev/null; then
            echo "  embedded-path strings differ (see $pa_paths / $pb_paths):"
            diff "$pa_paths" "$pb_paths" | head -20
        else
            echo "  embedded-path strings: identical set ($(wc -l < "$pa_paths" | tr -d ' ') paths) -- not the cause"
        fi
    fi

    # 2. Mach-O load commands (macOS): LC_UUID is regenerated by the linker
    #    on every link by default and is the most common source of a
    #    byte-for-byte mismatch between two otherwise-identical builds.
    if command -v otool >/dev/null && file "$pa" 2>/dev/null | grep -qi "mach-o"; then
        ua=$(otool -l "$pa" | awk '/LC_UUID/{getline; print $2}')
        ub=$(otool -l "$pb" | awk '/LC_UUID/{getline; print $2}')
        echo "  Mach-O LC_UUID: A=$ua B=$ub $([ "$ua" != "$ub" ] && echo '<-- differs')"
    fi

    # 3. ELF build-id (Linux), same idea as LC_UUID above.
    if command -v readelf >/dev/null && file "$pa" 2>/dev/null | grep -qi "elf"; then
        ia=$(readelf -n "$pa" 2>/dev/null | awk '/Build ID/{print $NF}')
        ib=$(readelf -n "$pb" 2>/dev/null | awk '/Build ID/{print $NF}')
        echo "  ELF Build ID: A=$ia B=$ib $([ "$ia" != "$ib" ] && echo '<-- differs')"
    fi

    echo "  full binaries kept at $pa and $pb for further inspection (e.g. cmp -l, objdump -d)"
done

if [ "$fail" -eq 0 ]; then
    echo "all ${#PACKAGES[@]} package(s) reproduced bit-for-bit"
else
    echo "reproducibility check found a difference -- see diagnostics above"
fi
exit $fail
