//! The codec framework: what a decoder, encoder, parser and bitstream filter are.
//!
//! Per D14.1 this crate sits *below* `vaco-format-core`, because demuxers need
//! codec parameters and bitstream parsers. Nothing here knows about any specific
//! codec — concrete codecs are leaf crates that implement these traits.
//!
//! # What is in here
//!
//! | Module | Contents |
//! |---|---|
//! | [`machine`] | [`Machine`], the send/receive state machine every component shares |
//! | [`protocol`] | [`SendReceive`], the adapters onto the three trait faces, and [`Validated`] |
//! | [`parser`] | [`ParserDesc`] and [`ParserDriver`]: how a parser is registered, and the harness that drives it |
//! | [`caps`] | [`Caps`] — what an implementation can do, checked before it is built |
//! | [`params`] | [`CodecParameters`], profiles, levels and their tables |
//! | [`picture`] | frame-threading primitives: guard-padded row bands published through `OnceLock` |
//! | [`threading`] | the three threading axes, and the split-decoder frame-threading traits |
//! | [`mock`] | a reference codec that exercises every corner of the protocol |
//!
//! # The one idea worth reading first
//!
//! Packet-to-frame is genuinely N:M. One packet can yield several frames, several
//! packets can yield none while a reorder buffer fills, and draining at end of
//! stream can yield many. That is why the API is send/receive rather than
//! `decode(packet) -> Frame`, and why [`Machine`] exists: the rules are the same
//! for decoders, encoders and bitstream filters, so they are written down once,
//! executed once, and — through [`Validated`] — *enforced* once.

#![forbid(unsafe_code)]

use vaco_core::{MediaType, Rational, Result};
use vaco_frame::Frame;
use vaco_limits::Limits;
use vaco_packet::Packet;

pub mod caps;
pub mod machine;
pub mod mock;
pub mod params;
pub mod parser;
pub mod picture;
pub mod protocol;
pub mod threading;

pub use caps::{Caps, CodecProperties};
pub use machine::{Accept, Machine, Stage};
pub use params::{
    AudioParameters, CodecParameters, FieldOrder, Level, LevelConstraints, LevelEntry, LevelQuery,
    LevelTable, Profile, ProfileEntry, ProfileTable, VideoParameters,
};
pub use parser::{ParserDesc, ParserDriver};
pub use picture::{
    BandMut, BandRangeMut, BlockRef, BlockScratch, PictureRef, PictureSpec, PictureWriter,
    PlaneSpec, PlaneView, ProgressPicture,
};
pub use protocol::{
    AsBitstreamFilter, AsDecoder, AsEncoder, DecoderProtocol, OnViolation, SendReceive, Validated,
    Violation, validate_decoder,
};
pub use threading::{
    CancelToken, FrameTask, FrameThreadedDecoder, SliceThreadedDecoder, SplitOutcome, TaskCtx,
    Threading,
};

/// Identifies a codec independently of who implements it.
///
/// Every variant is a unit variant, deliberately: at least one call site
/// (`vaco-bsf-generic`'s noise generator) casts a `CodecId` `as u64` for a
/// hash seed, and Rust only allows that cast when *every* variant of the enum
/// is fieldless. A payload-carrying escape hatch (`CodecId::Ext(&'static
/// ExtCodec)`, so a leaf crate could mint its own identity without a variant
/// here) was drafted and rejected for exactly this reason.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[non_exhaustive]
pub enum CodecId {
    H264,
    Hevc,
    Av1,
    Vp8,
    Vp9,
    Aac,
    /// AAC in the LATM/LOAS syntax, which the reference treats as a separate
    /// codec rather than a framing of `Aac`: `ffmpeg -codecs` lists both, and
    /// ffprobe prints `codec_name=aac_latm`. Reproducing that spelling is why
    /// this is a variant and not a flag on `Aac`.
    AacLatm,
    Opus,
    Flac,
    Vorbis,
    Mp3,
    Pcm,
    Png,
    Jpeg,
    /// `SubRip` (`.srt`), the text subtitle format Matroska carries as
    /// `S_TEXT/UTF8`. `ffprobe` prints `codec_name=subrip`.
    SubRip,
    /// MPEG-4 timed text, the *same* subtitles inside MP4. A separate codec in
    /// the reference rather than a framing — `ffprobe` prints
    /// `codec_name=mov_text` for a track transcoded from the identical
    /// `SubRip`
    /// source, so the two spellings are an interface fact (D9), not a choice.
    MovText,

    // ---------------------------------------------------------------- bulk
    //
    // Names, long names, media type and the lossy/lossless/intra properties for
    // all of these were **generated by probing** `ffmpeg -codecs` under
    // `LC_ALL=C`, not transcribed. Two things only showed up by doing it that
    // way:
    //
    // - The listing appends `(decoders: …)` / `(encoders: …)` to a long name
    //   when the codec has differently-named implementations, and that suffix
    //   is *not* part of `codec_long_name`. `subrip` proves it: the listing
    //   says "SubRip subtitle (decoders: srt subrip)" while `ffprobe` prints
    //   "SubRip subtitle" — which we already had measured from a real file, so
    //   the two sources could be checked against each other.
    // - DTS's codec is spelled `dts` with the long name "DCA (DTS Coherent
    //   Acoustics)", while its *decoder* is `dca`. Asking `-h decoder=` gives
    //   the wrong string for this field.
    PcmS16le,
    PcmS16be,
    PcmS24le,
    PcmS24be,
    PcmS32le,
    PcmS32be,
    PcmU8,
    /// Unsigned PCM above one byte, which only the raw `-f u16le`-family
    /// muxers name. Added 2026-08-23: every one of them reported
    /// `Default audio codec: pcm.` — a codec the reference does not have —
    /// because these six variants did not exist.
    /// `pcm_vidc`, the Archimedes VIDC logarithmic PCM the `vidc` muxer
    /// defaults to. Measured from `ffmpeg -codecs`: `DEAIL. pcm_vidc  PCM
    /// Archimedes VIDC`.
    PcmVidc,
    /// `wrapped_avframe`. Not a codec in any real sense — it is the
    /// reference's passthrough pseudo-codec, and it is here only because
    /// `-h muxer=null` and `-h muxer=yuv4mpegpipe` both name it as their
    /// default video codec and there is no other way to say so.
    WrappedAvframe,
    PcmU16le,
    PcmU16be,
    PcmU24le,
    PcmU24be,
    PcmU32le,
    PcmU32be,
    PcmS8,
    PcmF32le,
    PcmF32be,
    PcmF64le,
    PcmF64be,
    PcmAlaw,
    PcmMulaw,
    Rawvideo,
    Vc1,
    Mpeg4,
    Mpeg1video,
    Mpeg2video,
    Msmpeg4v3,
    H261,
    H263,
    Vvc,
    Evc,
    Cavs,
    Dirac,
    Dnxhd,
    Prores,
    Huffyuv,
    Ffv1,
    Gif,
    Bmp,
    Tiff,
    Webp,
    Ac3,
    Eac3,
    Dts,
    Truehd,
    Mp1,
    Mp2,
    Alac,
    Wmav1,
    Wmav2,
    Wmapro,
    Speex,
    Theora,
    AmrNb,
    AmrWb,
    AdpcmImaWav,
    AdpcmMs,
    Ass,
    Ssa,
    Webvtt,
    DvdSubtitle,
    HdmvPgsSubtitle,
    Eia608,
    // The text-subtitle family. Added when `vaco-subtitle-text` landed
    // seventeen demuxers and reported — correctly, rather than working around
    // it — that it could not name any of them: only this crate may add a
    // variant, and a demuxer that sets `codec_id: None` makes `vaco-probe`
    // print `codec_name=unknown` where the reference prints a real name.
    //
    // Names and long names probed from `ffmpeg -codecs`, 8.1. Note what is
    // *not* here: LRC and MPsub, which the reference reports as the generic
    // `text` rather than as formats of their own — so they take `Text`.
    Jacosub,
    Microdvd,
    Mpl2,
    Pjs,
    Realtext,
    Sami,
    Stl,
    Subviewer,
    Subviewer1,
    Text,
    Ttml,
    Vplayer,
    // The MPEG-TS repertoire. `vaco-format-mpegts-tables` carried its own
    // `TsCodec` enum for these and mapped only eight of about thirty across,
    // so a real `mpeg2video` stream printed `codec_name=unknown` — the largest
    // single divergence class the differential harness found. Names and long
    // names probed from `ffmpeg -codecs` 8.1.
    //
    // Four of them are `Data`, which is a media type this table had no entry
    // for until now: SCTE-35 splice messages, timed ID3, and SMPTE 336M KLV are
    // carried by a transport stream as their own elementary streams, and
    // collapsing them onto "unknown" would discard the one fact the PMT stated.
    Avs2,
    Avs3,
    Jpeg2000,
    DvbSubtitle,
    DvbTeletext,
    Scte35,
    TimedId3,
    Klv,
    // The Flash repertoire. `vaco-demux-flv`'s legacy codec table mapped two of
    // about ten ids, so a Sorenson Spark stream — what `-c:v flv1` produces and
    // therefore the most ordinary FLV there is — printed `codec_name=unknown`.
    // Names and long names probed from `ffmpeg -codecs` 8.1.
    Flv1,
    Flashsv,
    Flashsv2,
    Vp6,
    Vp6a,
    Vp6f,
    Nellymoser,
    AdpcmSwf,
    // The RTP static and dynamic payload repertoire (RFC 3551 and the
    // per-codec RFCs). `vaco-format-rtp` mapped 24 payload types onto 22
    // codecs and could name only some of them, so the rest reported as
    // `unknown`. Names and long names probed from `ffmpeg -codecs` 8.1.
    Gsm,
    GsmMs,
    AdpcmG722,
    AdpcmG726,
    G7231,
    G729,
    Qcelp,
    Ilbc,
    Dvvideo,
    Cljr,
    G728,

    // ------------------------------------------------- leaf image codecs
    //
    // QOI, the PNM family, and the simple-image repertoire (PCX/TGA/SGI/
    // XWD/XBM — BMP already had a variant). Landed the same day as their
    // decode/encode implementations, which had nowhere to register without
    // these: `vaco_registry::decoder_for`/`encoder_for` match on `CodecId`,
    // so a codec cannot be found by codec identity without one. Names and
    // long names probed from `ffmpeg -codecs`, 8.1. A `CodecId::Ext(&'static
    // ExtCodec)` escape hatch was drafted instead of hand-adding these, so
    // that a future codec crate would not need this file touched at all —
    // rejected because at least one existing call site
    // (`vaco-bsf-generic`'s noise generator) casts `CodecId as u64`, which
    // Rust only permits when every variant is fieldless.
    Qoi,
    Pbm,
    Pgm,
    Ppm,
    Pam,
    Pfm,
    Phm,
    Pcx,
    Targa,
    Sgi,
    Xwd,
    Xbm,

    // The legacy-lossless and simple-lossy repertoire `vaco-format-misc-audio`
    // needs to name a stream's codec at all: WavPack and TTA are whole-file
    // lossless containers with their own codec identity, and DFPWM/aptX/aptX
    // HD/CRI's ADX ADPCM have no existing variant either. Names and long
    // names probed from `ffmpeg -codecs`, 8.1.
    WavPack,
    Tta,
    Dfpwm,
    Aptx,
    AptxHd,
    Sbc,
    AdpcmAdx,

    // The game-video/game-audio repertoire `vaco-format-misc`'s `roq`,
    // `flic`, `cdg`, `bink` and `smk` demuxers need to name a stream's codec
    // at all (gap 21, `planning/INTERFACE-GAPS.md`): every one of them
    // carried `codec_id: None`, so `-show_streams` printed
    // `codec_name=unknown` where the reference names a real codec. Names,
    // long names and properties probed from `ffmpeg -codecs`/`-decoders`,
    // 8.1, and for `Roq`/`RoqDpcm` cross-checked against a real file
    // (`ffmpeg -f lavfi ... -c:v roqvideo -c:a roq_dpcm -f roq`) round-tripped
    // through `ffprobe`. `BinkAudioDct`/`BinkAudioRdft` are two variants, not
    // one: the reference reports them as two entirely distinct
    // `codec_name`s with no shared alias, so one `CodecId` could not print
    // the right name for both, unlike `AacLatm`'s reason for being separate
    // from `Aac` in the first place.
    Roq,
    RoqDpcm,
    Flic,
    Cdgraphics,
    Bink,
    BinkAudioDct,
    BinkAudioRdft,
    Smacker,
    SmackAudio,

    // ------------------------------------------- C-01/C-02/C-03 (#279-#281)
    //
    // The remainder of the standardised ADPCM subset and the raw/uncompressed
    // video family those issues need a `CodecId` for. `AdpcmG726` already
    // existed but `adpcm_g726le` is a *distinct* codec in the reference (its
    // own `-decoders`/`-encoders` row, "G.726 ADPCM little-endian (codec
    // adpcm_g726le)" — a different bit-packing of the same state machine, not
    // an alias), and `adpcm_ima_qt` had no variant at all. Names and long
    // names probed from `ffmpeg -codecs`/`-decoders`/`-encoders`, 8.1.
    AdpcmG726le,
    AdpcmImaQt,
    /// `v210`. `AV_CODEC_ID_V210` in the reference; SMPTE 292M/424M 10-bit
    /// 4:2:2 packing.
    V210,
    /// `v210x`, the decode-only sibling `vaco-demux-raw` already frames.
    V210x,
    /// `r10k`, AJA Kona's 10-bit RGB packing.
    R10k,
    /// `r210`, uncompressed 10-bit RGB.
    R210,
    /// `y41p`, uncompressed 4:1:1 12-bit YUV.
    Y41p,
    /// `avui`, Avid Meridien's uncompressed packing.
    Avui,
    /// `bitpacked`, `QuickTime`'s generic bit-packed raw family.
    Bitpacked,
    /// `vnull`, the reference's dummy video encoder — produces no packets,
    /// exists so `-c:v vnull` and `-an`-style discard pipelines resolve to a
    /// real codec identity instead of failing to find one.
    Vnull,
    /// `anull`, `vnull`'s audio counterpart.
    Anull,

    // ------------------------------------------- C-11/C-12 (#289/#290)
    //
    // OpenEXR and JPEG XL each need a `CodecId` of their own: neither had a
    // variant, unlike PNG/GIF/TIFF/WebP which already did. Names and long
    // names measured from `ffmpeg -codecs`, 8.1: `exr`/"OpenEXR image" and
    // `jpegxl`/"JPEG XL". `jpegxl_anim` (the reference's separate animated
    // variant) is not modelled as its own `CodecId` — same rationale as
    // `Png` covering APNG — because `vaco-codec-jpegxl` is decode-only via
    // `jxl-oxide` and animation is a frame-count property of one decode, not
    // a distinct bitstream identity the way `AacLatm` is.
    Exr,
    JpegXl,
    /// `jpegls`, ITU-T T.87 / ISO/IEC 14495-1. Neither had a variant, same
    /// gap as C-11/C-12 above. Name/long name measured from `ffmpeg
    /// -codecs`, 8.1: `jpegls`/"JPEG-LS".
    JpegLs,
    /// Dominic Szablewski's Quite OK Audio, a sign-sign LMS predictor coded
    /// in fixed 20-sample/8-byte slices with the LMS state re-transmitted at
    /// every frame header, so any frame is an independent seek point.
    /// `Dfpwm`/`Sbc` already exist above (added for
    /// `vaco-format-misc-audio`'s stream identification) and are reused
    /// as-is here, not redefined. Name/long name measured from `ffmpeg
    /// -codecs`, 8.1: `qoa`/"QOA (Quite OK Audio)".
    Qoa,
    /// RFC 3389 RTP comfort noise: a Silence Insertion Descriptor (noise
    /// level plus optional LPC reflection coefficients) driving an
    /// unspecified-by-the-RFC noise synthesiser. Name/long name measured
    /// from `ffmpeg -codecs`, 8.1: `comfortnoise`/"RFC 3389 Comfort Noise".
    ComfortNoise,
}

/// One row of the codec identity table.
///
/// Hand-written for now; plan 15 §1.1 has this generated from `codecs.toml`, the
/// same technique `vaco-pixfmt` uses, so that name, long name, media type and
/// properties cannot drift from the enum. The shape here is what that generator
/// must emit.
struct CodecEntry {
    id: CodecId,
    /// CLI-stable short name. An interface fact, not an implementation detail.
    name: &'static str,
    long_name: &'static str,
    media_type: MediaType,
    properties: CodecProperties,
}

const fn entry(
    id: CodecId,
    name: &'static str,
    long_name: &'static str,
    media_type: MediaType,
    properties: CodecProperties,
) -> CodecEntry {
    CodecEntry {
        id,
        name,
        long_name,
        media_type,
        properties,
    }
}

const V: MediaType = MediaType::Video;
const A: MediaType = MediaType::Audio;
const S: MediaType = MediaType::Subtitle;
const D: MediaType = MediaType::Data;
/// Every leaf image codec added alongside `EncoderDesc`: a whole-image
/// format, lossless, every frame a seek point.
const IMG: CodecProperties = CodecProperties::INTRA_ONLY.union(CodecProperties::LOSSLESS);

const CODECS: &[CodecEntry] = &[
    entry(
        CodecId::H264,
        "h264",
        "H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10",
        V,
        CodecProperties::LOSSY
            .union(CodecProperties::REORDER)
            .union(CodecProperties::FIELDS),
    ),
    entry(
        CodecId::Hevc,
        "hevc",
        "H.265 / HEVC (High Efficiency Video Coding)",
        V,
        CodecProperties::LOSSY
            .union(CodecProperties::REORDER)
            .union(CodecProperties::FIELDS),
    ),
    entry(
        CodecId::Av1,
        "av1",
        "Alliance for Open Media AV1",
        V,
        CodecProperties::LOSSY.union(CodecProperties::REORDER),
    ),
    entry(CodecId::Vp8, "vp8", "On2 VP8", V, CodecProperties::LOSSY),
    entry(
        CodecId::Vp9,
        "vp9",
        "Google VP9",
        V,
        CodecProperties::LOSSY.union(CodecProperties::REORDER),
    ),
    entry(
        CodecId::Aac,
        "aac",
        "AAC (Advanced Audio Coding)",
        A,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::AacLatm,
        "aac_latm",
        "AAC LATM (Advanced Audio Coding LATM syntax)",
        A,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Opus,
        "opus",
        "Opus (Opus Interactive Audio Codec)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Flac,
        "flac",
        "FLAC (Free Lossless Audio Codec)",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Vorbis,
        "vorbis",
        "Vorbis",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Mp3,
        "mp3",
        "MP3 (MPEG audio layer 3)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Pcm,
        "pcm",
        "PCM (uncompressed)",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Png,
        "png",
        "PNG (Portable Network Graphics) image",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Jpeg,
        "mjpeg",
        "Motion JPEG",
        V,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    // Both names measured from `ffprobe -show_entries stream=codec_name,
    // codec_long_name` on the same subtitle content muxed two ways.
    entry(
        CodecId::SubRip,
        "subrip",
        "SubRip subtitle",
        S,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::MovText,
        "mov_text",
        "MOV text",
        S,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS16le,
        "pcm_s16le",
        "PCM signed 16-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS16be,
        "pcm_s16be",
        "PCM signed 16-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS24le,
        "pcm_s24le",
        "PCM signed 24-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS24be,
        "pcm_s24be",
        "PCM signed 24-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS32le,
        "pcm_s32le",
        "PCM signed 32-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS32be,
        "pcm_s32be",
        "PCM signed 32-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU8,
        "pcm_u8",
        "PCM unsigned 8-bit",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmVidc,
        "pcm_vidc",
        "PCM Archimedes VIDC",
        A,
        CodecProperties::INTRA_ONLY.union(CodecProperties::LOSSY),
    ),
    entry(
        CodecId::WrappedAvframe,
        "wrapped_avframe",
        "AVFrame to AVPacket passthrough",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU16le,
        "pcm_u16le",
        "PCM unsigned 16-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU16be,
        "pcm_u16be",
        "PCM unsigned 16-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU24le,
        "pcm_u24le",
        "PCM unsigned 24-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU24be,
        "pcm_u24be",
        "PCM unsigned 24-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU32le,
        "pcm_u32le",
        "PCM unsigned 32-bit little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmU32be,
        "pcm_u32be",
        "PCM unsigned 32-bit big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmS8,
        "pcm_s8",
        "PCM signed 8-bit",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmF32le,
        "pcm_f32le",
        "PCM 32-bit floating point little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmF32be,
        "pcm_f32be",
        "PCM 32-bit floating point big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmF64le,
        "pcm_f64le",
        "PCM 64-bit floating point little-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmF64be,
        "pcm_f64be",
        "PCM 64-bit floating point big-endian",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmAlaw,
        "pcm_alaw",
        "PCM A-law / G.711 A-law",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::PcmMulaw,
        "pcm_mulaw",
        "PCM mu-law / G.711 mu-law",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Rawvideo,
        "rawvideo",
        "raw video",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(CodecId::Vc1, "vc1", "SMPTE VC-1", V, CodecProperties::LOSSY),
    entry(
        CodecId::Mpeg4,
        "mpeg4",
        "MPEG-4 part 2",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Mpeg1video,
        "mpeg1video",
        "MPEG-1 video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Mpeg2video,
        "mpeg2video",
        "MPEG-2 video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Msmpeg4v3,
        "msmpeg4v3",
        "MPEG-4 part 2 Microsoft variant version 3",
        V,
        CodecProperties::LOSSY,
    ),
    entry(CodecId::H261, "h261", "H.261", V, CodecProperties::LOSSY),
    entry(
        CodecId::H263,
        "h263",
        "H.263 / H.263-1996, H.263+ / H.263-1998 / H.263 version 2",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Vvc,
        "vvc",
        "H.266 / VVC (Versatile Video Coding)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Evc,
        "evc",
        "MPEG-5 EVC (Essential Video Coding)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Cavs,
        "cavs",
        "Chinese AVS (Audio Video Standard) (AVS1-P2, JiZhun profile)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Dirac,
        "dirac",
        "Dirac",
        V,
        CodecProperties::LOSSY.union(CodecProperties::LOSSLESS),
    ),
    entry(
        CodecId::Dnxhd,
        "dnxhd",
        "VC3/DNxHD",
        V,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Prores,
        "prores",
        "Apple ProRes (iCodec Pro)",
        V,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Huffyuv,
        "huffyuv",
        "HuffYUV",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Ffv1,
        "ffv1",
        "FFmpeg video codec #1",
        V,
        CodecProperties::LOSSLESS,
    ),
    entry(
        CodecId::Gif,
        "gif",
        "CompuServe GIF (Graphics Interchange Format)",
        V,
        CodecProperties::LOSSLESS,
    ),
    entry(
        CodecId::Bmp,
        "bmp",
        "BMP (Windows and OS/2 bitmap)",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Tiff,
        "tiff",
        "TIFF image",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Webp,
        "webp",
        "WebP",
        V,
        CodecProperties::LOSSY.union(CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY)),
    ),
    entry(
        CodecId::Ac3,
        "ac3",
        "ATSC A/52A (AC-3)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Eac3,
        "eac3",
        "ATSC A/52B (AC-3, E-AC-3)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Dts,
        "dts",
        "DCA (DTS Coherent Acoustics)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY)),
    ),
    entry(
        CodecId::Truehd,
        "truehd",
        "TrueHD",
        A,
        CodecProperties::LOSSLESS,
    ),
    entry(
        CodecId::Mp1,
        "mp1",
        "MP1 (MPEG audio layer 1)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Mp2,
        "mp2",
        "MP2 (MPEG audio layer 2)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Alac,
        "alac",
        "ALAC (Apple Lossless Audio Codec)",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Wmav1,
        "wmav1",
        "Windows Media Audio 1",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Wmav2,
        "wmav2",
        "Windows Media Audio 2",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Wmapro,
        "wmapro",
        "Windows Media Audio 9 Professional",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Speex,
        "speex",
        "Speex",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Theora,
        "theora",
        "Theora",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::AmrNb,
        "amr_nb",
        "AMR-NB (Adaptive Multi-Rate NarrowBand)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AmrWb,
        "amr_wb",
        "AMR-WB (Adaptive Multi-Rate WideBand)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmImaWav,
        "adpcm_ima_wav",
        "ADPCM IMA WAV",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmMs,
        "adpcm_ms",
        "ADPCM Microsoft",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Ass,
        "ass",
        "ASS (Advanced SSA) subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Ssa,
        "ssa",
        "SSA (SubStation Alpha) subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Webvtt,
        "webvtt",
        "WebVTT subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::DvdSubtitle,
        "dvd_subtitle",
        "DVD subtitles",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::HdmvPgsSubtitle,
        "hdmv_pgs_subtitle",
        "HDMV Presentation Graphic Stream subtitles",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Jacosub,
        "jacosub",
        "JACOsub subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Microdvd,
        "microdvd",
        "MicroDVD subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Mpl2,
        "mpl2",
        "MPL2 subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Pjs,
        "pjs",
        "PJS (Phoenix Japanimation Society) subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Realtext,
        "realtext",
        "RealText subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Sami,
        "sami",
        "SAMI subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Stl,
        "stl",
        "Spruce subtitle format",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Subviewer,
        "subviewer",
        "SubViewer subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Subviewer1,
        "subviewer1",
        "SubViewer v1 subtitle",
        S,
        CodecProperties::empty(),
    ),
    // `text` is the reference's catch-all for a subtitle stream whose format
    // has no codec of its own — LRC and MPsub both measure as this.
    entry(
        CodecId::Text,
        "text",
        "raw UTF-8 text",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Ttml,
        "ttml",
        "Timed Text Markup Language",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Vplayer,
        "vplayer",
        "VPlayer subtitle",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Avs2,
        "avs2",
        "AVS2-P2/IEEE1857.4",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Avs3,
        "avs3",
        "AVS3-P2/IEEE1857.10",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Jpeg2000,
        "jpeg2000",
        "JPEG 2000",
        V,
        CodecProperties::INTRA_ONLY
            .union(CodecProperties::LOSSY)
            .union(CodecProperties::LOSSLESS),
    ),
    entry(
        CodecId::DvbSubtitle,
        "dvb_subtitle",
        "DVB subtitles",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::DvbTeletext,
        "dvb_teletext",
        "DVB teletext",
        S,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Scte35,
        "scte_35",
        "SCTE 35 Message Queue",
        D,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::TimedId3,
        "timed_id3",
        "timed ID3 metadata",
        D,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Klv,
        "klv",
        "SMPTE 336M Key-Length-Value (KLV) metadata",
        D,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Flv1,
        "flv1",
        "FLV / Sorenson Spark / Sorenson H.263 (Flash Video)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Flashsv,
        "flashsv",
        "Flash Screen Video v1",
        V,
        CodecProperties::LOSSLESS,
    ),
    entry(
        CodecId::Flashsv2,
        "flashsv2",
        "Flash Screen Video v2",
        V,
        CodecProperties::LOSSY,
    ),
    entry(CodecId::Vp6, "vp6", "On2 VP6", V, CodecProperties::LOSSY),
    entry(
        CodecId::Vp6a,
        "vp6a",
        "On2 VP6 (Flash version, with alpha channel)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Vp6f,
        "vp6f",
        "On2 VP6 (Flash version)",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Nellymoser,
        "nellymoser",
        "Nellymoser Asao",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmSwf,
        "adpcm_swf",
        "ADPCM Shockwave Flash",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Gsm,
        "gsm",
        "GSM",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::GsmMs,
        "gsm_ms",
        "GSM Microsoft variant",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmG722,
        "adpcm_g722",
        "G.722 ADPCM",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmG726,
        "adpcm_g726",
        "G.726 ADPCM",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::G7231,
        "g723_1",
        "G.723.1",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::G729,
        "g729",
        "G.729",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Qcelp,
        "qcelp",
        "QCELP / PureVoice",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Ilbc,
        "ilbc",
        "iLBC (Internet Low Bitrate Codec)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Dvvideo,
        "dvvideo",
        "DV (Digital Video)",
        V,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Cljr,
        "cljr",
        "Cirrus Logic AccuPak",
        V,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::G728,
        "g728",
        "G.728",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Eia608,
        "eia_608",
        "EIA-608 closed captions",
        S,
        CodecProperties::empty(),
    ),
    // The leaf image codecs: QOI, the PNM family and the simple-image
    // repertoire (PCX/TGA/SGI/XWD/XBM — BMP already had a row). All
    // lossless, intra-only whole-image formats. Names and long names
    // probed from `ffmpeg -codecs`, 8.1; TGA's reference name is `targa`,
    // not `tga`.
    entry(CodecId::Qoi, "qoi", "QOI (Quite OK Image)", V, IMG),
    entry(CodecId::Pbm, "pbm", "PBM (Portable BitMap) image", V, IMG),
    entry(CodecId::Pgm, "pgm", "PGM (Portable GrayMap) image", V, IMG),
    entry(CodecId::Ppm, "ppm", "PPM (Portable PixelMap) image", V, IMG),
    entry(CodecId::Pam, "pam", "PAM (Portable AnyMap) image", V, IMG),
    entry(CodecId::Pfm, "pfm", "PFM (Portable FloatMap) image", V, IMG),
    entry(
        CodecId::Phm,
        "phm",
        "PHM (Portable HalfFloatMap) image",
        V,
        IMG,
    ),
    entry(CodecId::Pcx, "pcx", "PC Paintbrush PCX image", V, IMG),
    entry(CodecId::Targa, "targa", "Truevision Targa image", V, IMG),
    entry(CodecId::Sgi, "sgi", "SGI image", V, IMG),
    entry(CodecId::Xwd, "xwd", "XWD (X Window Dump) image", V, IMG),
    entry(CodecId::Xbm, "xbm", "XBM (X BitMap) image", V, IMG),
    entry(
        CodecId::WavPack,
        "wavpack",
        "WavPack",
        A,
        CodecProperties::LOSSY
            .union(CodecProperties::LOSSLESS)
            .union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Tta,
        "tta",
        "TTA (True Audio)",
        A,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Dfpwm,
        "dfpwm",
        "DFPWM (Dynamic Filter Pulse Width Modulation)",
        A,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Aptx,
        "aptx",
        "aptX (Audio Processing Technology for Bluetooth)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AptxHd,
        "aptx_hd",
        "aptX HD (Audio Processing Technology for Bluetooth)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Sbc,
        "sbc",
        "SBC (low-complexity subband codec)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmAdx,
        "adpcm_adx",
        "SEGA CRI ADX ADPCM",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    // The game-video/game-audio repertoire: see the `CodecId` variants'
    // own doc comment for why `BinkAudioDct`/`BinkAudioRdft` are two rows.
    // Flags read straight off `ffmpeg -codecs`' own I/L/S columns rather
    // than guessed: `flic` is the one lossless entry here, and every audio
    // row is intra-only where none of the video rows are.
    entry(
        CodecId::Roq,
        "roq",
        "id RoQ video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::RoqDpcm,
        "roq_dpcm",
        "DPCM id RoQ",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Flic,
        "flic",
        "Autodesk Animator Flic video",
        V,
        CodecProperties::LOSSLESS,
    ),
    entry(
        CodecId::Cdgraphics,
        "cdgraphics",
        "CD Graphics video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::Bink,
        "binkvideo",
        "Bink video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::BinkAudioDct,
        "binkaudio_dct",
        "Bink Audio (DCT)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::BinkAudioRdft,
        "binkaudio_rdft",
        "Bink Audio (RDFT)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Smacker,
        "smackvideo",
        "Smacker video",
        V,
        CodecProperties::LOSSY,
    ),
    entry(
        CodecId::SmackAudio,
        "smackaudio",
        "Smacker audio",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    // ---------------------------------------------- C-01/C-02/C-03 (#279-#281)
    entry(
        CodecId::AdpcmG726le,
        "adpcm_g726le",
        "G.726 ADPCM little-endian",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::AdpcmImaQt,
        "adpcm_ima_qt",
        "ADPCM IMA QuickTime",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::V210,
        "v210",
        "Uncompressed 4:2:2 10-bit",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::V210x,
        "v210x",
        "Uncompressed 4:2:2 10-bit",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::R10k,
        "r10k",
        "AJA Kona 10-bit RGB Codec",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::R210,
        "r210",
        "Uncompressed RGB 10-bit",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Y41p,
        "y41p",
        "Uncompressed YUV 4:1:1 12-bit",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Avui,
        "avui",
        "Avid Meridien Uncompressed",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Bitpacked,
        "bitpacked",
        "Bitpacked",
        V,
        CodecProperties::LOSSLESS.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::Vnull,
        "vnull",
        "Null video codec",
        V,
        CodecProperties::empty(),
    ),
    entry(
        CodecId::Anull,
        "anull",
        "Null audio codec",
        A,
        CodecProperties::empty(),
    ),
    // Measured `ffmpeg -codecs`, 8.1 (`LC_ALL=C`): `DEVILS exr` and
    // `..VILS jpegxl` — the props column (intra/lossy/lossless) is a codec
    // property independent of which decoders/encoders a given build links,
    // unlike the D/E letters this local build shows for `jpegxl`.
    entry(
        CodecId::Exr,
        "exr",
        "OpenEXR image",
        V,
        CodecProperties::LOSSY
            .union(CodecProperties::LOSSLESS)
            .union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::JpegXl,
        "jpegxl",
        "JPEG XL",
        V,
        CodecProperties::LOSSY
            .union(CodecProperties::LOSSLESS)
            .union(CodecProperties::INTRA_ONLY),
    ),
    // Measured `ffmpeg -codecs`, 8.1: `DEVILS jpegls` — decode and encode,
    // video, intra-only, and (like Exr/JpegXl above) the format itself
    // covers both lossy (near-lossless) and lossless operation even though
    // `vaco-codec-jpegls` implements only the lossless case today.
    entry(
        CodecId::JpegLs,
        "jpegls",
        "JPEG-LS",
        V,
        CodecProperties::LOSSY
            .union(CodecProperties::LOSSLESS)
            .union(CodecProperties::INTRA_ONLY),
    ),
    // Open-spec audio codecs this batch adds: `Dfpwm`/`Sbc` already have
    // table rows above (from `vaco-format-misc-audio`'s stream
    // identification), reused as-is. Measured `ffmpeg -codecs`, 8.1:
    // `D.AIL. qoa`, `DEAIL. comfortnoise`.
    entry(
        CodecId::Qoa,
        "qoa",
        "QOA (Quite OK Audio)",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
    entry(
        CodecId::ComfortNoise,
        "comfortnoise",
        "RFC 3389 Comfort Noise",
        A,
        CodecProperties::LOSSY.union(CodecProperties::INTRA_ONLY),
    ),
];

impl CodecId {
    fn entry(self) -> Option<&'static CodecEntry> {
        CODECS.iter().find(|e| e.id == self)
    }

    /// The CLI-stable short name, e.g. `"av1"`.
    ///
    /// Names and their documented semantics are interface facts and are used
    /// freely under D7; only expression is off limits.
    #[must_use]
    pub fn name(self) -> &'static str {
        self.entry().map_or("unknown", |e| e.name)
    }

    /// The human-readable name `vaco -codecs` prints.
    #[must_use]
    pub fn long_name(self) -> &'static str {
        self.entry().map_or("unknown codec", |e| e.long_name)
    }

    /// Video, audio, subtitle or data.
    #[must_use]
    pub fn media_type(self) -> MediaType {
        self.entry().map_or(MediaType::Data, |e| e.media_type)
    }

    /// What the *format* implies, before any implementation is chosen.
    #[must_use]
    pub fn properties(self) -> CodecProperties {
        self.entry()
            .map_or(CodecProperties::empty(), |e| e.properties)
    }

    /// Resolve a CLI name. Case-insensitive, because option values are.
    #[must_use]
    pub fn from_name(name: &str) -> Option<Self> {
        CODECS
            .iter()
            .find(|e| e.name.eq_ignore_ascii_case(name))
            .map(|e| e.id)
    }

    /// Every codec this build knows about, in table order.
    pub fn all() -> impl Iterator<Item = Self> {
        CODECS.iter().map(|e| e.id)
    }

    /// How many bitstream "ticks" make up one displayed picture.
    ///
    /// A demuxer that must synthesise a packet's duration from a codec-level
    /// frame rate (there being no more reliable per-packet timing available)
    /// needs `frame_rate / ticks_per_frame`, not `frame_rate` alone — mirrors
    /// the reference's `ff_compute_frame_duration`. Reaching for the codec
    /// frame rate directly halves every such duration for a codec whose
    /// bitstream rate field is a *tick* rate rather than a picture rate.
    ///
    /// `// D17:` measured per codec, not inferred from "supports interlace" —
    /// that would have been wrong twice over. Reproduction, on real 25 fps
    /// content, comparing `r_frame_rate` (bitstream-derived) against the true
    /// encode rate:
    ///
    /// ```text
    /// ffmpeg -f lavfi -i testsrc=size=64x64:rate=25:duration=1 \
    ///        -pix_fmt yuv420p -c:v <encoder> -f mpegts t.ts
    /// ffprobe -show_entries stream=r_frame_rate,avg_frame_rate t.ts
    /// ```
    ///
    /// | encoder | `r_frame_rate` | true rate | ratio |
    /// |---|---|---|---|
    /// | `libx264` | 50/1 | 25 | **2** |
    /// | `mpeg1video` | 50/1 | 25 | **2** |
    /// | `mpeg2video` | 25/1 | 25 | 1 |
    /// | `mpeg4` | 25/1 | 25 | 1 |
    ///
    /// Repeated at 24 fps and 30 fps to rule out a coincidence of the number
    /// 25: `libx264` and `mpeg1video` scale to 48/1 and 60/1 respectively
    /// (always exactly double), `mpeg2video` and `mpeg4` track the true rate
    /// exactly. **MPEG-2 video and MPEG-4 part 2 do *not* need this** despite
    /// both being interlace-capable — the natural guess, and wrong. MPEG-1
    /// video does, despite having no interlace mode at all in its own right —
    /// the codec whose VUI-equivalent field the reference doubles is not the
    /// one this project's own `FIELDS` property flags, which is why this is
    /// a distinct concept with its own table rather than a read of
    /// [`CodecProperties::FIELDS`].
    #[must_use]
    pub fn ticks_per_frame(self) -> u32 {
        match self {
            Self::H264 | Self::Mpeg1video => 2,
            _ => 1,
        }
    }

    /// Samples per encoded frame, for a codec whose frame size the format
    /// fixes rather than states per file: AAC-LC 1024 (ISO/IEC 13818-7), MP3
    /// 1152 (ISO/IEC 11172-3), AC-3/E-AC-3 1536 (ATSC A/52, one independent
    /// frame — dependent E-AC-3 frames are not modelled here).
    ///
    /// `None` for a codec with no fixed size (Opus, Vorbis, FLAC, PCM), for
    /// `AacLatm` (LATM/LOAS framing can multiplex more than one access unit
    /// per logical frame, so the fixed-AAC answer does not transfer), and for
    /// every codec this crate has not measured. A demuxer with no parser
    /// uses this to reconstruct a stream's own last-frame duration — see
    /// `vaco-demux-mpegts`'s `end_pts` — and a wrong value there is worse
    /// than an absent one, so this is never guessed.
    #[must_use]
    pub const fn fixed_frame_size(self) -> Option<u32> {
        match self {
            Self::Aac => Some(1024),
            Self::Mp3 => Some(1152),
            Self::Ac3 | Self::Eac3 => Some(1536),
            _ => None,
        }
    }
}

/// Decode: compressed packets in, frames out.
///
/// The send/receive shape is not decoration. A decoder's packet-to-frame
/// relationship is genuinely N:M — one packet can yield several frames, several
/// packets can yield none while a reorder buffer fills, and flushing at EOF can
/// yield many. A `decode(packet) -> Frame` signature cannot express that, which
/// is why this API is shaped the way it is.
pub trait Decoder: Send {
    /// Submit a packet, or `None` to begin draining at end of stream.
    ///
    /// # Errors
    /// [`vaco_core::Error::OutputPending`] means frames must be drained via
    /// [`Decoder::receive_frame`] before more input is accepted.
    fn send_packet(&mut self, packet: Option<&Packet>) -> Result<()>;

    /// Take the next available frame.
    ///
    /// # Errors
    /// [`vaco_core::Error::NeedMoreInput`] means send another packet;
    /// [`vaco_core::Error::Eof`] means draining is complete.
    fn receive_frame(&mut self) -> Result<Frame>;

    /// Discard buffered state after a seek. Does not change configuration.
    fn flush(&mut self);

    /// Seed the decoder from the container's out-of-band configuration — the
    /// same conceptual record [`Parser::set_extradata`] takes, for a decoder
    /// reached through [`crate::DecoderDesc::build`] without ever passing
    /// through a `Parser` at all.
    ///
    /// DVD/`VobSub` is the concrete case this exists for. An SPU's
    /// `SET_COLOR` command carries four 4-bit *indices*, not colours — the
    /// 16-entry palette they index into lives entirely outside the SPU
    /// bytes, in the `.idx` sidecar or a Matroska `S_VOBSUB` track's
    /// `CodecPrivate`. Before this method existed, a decoder built from the
    /// registry had no way to be handed that palette and had to paint with a
    /// fallback instead — correct geometry and pixel indices, wrong colours.
    /// Not subtitle-only: any codec whose configuration is the container's to
    /// state (an `avcC`, an `AudioSpecificConfig`) has the identical shape.
    ///
    /// The default implementation ignores the record, which is right for a
    /// codec whose containers carry none — every implementor before this
    /// method existed keeps compiling and keeps its current behaviour.
    /// Calling it twice, or with an empty slice, must be harmless.
    ///
    /// # Errors
    ///
    /// Whatever the codec's own record parser returns. A caller that is
    /// merely *offering* extradata should treat an error the same way
    /// [`Parser::set_extradata`]'s doc says to: "this record told me
    /// nothing", not a reason to stop decoding.
    fn set_extradata(&mut self, extradata: &[u8]) -> Result<()> {
        let _ = extradata;
        Ok(())
    }
}

/// So a boxed decoder is itself a [`Decoder`], mirroring
/// `impl<P: Parser + ?Sized> Parser for Box<P>` below for the identical
/// reason: generic code written against `D: Decoder` has to keep working when
/// handed a `Box<dyn Decoder>`, which is all [`DecoderDesc::build`] ever
/// returns.
///
/// This also has to forward every method by hand, including the defaulted
/// [`Decoder::set_extradata`] — a `Box<D>` that inherited the trait's default
/// instead would silently discard every call, exactly the shape gap 9 found
/// in `Box<dyn Muxer>`.
impl<D: Decoder + ?Sized> Decoder for Box<D> {
    fn send_packet(&mut self, packet: Option<&Packet>) -> Result<()> {
        (**self).send_packet(packet)
    }

    fn receive_frame(&mut self) -> Result<Frame> {
        (**self).receive_frame()
    }

    fn flush(&mut self) {
        (**self).flush();
    }

    fn set_extradata(&mut self, extradata: &[u8]) -> Result<()> {
        (**self).set_extradata(extradata)
    }
}

/// Encode: frames in, compressed packets out. Mirrors [`Decoder`].
pub trait Encoder: Send {
    /// # Errors
    /// [`vaco_core::Error::OutputPending`] means drain before sending more.
    fn send_frame(&mut self, frame: Option<&Frame>) -> Result<()>;

    /// # Errors
    /// [`vaco_core::Error::NeedMoreInput`] or [`vaco_core::Error::Eof`].
    fn receive_packet(&mut self) -> Result<Packet>;

    fn flush(&mut self);

    /// Pixel formats this encoder's [`send_frame`](Encoder::send_frame)
    /// accepts, most-preferred first.
    ///
    /// The empty default means "whatever format arrives" — true of every audio
    /// encoder and of the video encoders that already negotiate their own
    /// format elsewhere. A video encoder that hard-fails on the wrong format
    /// (`vaco-codec-qoi`'s "encoder needs rgb24 or rgba input" is the
    /// motivating case) overrides this so a caller can convert *before*
    /// sending rather than parse the failure. Additive by construction — a
    /// default method, so every existing implementor keeps compiling.
    #[must_use]
    fn accepted_pix_fmts(&self) -> &'static [vaco_pixfmt::PixFmt] {
        &[]
    }

    /// Sample formats this encoder's [`send_frame`](Encoder::send_frame)
    /// accepts, most-preferred first.
    ///
    /// The audio mirror of [`accepted_pix_fmts`](Encoder::accepted_pix_fmts) —
    /// same empty-means-anything default, same reasoning. `vaco-codec-pcm`'s
    /// encoders are the motivating case: each `Pcm*` codec has exactly one
    /// wire format (`pcm_s16le` wants packed `S16`) and currently hard-fails
    /// a mismatch (`Error::Unsupported`) rather than silently mislabeling the
    /// stream, which is correct but was previously undetectable by a caller
    /// ahead of time — there was nothing to ask before calling `send_frame`
    /// and parsing the failure, the same gap the pixel-format version closed
    /// for video (E2E-GAPS 3).
    #[must_use]
    fn accepted_sample_fmts(&self) -> &'static [vaco_sampfmt::SampleFmt] {
        &[]
    }

    /// Configure a generic encoder option by name, mirroring the CLI's
    /// `-<name>[:<spec>] <value>` surface (`"b"` for bitrate, `"qscale"` for a
    /// fixed quality) after the encoder is built but before the first
    /// [`send_frame`](Encoder::send_frame).
    ///
    /// This is the channel [`EncoderDesc::build`] itself deliberately does not
    /// have — `make: fn(Limits) -> Box<dyn Encoder>` takes no options, so
    /// before this method existed there was no way for a caller to reach an
    /// encoder's own configuration at all: a working rate controller
    /// (`vaco-codec-vp8`'s CBR/VBR/constant-quality modes) was reachable only
    /// by calling a codec-specific constructor directly, which
    /// [`vaco_registry::encoder_by_name`]'s uniform `EncoderDesc` cannot do.
    ///
    /// The default rejects nothing and changes nothing: a generic `AVOption`
    /// the reference defines on every codec context (`bit_rate`, for one) is
    /// accepted silently by codecs that have no use for it — measured against
    /// `ffmpeg 8.1`, `-c:v png -b:v 1M` exits 0 and writes an unchanged PNG. A
    /// value this specific encoder cannot honour is the one case that should
    /// fail, via [`vaco_core::Error::Option`].
    ///
    /// # Errors
    /// [`vaco_core::Error::Option`] naming `key` when its value does not
    /// parse for a key this encoder does recognise.
    fn set_option(&mut self, key: &str, value: &str) -> Result<()> {
        let _ = (key, value);
        Ok(())
    }
}

/// Splits a byte stream into packets and reads enough header syntax to describe
/// the stream, without decoding it.
///
/// This is what v0.1 needs: `vaco-probe` reports stream properties, which means
/// parsing parameter sets, never reconstructing pixels. The distinction is also
/// load-bearing legally (plan 15 §1.6): parsing an H.264 SPS implements no
/// decoder, so header-parsing crates ship in the default build while the
/// decoders do not.
///
/// # The end-of-stream convention
///
/// An empty `input` slice means "no more bytes will ever arrive": emit any
/// partially buffered final unit, or return `(None, 0)`. [`ParserDriver`] is
/// what applies that convention, and what checks the parser does not claim to
/// have consumed more than it was given.
pub trait Parser: Send {
    /// Consume input, returning a complete packet when one is available and how
    /// many bytes were used.
    ///
    /// # Errors
    /// [`vaco_core::Error::InvalidData`] when the stream cannot be resynchronised.
    fn parse(&mut self, input: &[u8]) -> Result<(Option<Packet>, usize)>;

    /// Stream properties discovered so far, if enough header data has been seen.
    fn parameters(&self) -> Option<&CodecParameters>;

    /// Seed the parser from the container's out-of-band configuration —
    /// `avcC`, `hvcC`, `av1C`, an `AudioSpecificConfig`, an `OpusHead`.
    ///
    /// **This is the mechanism that makes a parser useful at all in MP4 and
    /// Matroska**, and it was the missing half of the `ParserProvider` seam. In
    /// an MPEG-TS or raw elementary stream every parameter set is in-band, so
    /// [`Parser::parse`] alone finds everything. In MP4 the sequence parameter
    /// set is in `avcC` and appears in **no packet at all**: a parser fed only
    /// payloads reports nothing, forever, however many packets it is given.
    /// Measured on `av.mp4` — 0 of the 8 bitstream-derived stream fields
    /// arrive through the packet path and 8 of 8 arrive through this one.
    ///
    /// Two further things ride on it, which is why it returns a value rather
    /// than being a plain setter:
    ///
    /// * the configuration record states the **NAL length prefix size**, which
    ///   is the only way a parser can read a length-prefixed sample at all;
    /// * `is_avc`/`nal_length_size` are printed by `-show_streams`, and they
    ///   are properties of the *container's* framing rather than of the
    ///   bitstream, so nothing downstream can derive them.
    ///
    /// Both are reported through [`CodecParameters`], so a caller that only
    /// wants parameters needs nothing but [`Parser::parameters`].
    ///
    /// The default implementation ignores the record, which is right for a
    /// codec whose containers carry none. Calling it twice, or with an empty
    /// slice, must be harmless.
    ///
    /// # Errors
    ///
    /// Whatever the codec's own record parser returns. A caller that is merely
    /// *offering* extradata — stream discovery is — should treat an error as
    /// "this record told me nothing" and carry on, because a malformed record
    /// is not a reason to stop reporting the container's own fields.
    fn set_extradata(&mut self, extradata: &[u8]) -> Result<()> {
        let _ = extradata;
        Ok(())
    }

    /// How long one **already-framed** packet lasts, in seconds, when that is a
    /// fact about the codec rather than about the container.
    ///
    /// `packet` is one whole access unit — a Matroska block frame, an MP4
    /// sample, a PES payload — the same slice [`Parser::parse`] would be given.
    /// `None` means "this codec does not state a packet duration", which is the
    /// default and the right answer for every video codec in v0.1.
    ///
    /// # Why this is on `Parser` at all
    ///
    /// Because the fact is a *codec* fact and the layering (D14.1) forbids a
    /// demuxer from naming a codec crate. Matroska writes no `DefaultDuration`
    /// for an Opus track and no `BlockDuration` on its blocks — the element is
    /// absent from the file, not misread — and the reference nonetheless
    /// reports 20 ms per packet, because it reads Opus's own TOC byte. The only
    /// seam a demuxer has onto codec code is
    /// [`ParserProvider`](../../vaco_format_core/trait.ParserProvider.html),
    /// which hands back a `dyn Parser`. So either the answer arrives through
    /// this trait or it does not arrive at all.
    ///
    /// # Why seconds, and why a `Rational`
    ///
    /// Three constraints, and this is the only shape that meets all three.
    ///
    /// * **It must be exact.** The consumer converts into the stream's time
    ///   base and the reference *truncates* that conversion (measured three
    ///   ways — see `vaco_format_core::time::quantise_duration`), so an input
    ///   that has already been rounded gives the wrong answer half a tick of
    ///   the time. A 2.5 ms Opus packet on Matroska's 1 ms base is exactly the
    ///   case: the reference prints `2`, and anything that reaches the
    ///   truncation as microseconds prints `3`.
    /// * **It must not need a second lookup.** "Samples" alone would make the
    ///   caller supply a rate, and the rate a caller has is the one the
    ///   *container* reports — which is wrong for both codecs here. Opus always
    ///   runs at 48 kHz whatever `input_sample_rate` says, and an SBR AAC
    ///   stream reports the *extension* rate while its frames are counted at
    ///   the core rate. Dividing inside the parser, which knows both halves,
    ///   removes the trap: 1024 core samples at 22050 Hz and 2048 output
    ///   samples at 44100 Hz are the same `Rational`, so SBR stops being a
    ///   special case anywhere else.
    /// * **It must not add a concept.** [`Rational`] is already this
    ///   workspace's exact ratio — it is what a `TimeBase` and a frame rate
    ///   are — so nothing new is defined and D19 is satisfied by construction.
    ///
    /// A rejected alternative, for the record: a `fn(&[u8]) -> Option<u64>`
    /// field on [`ParserDesc`] would be inspectable without constructing a
    /// parser, but AAC's answer lives in an `AudioSpecificConfig` the parser
    /// was handed by [`Parser::set_extradata`], so a free function cannot
    /// produce it. A second rejected alternative: returning ticks of a
    /// caller-supplied time base would put the truncation rule — a
    /// reference-matching decision — inside every parser instead of in one
    /// place.
    ///
    /// # Contract
    ///
    /// * `&self`, deliberately: this is a question, not a step. It must be
    ///   callable once per packet on the read path without advancing any
    ///   state, without allocating, and without the caller having fed the same
    ///   bytes to [`Parser::parse`] first.
    /// * A malformed packet is `None`, never an error and never a panic. The
    ///   caller is a demuxer filling in a field the container left blank; a
    ///   packet it cannot measure is one it reports without a duration, which
    ///   is what the container said in the first place.
    /// * The value is a duration, so it is non-negative and finite. A
    ///   zero-valued or non-finite `Rational` is treated as `None` downstream.
    fn packet_duration(&self, packet: &[u8]) -> Option<Rational> {
        let _ = packet;
        None
    }
}

/// So a boxed parser is itself a [`Parser`], and can be handed to anything
/// generic over `P: Parser` — [`ParserDriver`] above all.
///
/// Without this, a caller that obtains a parser dynamically (from a registry
/// lookup, or `ParserProvider::parser_for`, which can only return a `Box<dyn
/// Parser>` because the codec is not known until runtime) cannot use the driver
/// at all, and has to re-implement the end-of-stream convention and the
/// consumed-bytes check by hand. `vaco-format-core`'s stream discovery hit
/// exactly that and was doing so.
impl<P: Parser + ?Sized> Parser for Box<P> {
    fn parse(&mut self, input: &[u8]) -> Result<(Option<Packet>, usize)> {
        (**self).parse(input)
    }

    fn parameters(&self) -> Option<&CodecParameters> {
        (**self).parameters()
    }

    fn set_extradata(&mut self, extradata: &[u8]) -> Result<()> {
        (**self).set_extradata(extradata)
    }

    fn packet_duration(&self, packet: &[u8]) -> Option<Rational> {
        (**self).packet_duration(packet)
    }
}

/// Transforms packets without decoding: format conversion, metadata rewriting,
/// extradata extraction.
///
/// Deliberately the same state machine as [`Decoder`]: learning it once covers
/// all three faces.
pub trait BitstreamFilter: Send {
    /// # Errors
    /// [`vaco_core::Error::OutputPending`].
    fn send_packet(&mut self, packet: Option<&Packet>) -> Result<()>;

    /// # Errors
    /// [`vaco_core::Error::NeedMoreInput`] or [`vaco_core::Error::Eof`].
    fn receive_packet(&mut self) -> Result<Packet>;

    /// Set one filter-private option by name (gap 12, `planning/INTERFACE-GAPS.md`)
    /// — the seam for `-bsf:v filtername=opt=value`'s right-hand side, which
    /// [`vaco_format_core::mux::BsfProvider::open`]'s `(name, params)`
    /// signature has nowhere to carry.
    ///
    /// Mirrors `vaco_format_core::Muxer::set_option`'s name/value-string
    /// contract (gap 5) for the identical reason: a construction-time-only
    /// entry point cannot grow a parameter without touching every one of its
    /// ~90/~20 callers, so the door is a method opened after construction
    /// instead. A caller applies every option before the first
    /// [`BitstreamFilter::send_packet`].
    ///
    /// The default answers "no such option" for every name, which is
    /// correct for every filter registered before this method existed:
    /// nothing could call it, so refusing is not a behaviour change. A
    /// filter that grows options overrides it to parse its own.
    ///
    /// # Errors
    /// [`vaco_core::Error::Option`] naming `name`, when this filter has no
    /// such option or `value` does not parse for it. The default always errs.
    fn set_option(&mut self, name: &str, value: &str) -> Result<()> {
        let _ = value;
        Err(vaco_core::Error::Option {
            name: name.to_owned(),
            detail: "this bitstream filter has no such option".to_owned(),
        })
    }
}

/// Static description of a codec implementation.
///
/// The registry stores descriptors and constructs implementations on demand, so
/// `-h decoder=h264` can print capabilities without instantiating anything —
/// `make` is a `fn` pointer rather than a boxed factory for exactly the reason
/// [`ParserDesc::make`] is (see that field's docs): a `const` descriptor
/// holding a function pointer is inspectable without allocating, and `Box::new`
/// is not a `const` operation.
///
/// This carried no `make` field for a while, which meant a registered
/// `DecoderDesc` proved `vaco_registry::can_decode` true and nothing more —
/// there was no path from a registry lookup to a live [`Decoder`]. `vaco-cli`
/// is the caller this field exists for.
#[derive(Debug, Clone, Copy)]
pub struct DecoderDesc {
    pub name: &'static str,
    pub long_name: &'static str,
    pub id: CodecId,
    pub media_type: MediaType,
    pub caps: Caps,
    /// Frame rates, sample rates or pixel formats the implementation accepts;
    /// empty means unconstrained.
    pub supported_rates: &'static [Rational],
    /// Build one, bounded by `limits` — the decode-side dimensions/sample
    /// counts a demuxer's own bitstream states are attacker-controlled the
    /// same way a parser's are, so there is no `Default`-limits constructor
    /// here either; every caller states the budget.
    pub make: fn(Limits) -> Box<dyn Decoder>,
}

impl DecoderDesc {
    /// Whether this implementation may appear in a default build.
    ///
    /// D4 requires CI to assert that nothing patent-encumbered is *reachable*
    /// from the default feature set, and to assert it on the compiled artefact
    /// rather than on intent. [`Caps::PATENT_ENCUMBERED`] is the runtime half of
    /// that assertion and this is the predicate CI evaluates over the registry.
    #[must_use]
    pub const fn is_default_build_safe(&self) -> bool {
        !self.caps.contains(Caps::PATENT_ENCUMBERED)
    }

    /// Whether the implementation supports a given rate, treating an empty
    /// table as "unconstrained".
    #[must_use]
    pub fn supports_rate(&self, rate: Rational) -> bool {
        self.supported_rates.is_empty() || self.supported_rates.contains(&rate)
    }

    /// Build an instance bounded by `limits`.
    #[must_use]
    pub fn build(&self, limits: Limits) -> Box<dyn Decoder> {
        (self.make)(limits)
    }
}

/// Static description of an encoder implementation. Mirrors [`DecoderDesc`]
/// exactly, field for field — see that type's docs for why `make` is a `fn`
/// pointer and why it takes [`Limits`].
///
/// This type did not exist at all before it did. `vaco-registry`'s `encoder`
/// fragment kind had a name and a metadata row, and nothing else — no way to
/// *mean* anything by registering one, only a resolution check that the
/// named `ctor` compiled. This is the type that check was waiting for.
#[derive(Debug, Clone, Copy)]
pub struct EncoderDesc {
    pub name: &'static str,
    pub long_name: &'static str,
    pub id: CodecId,
    pub media_type: MediaType,
    pub caps: Caps,
    pub supported_rates: &'static [Rational],
    pub make: fn(Limits) -> Box<dyn Encoder>,
}

impl EncoderDesc {
    /// Whether this implementation may appear in a default build.
    #[must_use]
    pub const fn is_default_build_safe(&self) -> bool {
        !self.caps.contains(Caps::PATENT_ENCUMBERED)
    }

    /// Whether the implementation supports a given rate, treating an empty
    /// table as "unconstrained".
    #[must_use]
    pub fn supports_rate(&self, rate: Rational) -> bool {
        self.supported_rates.is_empty() || self.supported_rates.contains(&rate)
    }

    /// Build an instance bounded by `limits`.
    #[must_use]
    pub fn build(&self, limits: Limits) -> Box<dyn Encoder> {
        (self.make)(limits)
    }
}
