//! Generate `docs/format-coverage.md` from the component registry.
//!
//! The table backs a claim in `docs/why-some-formats-are-not-included.md`
//! that most of the gap against the reference is "not yet" rather than
//! "never". It is derived from the same `vaco-component.toml` fragments that
//! build the registry, so it cannot disagree with the binary.

use crate::{Task, crates, repo_root, toml};
use std::collections::{BTreeMap, BTreeSet};

/// Formats a decision record says we will not implement. Anything else we
/// lack is "not yet".
const EXCLUDED: &[(&str, &str)] = &[
    ("dvdvideo", "disc structure; GPL C libraries (plan 18 §9.3)"),
    ("bluray", "disc structure; GPL C libraries (plan 18 §9.3)"),
    ("avfoundation", "capture device (plan 18 §9.3)"),
    ("audiotoolbox", "playback device (plan 18 §9.3)"),
    ("v4l2", "capture device (plan 18 §9.3)"),
    ("dshow", "capture device (plan 18 §9.3)"),
    ("alsa", "playback device (plan 18 §9.3)"),
    ("x11grab", "capture device (plan 18 §9.3)"),
];

pub fn run(check: bool) -> Task {
    let root = repo_root();

    let mut demux: BTreeMap<String, String> = BTreeMap::new();
    let mut mux: BTreeMap<String, String> = BTreeMap::new();
    for (_area, name, path) in crates() {
        let frag = path.join("vaco-component.toml");
        if !frag.exists() {
            continue;
        }
        let text = std::fs::read_to_string(&frag).map_err(|e| format!("{name}: {e}"))?;
        let tables =
            toml::tables(&text, &["component"]).map_err(|e| format!("{}: {e}", frag.display()))?;
        for t in tables {
            let Some(component) = t.get("name") else {
                continue;
            };
            match t.get("kind") {
                Some("demuxer") => demux.insert(component.to_string(), name.clone()),
                Some("muxer") => mux.insert(component.to_string(), name.clone()),
                _ => None,
            };
        }
    }

    let data = root.join("xtask/data/reference-formats.txt");
    let text = std::fs::read_to_string(&data).map_err(|e| format!("{}: {e}", data.display()))?;
    let (ref_demux, ref_mux) = parse_reference(&text)?;

    let excluded: BTreeMap<&str, &str> = EXCLUDED.iter().copied().collect();
    let mut names: BTreeSet<&str> = BTreeSet::new();
    for n in ref_demux.iter().chain(ref_mux.iter()) {
        names.insert(n.as_str());
    }
    for n in demux.keys().chain(mux.keys()) {
        names.insert(n.as_str());
    }

    let mut have_d = 0usize;
    let mut have_m = 0usize;
    let mut not_yet: BTreeSet<&str> = BTreeSet::new();
    let mut rows = String::new();
    for name in &names {
        let d = demux.get(*name);
        let m = mux.get(*name);
        if d.is_some() {
            have_d += 1;
        }
        if m.is_some() {
            have_m += 1;
        }
        let wanted_d = ref_demux.contains(*name);
        let wanted_m = ref_mux.contains(*name);
        let note = match excluded.get(*name) {
            Some(reason) => (*reason).to_string(),
            None => {
                let missing = (wanted_d && d.is_none()) || (wanted_m && m.is_none());
                if missing {
                    not_yet.insert(name);
                    "not yet".to_string()
                } else if !wanted_d && !wanted_m {
                    "vaco-only".to_string()
                } else {
                    String::new()
                }
            }
        };
        rows.push_str(&format!(
            "| `{name}` | {} | {} | {note} |\n",
            cell(d, wanted_d),
            cell(m, wanted_m),
        ));
    }

    let total = names.len();
    let excluded_present = names.iter().filter(|n| excluded.contains_key(*n)).count();
    let out = format!(
        "# Format coverage\n\n\
         GENERATED by `cargo xtask gen-coverage`. Do not edit.\n\n\
         Every container format Vaco registers, alongside every one the reference\n\
         implementation registers. Read it with\n\
         [why-some-formats-are-not-included.md](why-some-formats-are-not-included.md),\n\
         which explains what the notes mean.\n\n\
         The reference column is a list of *names* measured off `ffmpeg -demuxers`\n\
         and `-muxers`; see `xtask/data/reference-formats.txt` for the exact\n\
         provenance. A blank note means we match the reference for that format.\n\n\
         ## Summary\n\n\
         | | Demux | Mux |\n|---|---|---|\n\
         | Vaco | {have_d} | {have_m} |\n\
         | Reference | {} | {} |\n\n\
         Of the {total} format names either side registers, **{}** are still to be\n\
         written and **{excluded_present}** {} excluded by a decision record. The\n\
         ratio between those two numbers is the point of the other document —\n\
         nearly everything Vaco lacks, it lacks because nobody has written it yet.\n\n\
         Most of the excluded list does not appear above at all: capture and\n\
         playback devices are not in `-demuxers`/`-muxers` output, they are in\n\
         `-devices`. They are named in the other document.\n\n\
         ## Formats\n\n\
         | Format | Demux | Mux | Note |\n|---|---|---|---|\n{rows}",
        ref_demux.len(),
        ref_mux.len(),
        not_yet.len(),
        if excluded_present == 1 { "is" } else { "are" },
    );

    let dest = root.join("docs/format-coverage.md");
    if check {
        let current = std::fs::read_to_string(&dest).unwrap_or_default();
        if current != out {
            return Err(format!(
                "{} is stale; run `cargo xtask gen-coverage`",
                dest.display()
            ));
        }
        println!("gen-coverage --check: up to date");
    } else {
        std::fs::write(&dest, out).map_err(|e| e.to_string())?;
        println!("gen-coverage: wrote {}", dest.display());
    }
    Ok(())
}

/// A crate name when we have the component, an em dash when we do not, and a
/// blank when neither side has it in that direction — so a missing cell in a
/// column the reference does not populate either is not read as a gap.
fn cell(owner: Option<&String>, wanted: bool) -> String {
    match (owner, wanted) {
        (Some(c), _) => format!("`{c}`"),
        (None, true) => "—".to_string(),
        (None, false) => String::new(),
    }
}

/// Which of `reference-formats.txt`'s bracketed sections a line falls under.
/// `Other` and `None` both mean "collect nothing", but stay distinct so a
/// stray name before the file's first heading is still an error rather than
/// silently accepted the same way a name in `[decoders]`/`[filters]`/etc. is.
#[derive(PartialEq, Eq)]
enum Section {
    None,
    Demux,
    Mux,
    Other,
}

fn parse_reference(text: &str) -> Result<(BTreeSet<String>, BTreeSet<String>), String> {
    let mut demux = BTreeSet::new();
    let mut mux = BTreeSet::new();
    let mut section = Section::None;
    for line in text.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        match line {
            "[demuxers]" => section = Section::Demux,
            "[muxers]" => section = Section::Mux,
            // The real bug this arm closes: `xtask/data/reference-formats.txt`
            // has five other bracketed sections after `[muxers]` —
            // `[decoders]`, `[encoders]`, `[filters]`, `[bitstream_filters]`,
            // `[protocols]` — and none of them used to reset `section` at
            // all, so every name in every one of them (hundreds) fell
            // through to the `name =>` arm below and was silently counted as
            // a *muxer*, the last section this function actually tracked.
            // Measured: `cargo xtask gen-coverage` reported "Reference: 1248"
            // muxers against a real count of ~184 before this fix — decoders
            // (527) + encoders (190) + filters (481) + bitstream_filters
            // (51) + protocols (41), plus their own header lines, all
            // dumped into the same `BTreeSet`.
            "[decoders]" | "[encoders]" | "[filters]" | "[bitstream_filters]" | "[protocols]" => {
                section = Section::Other;
            }
            name => match section {
                Section::Demux => {
                    demux.insert(name.to_string());
                }
                Section::Mux => {
                    mux.insert(name.to_string());
                }
                Section::Other => {}
                Section::None => {
                    return Err(format!(
                        "reference-formats.txt: `{name}` appears before any \
                         [demuxers] or [muxers] heading"
                    ));
                }
            },
        }
    }
    if demux.is_empty() || mux.is_empty() {
        return Err("reference-formats.txt: a section is empty".to_string());
    }
    Ok((demux, mux))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_before_a_heading_are_an_error_rather_than_silently_dropped() {
        assert!(parse_reference("avi\n[demuxers]\nmp4\n[muxers]\nmp4\n").is_err());
    }

    #[test]
    fn sections_are_kept_apart() {
        let (d, m) = parse_reference("[demuxers]\navi\nmp4\n[muxers]\nmp4\n")
            .expect("well-formed fixture parses");
        assert!(d.contains("avi") && !m.contains("avi"));
        assert!(d.contains("mp4") && m.contains("mp4"));
    }

    #[test]
    fn a_column_the_reference_does_not_populate_reads_blank_not_as_a_gap() {
        assert_eq!(cell(None, false), "");
        assert_eq!(cell(None, true), "—");
    }

    /// The real bug, reproduced with the file's actual section order:
    /// `[muxers]` is followed by `[decoders]`/`[encoders]`/`[filters]`/
    /// `[bitstream_filters]`/`[protocols]` in the real
    /// `xtask/data/reference-formats.txt`, and every name in every one of
    /// those five used to be silently counted as a muxer because nothing
    /// reset `section` when a heading it did not recognise went by.
    #[test]
    fn sections_after_muxers_do_not_leak_into_it() {
        let (d, m) = parse_reference(
            "[demuxers]\navi\n[muxers]\nmp4\n[decoders]\nh264\nvp9\n\
             [encoders]\naac\n[filters]\nscale\n[bitstream_filters]\nnull\n\
             [protocols]\nfile\n",
        )
        .expect("well-formed fixture parses");
        assert_eq!(d, BTreeSet::from(["avi".to_string()]));
        assert_eq!(m, BTreeSet::from(["mp4".to_string()]));
    }

    /// A name before the file's very first recognised heading is still an
    /// error — the fix for the leak above must not also silence this.
    #[test]
    fn names_before_the_first_heading_still_error_even_with_later_sections() {
        assert!(
            parse_reference("avi\n[demuxers]\nmp4\n[muxers]\nmp4\n[decoders]\nh264\n").is_err()
        );
    }
}
