//! Generate `docs/README.md` from per-crate documentation front-matter.
//!
//! Same reasoning as the registry: a hand-maintained index is a file every crate
//! must edit. Measured on a comparable project, a docs index was the single
//! highest-churn file in the repository.

use crate::{crates, repo_root, Task};

pub fn run(check: bool) -> Task {
    let root = repo_root();
    let mut rows = Vec::new();

    for (layer, name, path) in crates() {
        let manifest = std::fs::read_to_string(path.join("Cargo.toml")).unwrap_or_default();
        let desc = manifest
            .lines()
            .find(|l| l.trim_start().starts_with("description"))
            .and_then(|l| l.split('"').nth(1))
            .unwrap_or("")
            .to_string();
        let doc = format!("docs/{layer}/{name}.md");
        let exists = root.join(&doc).exists();
        rows.push((layer, name, desc, doc, exists));
    }

    let mut out = String::from(
        "# Vaco documentation\n\n\
         GENERATED by `cargo xtask gen-docs-index`. Do not edit.\n\n\
         | Crate | Layer | Purpose | Doc |\n|---|---|---|---|\n",
    );
    for (layer, name, desc, doc, exists) in &rows {
        let link = if *exists { format!("[{name}]({doc})") } else { "—".into() };
        out.push_str(&format!("| `{name}` | {layer} | {desc} | {link} |\n"));
    }

    let dest = root.join("docs/README.md");
    if check {
        let current = std::fs::read_to_string(&dest).unwrap_or_default();
        if current != out {
            return Err(format!("{} is stale; run `just gen-docs-index`", dest.display()));
        }
        println!("gen-docs-index --check: up to date");
    } else {
        std::fs::create_dir_all(root.join("docs")).map_err(|e| e.to_string())?;
        std::fs::write(&dest, out).map_err(|e| e.to_string())?;
        println!("gen-docs-index: {} crates indexed", rows.len());
    }
    Ok(())
}
