//! Assemble `vaco-registry` from per-crate `vaco-component.toml` fragments.
//!
//! Registration is generated rather than hand-edited because the registry would
//! otherwise be a file every one of ~120 crates must touch — the single worst
//! contention point in a shared working tree (plan 19 §3.4). A crate declares
//! what it provides; this walks the tree and emits the table.
//!
//! Linker-section registration (`inventory`, `linkme`) would also solve the
//! contention, but both rely on `unsafe` and link tricks, which D2 rules out.

use crate::{crates, repo_root, Task};

pub fn run(check: bool) -> Task {
    let mut components: Vec<(String, String)> = Vec::new();

    for (_, name, path) in crates() {
        let frag = path.join("vaco-component.toml");
        if frag.exists() {
            let text = std::fs::read_to_string(&frag).map_err(|e| format!("{name}: {e}"))?;
            components.push((name, text));
        }
    }

    let mut out = String::from(
        "//! GENERATED by `cargo xtask gen-registry`. Do not edit.\n\
         //!\n\
         //! Assembled from `vaco-component.toml` fragments so that adding a component\n\
         //! touches only that component's own crate (plan 19 §3.4).\n\n",
    );

    if components.is_empty() {
        out.push_str("// No components registered yet.\n");
    }
    for (name, _) in &components {
        out.push_str(&format!("// {name}\n"));
    }

    let dest = repo_root().join("crates/registry/vaco-registry/src/generated.rs");
    if check {
        let current = std::fs::read_to_string(&dest).unwrap_or_default();
        if current != out {
            return Err(format!(
                "{} is stale; run `just gen-registry`",
                dest.display()
            ));
        }
        println!("gen-registry --check: up to date ({} components)", components.len());
    } else {
        if let Some(p) = dest.parent() {
            std::fs::create_dir_all(p).map_err(|e| e.to_string())?;
        }
        std::fs::write(&dest, out).map_err(|e| e.to_string())?;
        println!("gen-registry: wrote {} components", components.len());
    }
    Ok(())
}
