//! Reference output captured from the real `ffprobe`, byte for byte.
//!
//! GENERATED BY OBSERVATION, NOT BY HAND. Every entry is the exact stdout of
//! one `ffprobe` invocation under `LC_ALL=C`, recorded with the command that
//! produced it. Regenerate only against a reference binary whose
//! `ffprobe -version` is recorded in `docs/app/vaco-textformat.md`.
//!
//! Reference: ffprobe version 8.1 (Homebrew, 2026), libavformat 62.12.100.
//!
//! The five sample files are built by these commands; the torture string is
//! the one from plan 14 §4.3.
//!
//! ```sh
//! NASTY='v=1,c:2|q"3\4;e[f]#g <&> ünï'
//! ffmpeg -f lavfi -i 'sine=frequency=440:duration=1:sample_rate=44100' -c:a aac \
//!        -metadata:s:a:0 "nasty=$NASTY" -metadata:s:a:0 'we-ird key.1=x' t.mkv
//! ffmpeg -f lavfi -i 'sine=duration=0.2' -c:a aac \
//!        -metadata:s:a:0 "$(python3 -c \"print('x='+''.join('%02x'%i+chr(i) for i in range(1,32)))\")" t6.mkv
//! ffmpeg -f lavfi -i 'sine=frequency=440:duration=1:sample_rate=44100' -c:a aac t.mp4
//! ffmpeg -f lavfi -i 'testsrc=size=64x48:rate=10:duration=0.5' \
//!        -f lavfi -i 'sine=duration=0.5' -map 0:v -map 1:a \
//!        -c:v libx264 -c:a aac -f mpegts p.ts
//! ```

#![allow(
    unreachable_pub,
    reason = "shared by the test binaries that include it"
)]

/// One captured invocation: the scenario, the `-of` argument, the arguments
/// that produced it, and its exact stdout.
#[derive(Debug)]
pub struct Capture {
    /// Name of the scenario the test harness replays.
    pub scenario: &'static str,
    /// The `-of` argument.
    pub spec: &'static str,
    /// The remaining ffprobe arguments, for regeneration.
    pub args: &'static str,
    /// Exact stdout.
    pub bytes: &'static [u8],
}

/// Everything captured.
pub static CAPTURES: &[Capture] = &[
    Capture {
        scenario: "torture_tag",
        spec: "default",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"[STREAM]\nTAG:NASTY=v=1,c:2|q\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n[/STREAM]\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream|tag:NASTY=v=1,c:2\\|q\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "csv",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream,\"v=1,c:2|q\"\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "flat",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"streams.stream.0.tags.NASTY=\"v=1,c:2|q\\\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "ini",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"# ffprobe output\n\n[streams.stream.0]\n[streams.stream.0.tags]\nNASTY=v\\=1,c\\:2|q\"3\\\\4;e[f]\\#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "json",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"{\n    \"streams\": [\n        {\n            \"tags\": {\n                \"NASTY\": \"v=1,c:2|q\\\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n            }\n        }\n    ]\n}\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "xml",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <streams>\n        <stream >\n            <tags>\n                <tag key=\"NASTY\" value=\"v=1,c:2|q&quot;3\\4;e[f]#g &lt;&amp;&gt; \xc3\xbcn\xc3\xaf\"/>\n            </tags>\n        </stream>\n    </streams>\n</ffprobe>\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact=e=csv",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream|tag:NASTY=\"v=1,c:2|q\"\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact=e=none",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream|tag:NASTY=v=1,c:2|q\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact=p=0",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"tag:NASTY=v=1,c:2\\|q\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact=nk=1",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream|v=1,c:2\\|q\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "compact=s=@",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream@tag:NASTY=v=1,c:2|q\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "csv=e=c",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream,v=1\\,c:2|q\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "default=nk=1",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"[STREAM]\nv=1,c:2|q\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n[/STREAM]\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "default=nw=1",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"TAG:NASTY=v=1,c:2|q\"3\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "flat=h=0",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"stream.0.tags.NASTY=\"v=1,c:2|q\\\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "flat=s=#",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"streams#stream#0#tags#NASTY=\"v=1,c:2|q\\\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\"\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "ini=h=0",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"# ffprobe output\n\n[stream.0]\n[stream.0.tags]\nNASTY=v\\=1,c\\:2|q\"3\\\\4;e[f]\\#g <&> \xc3\xbcn\xc3\xaf\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "json=c=1",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"{\n    \"streams\": [\n        {             \"tags\": { \"NASTY\": \"v=1,c:2|q\\\"3\\\\4;e[f]#g <&> \xc3\xbcn\xc3\xaf\" } }\n    ]\n}\n",
    },
    Capture {
        scenario: "torture_tag",
        spec: "xml=q=1",
        args: "-show_entries stream_tags=NASTY t.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <streams>\n        <stream >\n            <tags>\n                <tag key=\"NASTY\" value=\"v=1,c:2|q&quot;3\\4;e[f]#g &lt;&amp;&gt; \xc3\xbcn\xc3\xaf\"/>\n            </tags>\n        </stream>\n    </streams>\n</ffprobe:ffprobe>\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "default",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"[STREAM]\nTAG:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n[/STREAM]\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream|tag:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\\b09\t0a\\n0b\x0b0c\\f0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "csv",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream,\"01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\"\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "flat",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"streams.stream.0.tags.X=\"01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\\n0b\x0b0c\x0c0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\"\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "ini",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"# ffprobe output\n\n[streams.stream.0]\n[streams.stream.0.tags]\nX=01\\x000102\\x000203\\x000304\\x000405\\x000506\\x000607\\x000708\\b09\\t0a\\n0b\\x000b0c\\f0d\\r0e\\x000e0f\\x000f10\\x001011\\x001112\\x001213\\x001314\\x001415\\x001516\\x001617\\x001718\\x001819\\x00191a\\x001a1b\\x001b1c\\x001c1d\\x001d1e\\x001e1f\\x001f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "json",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"{\n    \"streams\": [\n        {\n            \"tags\": {\n                \"X\": \"01\\u000102\\u000203\\u000304\\u000405\\u000506\\u000607\\u000708\\b09\\t0a\\n0b\\u000b0c\\f0d\\r0e\\u000e0f\\u000f10\\u001011\\u001112\\u001213\\u001314\\u001415\\u001516\\u001617\\u001718\\u001819\\u00191a\\u001a1b\\u001b1c\\u001c1d\\u001d1e\\u001e1f\\u001f\"\n            }\n        }\n    ]\n}\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "xml",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <streams>\n        <stream >\n            <tags>\n                <tag key=\"X\" value=\"01\xef\xbf\xbd02\xef\xbf\xbd03\xef\xbf\xbd04\xef\xbf\xbd05\xef\xbf\xbd06\xef\xbf\xbd07\xef\xbf\xbd08\xef\xbf\xbd09\t0a\n0b\xef\xbf\xbd0c\xef\xbf\xbd0d\r0e\xef\xbf\xbd0f\xef\xbf\xbd10\xef\xbf\xbd11\xef\xbf\xbd12\xef\xbf\xbd13\xef\xbf\xbd14\xef\xbf\xbd15\xef\xbf\xbd16\xef\xbf\xbd17\xef\xbf\xbd18\xef\xbf\xbd19\xef\xbf\xbd1a\xef\xbf\xbd1b\xef\xbf\xbd1c\xef\xbf\xbd1d\xef\xbf\xbd1e\xef\xbf\xbd1f\xef\xbf\xbd\"/>\n            </tags>\n        </stream>\n    </streams>\n</ffprobe>\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact=e=csv",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream|tag:X=\"01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\"\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact=e=none",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream|tag:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact=p=0",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"tag:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\\b09\t0a\\n0b\x0b0c\\f0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact=nk=1",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream|01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\\b09\t0a\\n0b\x0b0c\\f0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "compact=s=@",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream@tag:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\\b09\t0a\\n0b\x0b0c\\f0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "csv=e=c",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream,01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\\b09\t0a\\n0b\x0b0c\\f0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "default=nk=1",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"[STREAM]\n01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n[/STREAM]\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "default=nw=1",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"TAG:X=01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\n0b\x0b0c\x0c0d\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "flat=h=0",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"stream.0.tags.X=\"01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\\n0b\x0b0c\x0c0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\"\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "flat=s=#",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"streams#stream#0#tags#X=\"01\x0102\x0203\x0304\x0405\x0506\x0607\x0708\x0809\t0a\\n0b\x0b0c\x0c0d\\r0e\x0e0f\x0f10\x1011\x1112\x1213\x1314\x1415\x1516\x1617\x1718\x1819\x191a\x1a1b\x1b1c\x1c1d\x1d1e\x1e1f\x1f\"\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "ini=h=0",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"# ffprobe output\n\n[stream.0]\n[stream.0.tags]\nX=01\\x000102\\x000203\\x000304\\x000405\\x000506\\x000607\\x000708\\b09\\t0a\\n0b\\x000b0c\\f0d\\r0e\\x000e0f\\x000f10\\x001011\\x001112\\x001213\\x001314\\x001415\\x001516\\x001617\\x001718\\x001819\\x00191a\\x001a1b\\x001b1c\\x001c1d\\x001d1e\\x001e1f\\x001f\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "json=c=1",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"{\n    \"streams\": [\n        {             \"tags\": { \"X\": \"01\\u000102\\u000203\\u000304\\u000405\\u000506\\u000607\\u000708\\b09\\t0a\\n0b\\u000b0c\\f0d\\r0e\\u000e0f\\u000f10\\u001011\\u001112\\u001213\\u001314\\u001415\\u001516\\u001617\\u001718\\u001819\\u00191a\\u001a1b\\u001b1c\\u001c1d\\u001d1e\\u001e1f\\u001f\" } }\n    ]\n}\n",
    },
    Capture {
        scenario: "control_chars",
        spec: "xml=q=1",
        args: "-show_entries stream_tags=X t6.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <streams>\n        <stream >\n            <tags>\n                <tag key=\"X\" value=\"01\xef\xbf\xbd02\xef\xbf\xbd03\xef\xbf\xbd04\xef\xbf\xbd05\xef\xbf\xbd06\xef\xbf\xbd07\xef\xbf\xbd08\xef\xbf\xbd09\t0a\n0b\xef\xbf\xbd0c\xef\xbf\xbd0d\r0e\xef\xbf\xbd0f\xef\xbf\xbd10\xef\xbf\xbd11\xef\xbf\xbd12\xef\xbf\xbd13\xef\xbf\xbd14\xef\xbf\xbd15\xef\xbf\xbd16\xef\xbf\xbd17\xef\xbf\xbd18\xef\xbf\xbd19\xef\xbf\xbd1a\xef\xbf\xbd1b\xef\xbf\xbd1c\xef\xbf\xbd1d\xef\xbf\xbd1e\xef\xbf\xbd1f\xef\xbf\xbd\"/>\n            </tags>\n        </stream>\n    </streams>\n</ffprobe:ffprobe>\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "default",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"[PACKET]\ncodec_type=audio\nstream_index=0\npts=-1024\npts_time=-0.023220\ndts=-1024\ndts_time=-0.023220\nduration=1024\nduration_time=0.023220\nsize=258\npos=44\nflags=KD_\n[SIDE_DATA]\nside_data_type=Skip Samples\nskip_samples=1024\ndiscard_padding=0\nskip_reason=0\ndiscard_reason=0\n[/SIDE_DATA]\n[/PACKET]\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet|codec_type=audio|stream_index=0|pts=-1024|pts_time=-0.023220|dts=-1024|dts_time=-0.023220|duration=1024|duration_time=0.023220|size=258|pos=44|flags=KD_|side_datum/skip_samples:side_data_type=Skip Samples|side_datum/skip_samples:skip_samples=1024|side_datum/skip_samples:discard_padding=0|side_datum/skip_samples:skip_reason=0|side_datum/skip_samples:discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "csv",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet,audio,0,-1024,-0.023220,-1024,-0.023220,1024,0.023220,258,44,KD_,Skip Samples,1024,0,0,0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "flat",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packets.packet.0.codec_type=\"audio\"\npackets.packet.0.stream_index=0\npackets.packet.0.pts=-1024\npackets.packet.0.pts_time=\"-0.023220\"\npackets.packet.0.dts=-1024\npackets.packet.0.dts_time=\"-0.023220\"\npackets.packet.0.duration=1024\npackets.packet.0.duration_time=\"0.023220\"\npackets.packet.0.size=\"258\"\npackets.packet.0.pos=\"44\"\npackets.packet.0.flags=\"KD_\"\npackets.packet.0.side_data_list.side_data.0.side_data_type=\"Skip Samples\"\npackets.packet.0.side_data_list.side_data.0.skip_samples=1024\npackets.packet.0.side_data_list.side_data.0.discard_padding=0\npackets.packet.0.side_data_list.side_data.0.skip_reason=0\npackets.packet.0.side_data_list.side_data.0.discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "ini",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"# ffprobe output\n\n[packets.packet.0]\ncodec_type=audio\nstream_index=0\npts=-1024\npts_time=-0.023220\ndts=-1024\ndts_time=-0.023220\nduration=1024\nduration_time=0.023220\nsize=258\npos=44\nflags=KD_\n\n[packets.packet.0.side_data_list.side_data.0]\nside_data_type=Skip Samples\nskip_samples=1024\ndiscard_padding=0\nskip_reason=0\ndiscard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "json",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"{\n    \"packets\": [\n        {\n            \"codec_type\": \"audio\",\n            \"stream_index\": 0,\n            \"pts\": -1024,\n            \"pts_time\": \"-0.023220\",\n            \"dts\": -1024,\n            \"dts_time\": \"-0.023220\",\n            \"duration\": 1024,\n            \"duration_time\": \"0.023220\",\n            \"size\": \"258\",\n            \"pos\": \"44\",\n            \"flags\": \"KD_\",\n            \"side_data_list\": [\n                {\n                    \"side_data_type\": \"Skip Samples\",\n                    \"skip_samples\": 1024,\n                    \"discard_padding\": 0,\n                    \"skip_reason\": 0,\n                    \"discard_reason\": 0\n                }\n            ]\n        }\n    ]\n}\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "xml",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <packets>\n        <packet codec_type=\"audio\" stream_index=\"0\" pts=\"-1024\" pts_time=\"-0.023220\" dts=\"-1024\" dts_time=\"-0.023220\" duration=\"1024\" duration_time=\"0.023220\" size=\"258\" pos=\"44\" flags=\"KD_\">\n            <side_data_list>\n                <side_data type=\"Skip Samples\">\n                    <side_datum key=\"side_data_type\" value=\"Skip Samples\"/>\n                    <side_datum key=\"skip_samples\" value=\"1024\"/>\n                    <side_datum key=\"discard_padding\" value=\"0\"/>\n                    <side_datum key=\"skip_reason\" value=\"0\"/>\n                    <side_datum key=\"discard_reason\" value=\"0\"/>\n                </side_data>\n            </side_data_list>\n        </packet>\n    </packets>\n</ffprobe>\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact=e=csv",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet|codec_type=audio|stream_index=0|pts=-1024|pts_time=-0.023220|dts=-1024|dts_time=-0.023220|duration=1024|duration_time=0.023220|size=258|pos=44|flags=KD_|side_datum/skip_samples:side_data_type=Skip Samples|side_datum/skip_samples:skip_samples=1024|side_datum/skip_samples:discard_padding=0|side_datum/skip_samples:skip_reason=0|side_datum/skip_samples:discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact=e=none",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet|codec_type=audio|stream_index=0|pts=-1024|pts_time=-0.023220|dts=-1024|dts_time=-0.023220|duration=1024|duration_time=0.023220|size=258|pos=44|flags=KD_|side_datum/skip_samples:side_data_type=Skip Samples|side_datum/skip_samples:skip_samples=1024|side_datum/skip_samples:discard_padding=0|side_datum/skip_samples:skip_reason=0|side_datum/skip_samples:discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact=p=0",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"codec_type=audio|stream_index=0|pts=-1024|pts_time=-0.023220|dts=-1024|dts_time=-0.023220|duration=1024|duration_time=0.023220|size=258|pos=44|flags=KD_|side_datum/skip_samples:side_data_type=Skip Samples|side_datum/skip_samples:skip_samples=1024|side_datum/skip_samples:discard_padding=0|side_datum/skip_samples:skip_reason=0|side_datum/skip_samples:discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact=nk=1",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet|audio|0|-1024|-0.023220|-1024|-0.023220|1024|0.023220|258|44|KD_|Skip Samples|1024|0|0|0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "compact=s=@",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet@codec_type=audio@stream_index=0@pts=-1024@pts_time=-0.023220@dts=-1024@dts_time=-0.023220@duration=1024@duration_time=0.023220@size=258@pos=44@flags=KD_@side_datum/skip_samples:side_data_type=Skip Samples@side_datum/skip_samples:skip_samples=1024@side_datum/skip_samples:discard_padding=0@side_datum/skip_samples:skip_reason=0@side_datum/skip_samples:discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "csv=e=c",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet,audio,0,-1024,-0.023220,-1024,-0.023220,1024,0.023220,258,44,KD_,Skip Samples,1024,0,0,0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "default=nk=1",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"[PACKET]\naudio\n0\n-1024\n-0.023220\n-1024\n-0.023220\n1024\n0.023220\n258\n44\nKD_\n[SIDE_DATA]\nSkip Samples\n1024\n0\n0\n0\n[/SIDE_DATA]\n[/PACKET]\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "default=nw=1",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"codec_type=audio\nstream_index=0\npts=-1024\npts_time=-0.023220\ndts=-1024\ndts_time=-0.023220\nduration=1024\nduration_time=0.023220\nsize=258\npos=44\nflags=KD_\nside_data_type=Skip Samples\nskip_samples=1024\ndiscard_padding=0\nskip_reason=0\ndiscard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "flat=h=0",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packet.0.codec_type=\"audio\"\npacket.0.stream_index=0\npacket.0.pts=-1024\npacket.0.pts_time=\"-0.023220\"\npacket.0.dts=-1024\npacket.0.dts_time=\"-0.023220\"\npacket.0.duration=1024\npacket.0.duration_time=\"0.023220\"\npacket.0.size=\"258\"\npacket.0.pos=\"44\"\npacket.0.flags=\"KD_\"\npacket.0.side_data.0.side_data_type=\"Skip Samples\"\npacket.0.side_data.0.skip_samples=1024\npacket.0.side_data.0.discard_padding=0\npacket.0.side_data.0.skip_reason=0\npacket.0.side_data.0.discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "flat=s=#",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"packets#packet#0#codec_type=\"audio\"\npackets#packet#0#stream_index=0\npackets#packet#0#pts=-1024\npackets#packet#0#pts_time=\"-0.023220\"\npackets#packet#0#dts=-1024\npackets#packet#0#dts_time=\"-0.023220\"\npackets#packet#0#duration=1024\npackets#packet#0#duration_time=\"0.023220\"\npackets#packet#0#size=\"258\"\npackets#packet#0#pos=\"44\"\npackets#packet#0#flags=\"KD_\"\npackets#packet#0#side_data_list#side_data#0#side_data_type=\"Skip Samples\"\npackets#packet#0#side_data_list#side_data#0#skip_samples=1024\npackets#packet#0#side_data_list#side_data#0#discard_padding=0\npackets#packet#0#side_data_list#side_data#0#skip_reason=0\npackets#packet#0#side_data_list#side_data#0#discard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "ini=h=0",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"# ffprobe output\n\n[packet.0]\ncodec_type=audio\nstream_index=0\npts=-1024\npts_time=-0.023220\ndts=-1024\ndts_time=-0.023220\nduration=1024\nduration_time=0.023220\nsize=258\npos=44\nflags=KD_\n\n[packet.0.side_data.0]\nside_data_type=Skip Samples\nskip_samples=1024\ndiscard_padding=0\nskip_reason=0\ndiscard_reason=0\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "json=c=1",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"{\n    \"packets\": [\n        { \"codec_type\": \"audio\", \"stream_index\": 0, \"pts\": -1024, \"pts_time\": \"-0.023220\", \"dts\": -1024, \"dts_time\": \"-0.023220\", \"duration\": 1024, \"duration_time\": \"0.023220\", \"size\": \"258\", \"pos\": \"44\", \"flags\": \"KD_\",\n            \"side_data_list\": [\n                { \"side_data_type\": \"Skip Samples\", \"skip_samples\": 1024, \"discard_padding\": 0, \"skip_reason\": 0, \"discard_reason\": 0 }\n            ] }\n    ]\n}\n",
    },
    Capture {
        scenario: "packet_side_data",
        spec: "xml=q=1",
        args: "-show_packets -read_intervals %+#1 t.mp4",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <packets>\n        <packet codec_type=\"audio\" stream_index=\"0\" pts=\"-1024\" pts_time=\"-0.023220\" dts=\"-1024\" dts_time=\"-0.023220\" duration=\"1024\" duration_time=\"0.023220\" size=\"258\" pos=\"44\" flags=\"KD_\">\n            <side_data_list>\n                <side_data type=\"Skip Samples\">\n                    <side_datum key=\"side_data_type\" value=\"Skip Samples\"/>\n                    <side_datum key=\"skip_samples\" value=\"1024\"/>\n                    <side_datum key=\"discard_padding\" value=\"0\"/>\n                    <side_datum key=\"skip_reason\" value=\"0\"/>\n                    <side_datum key=\"discard_reason\" value=\"0\"/>\n                </side_data>\n            </side_data_list>\n        </packet>\n    </packets>\n</ffprobe:ffprobe>\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "default",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"[PROGRAM]\nprogram_id=1\n[STREAM]\nindex=0\n[/STREAM]\n[STREAM]\nindex=1\n[/STREAM]\n[/PROGRAM]\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program|program_id=1|stream|index=0\nstream|index=1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "csv",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program,1,stream,0\nstream,1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "flat",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"programs.program.0.program_id=1\nprograms.program.0.streams.stream.0.index=0\nprograms.program.0.streams.stream.1.index=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "ini",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"# ffprobe output\n\n[programs.program.0]\nprogram_id=1\n\n[programs.program.0.streams.stream.0]\nindex=0\n\n[programs.program.0.streams.stream.1]\nindex=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "json",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"{\n    \"programs\": [\n        {\n            \"program_id\": 1,\n            \"streams\": [\n                {\n                    \"index\": 0\n                },\n                {\n                    \"index\": 1\n                }\n            ]\n        }\n    ]\n}\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "xml",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <programs>\n        <program program_id=\"1\">\n            <streams>\n                <stream index=\"0\"/>\n                <stream index=\"1\"/>\n            </streams>\n        </program>\n    </programs>\n</ffprobe>\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact=e=csv",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program|program_id=1|stream|index=0\nstream|index=1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact=e=none",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program|program_id=1|stream|index=0\nstream|index=1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact=p=0",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program_id=1|index=0\nindex=1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact=nk=1",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program|1|stream|0\nstream|1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "compact=s=@",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program@program_id=1@stream@index=0\nstream@index=1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "csv=e=c",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program,1,stream,0\nstream,1\n\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "default=nk=1",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"[PROGRAM]\n1\n[STREAM]\n0\n[/STREAM]\n[STREAM]\n1\n[/STREAM]\n[/PROGRAM]\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "default=nw=1",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program_id=1\nindex=0\nindex=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "flat=h=0",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"program.0.program_id=1\nprogram.0.stream.0.index=0\nprogram.0.stream.1.index=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "flat=s=#",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"programs#program#0#program_id=1\nprograms#program#0#streams#stream#0#index=0\nprograms#program#0#streams#stream#1#index=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "ini=h=0",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"# ffprobe output\n\n[program.0]\nprogram_id=1\n\n[program.0.stream.0]\nindex=0\n\n[program.0.stream.1]\nindex=1\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "json=c=1",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"{\n    \"programs\": [\n        { \"program_id\": 1,\n            \"streams\": [\n                { \"index\": 0 },\n                { \"index\": 1 }\n            ] }\n    ]\n}\n",
    },
    Capture {
        scenario: "program_streams",
        spec: "xml=q=1",
        args: "-show_entries program=program_id:program_stream=index p.ts",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <programs>\n        <program program_id=\"1\">\n            <streams>\n                <stream index=\"0\"/>\n                <stream index=\"1\"/>\n            </streams>\n        </program>\n    </programs>\n</ffprobe:ffprobe>\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "default",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"[STREAM]\nindex=0\n[/STREAM]\n[STREAM]\nindex=1\n[/STREAM]\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream|index=0\nstream|index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "csv",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream,0\nstream,1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "flat",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"streams.stream.0.index=0\nstreams.stream.1.index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "ini",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"# ffprobe output\n\n\n\n[streams.stream.0]\nindex=0\n\n[streams.stream.1]\nindex=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "json",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"{\n    \"programs\": [\n\n    ],\n    \"stream_groups\": [\n\n    ],\n    \"streams\": [\n        {\n            \"index\": 0\n        },\n        {\n            \"index\": 1\n        }\n    ]\n}\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "xml",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <programs>\n    </programs>\n\n    <stream_groups>\n    </stream_groups>\n\n    <streams>\n        <stream index=\"0\"/>\n        <stream index=\"1\"/>\n    </streams>\n</ffprobe>\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact=e=csv",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream|index=0\nstream|index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact=e=none",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream|index=0\nstream|index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact=p=0",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"index=0\nindex=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact=nk=1",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream|0\nstream|1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "compact=s=@",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream@index=0\nstream@index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "csv=e=c",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream,0\nstream,1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "default=nk=1",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"[STREAM]\n0\n[/STREAM]\n[STREAM]\n1\n[/STREAM]\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "default=nw=1",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"index=0\nindex=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "flat=h=0",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"stream.0.index=0\nstream.1.index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "flat=s=#",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"streams#stream#0#index=0\nstreams#stream#1#index=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "ini=h=0",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"# ffprobe output\n\n\n\n[stream.0]\nindex=0\n\n[stream.1]\nindex=1\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "json=c=1",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"{\n    \"programs\": [\n\n    ],\n    \"stream_groups\": [\n\n    ],\n    \"streams\": [\n        { \"index\": 0 },\n        { \"index\": 1 }\n    ]\n}\n",
    },
    Capture {
        scenario: "empty_arrays",
        spec: "xml=q=1",
        args: "-show_entries stream=index t2.mkv",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <programs>\n    </programs>\n\n    <stream_groups>\n    </stream_groups>\n\n    <streams>\n        <stream index=\"0\"/>\n        <stream index=\"1\"/>\n    </streams>\n</ffprobe:ffprobe>\n",
    },
];

/// A second batch, appended by the same generator: one stream and the
/// format section together, which is where the `xml` writer's blank line
/// between root children and the two inline styles (`DISPOSITION:` from a
/// plain section, `TAG:` from a variable-field one) show up side by side.
pub static CAPTURES_STREAM_AND_FORMAT: &[Capture] = &[
    Capture {
        scenario: "stream_and_format",
        spec: "default",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"[STREAM]\nindex=0\nDISPOSITION:default=1\nDISPOSITION:forced=0\nTAG:language=und\n[/STREAM]\n[FORMAT]\nsize=10028\nTAG:title=hello\n[/FORMAT]\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream|index=0|disposition:default=1|disposition:forced=0|tag:language=und\nformat|size=10028|tag:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "csv",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream,0,1,0,und\nformat,10028,hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "flat",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"streams.stream.0.index=0\nstreams.stream.0.disposition.default=1\nstreams.stream.0.disposition.forced=0\nstreams.stream.0.tags.language=\"und\"\nformat.size=\"10028\"\nformat.tags.title=\"hello\"\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "ini",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"# ffprobe output\n\n\n\n[streams.stream.0]\nindex=0\n\n[streams.stream.0.disposition]\ndefault=1\nforced=0\n\n[streams.stream.0.tags]\nlanguage=und\n\n[format]\nsize=10028\n\n[format.tags]\ntitle=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "json",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"{\n    \"programs\": [\n\n    ],\n    \"stream_groups\": [\n\n    ],\n    \"streams\": [\n        {\n            \"index\": 0,\n            \"disposition\": {\n                \"default\": 1,\n                \"forced\": 0\n            },\n            \"tags\": {\n                \"language\": \"und\"\n            }\n        }\n    ],\n    \"format\": {\n        \"size\": \"10028\",\n        \"tags\": {\n            \"title\": \"hello\"\n        }\n    }\n}\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "xml",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe>\n    <programs>\n    </programs>\n\n    <stream_groups>\n    </stream_groups>\n\n    <streams>\n        <stream index=\"0\">\n            <disposition default=\"1\" forced=\"0\"/>\n            <tags>\n                <tag key=\"language\" value=\"und\"/>\n            </tags>\n        </stream>\n    </streams>\n\n    <format size=\"10028\">\n        <tags>\n            <tag key=\"title\" value=\"hello\"/>\n        </tags>\n    </format>\n</ffprobe>\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact=e=csv",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream|index=0|disposition:default=1|disposition:forced=0|tag:language=und\nformat|size=10028|tag:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact=e=none",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream|index=0|disposition:default=1|disposition:forced=0|tag:language=und\nformat|size=10028|tag:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact=p=0",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"index=0|disposition:default=1|disposition:forced=0|tag:language=und\nsize=10028|tag:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact=nk=1",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream|0|1|0|und\nformat|10028|hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "compact=s=@",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream@index=0@disposition:default=1@disposition:forced=0@tag:language=und\nformat@size=10028@tag:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "csv=e=c",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream,0,1,0,und\nformat,10028,hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "default=nk=1",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"[STREAM]\n0\n1\n0\nund\n[/STREAM]\n[FORMAT]\n10028\nhello\n[/FORMAT]\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "default=nw=1",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"index=0\nDISPOSITION:default=1\nDISPOSITION:forced=0\nTAG:language=und\nsize=10028\nTAG:title=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "flat=h=0",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"stream.0.index=0\nstream.0.disposition.default=1\nstream.0.disposition.forced=0\nstream.0.tags.language=\"und\"\nformat.size=\"10028\"\nformat.tags.title=\"hello\"\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "flat=s=#",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"streams#stream#0#index=0\nstreams#stream#0#disposition#default=1\nstreams#stream#0#disposition#forced=0\nstreams#stream#0#tags#language=\"und\"\nformat#size=\"10028\"\nformat#tags#title=\"hello\"\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "ini=h=0",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"# ffprobe output\n\n\n\n[stream.0]\nindex=0\n\n[stream.0.disposition]\ndefault=1\nforced=0\n\n[stream.0.tags]\nlanguage=und\n\n[format]\nsize=10028\n\n[format.tags]\ntitle=hello\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "json=c=1",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"{\n    \"programs\": [\n\n    ],\n    \"stream_groups\": [\n\n    ],\n    \"streams\": [\n        { \"index\": 0,\n            \"disposition\": { \"default\": 1, \"forced\": 0 },\n            \"tags\": { \"language\": \"und\" } }\n    ],\n    \"format\": { \"size\": \"10028\",\n        \"tags\": { \"title\": \"hello\" } }\n}\n",
    },
    Capture {
        scenario: "stream_and_format",
        spec: "xml=q=1",
        args: "-show_entries stream=index:stream_disposition=default,forced:stream_tags=language:format=size:format_tags=title t.mp4",
        bytes: b"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ffprobe:ffprobe xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:ffprobe=\"http://www.ffmpeg.org/schema/ffprobe\" xsi:schemaLocation=\"http://www.ffmpeg.org/schema/ffprobe ffprobe.xsd\">\n    <programs>\n    </programs>\n\n    <stream_groups>\n    </stream_groups>\n\n    <streams>\n        <stream index=\"0\">\n            <disposition default=\"1\" forced=\"0\"/>\n            <tags>\n                <tag key=\"language\" value=\"und\"/>\n            </tags>\n        </stream>\n    </streams>\n\n    <format size=\"10028\">\n        <tags>\n            <tag key=\"title\" value=\"hello\"/>\n        </tags>\n    </format>\n</ffprobe:ffprobe>\n",
    },
];
