//! Generate `crates/model/vaco-pixfmt/src/table.rs` from a family description.
//!
//! Why generate at all: ~270 formats times plane count, four components, five
//! numbers each, subsampling and a flag set is ~1300 lines of data whose errors
//! are silent. A wrong `offset` on `bgr565be` does not fail to compile — it
//! corrupts one conversion path and shows up months later. Generating from
//! families makes the *shape* the reviewable artefact, and `--check` makes an
//! edit to the table impossible to land.
//!
//! `cargo xtask gen-pixfmt`          writes the table.
//! `cargo xtask gen-pixfmt --check`  fails if the committed table is stale.

mod expand;
mod model;
mod source;

use crate::{Task, repo_root};
use model::{Flag, Format};
use std::io::Write;
use std::process::{Command, Stdio};

const DEST: &str = "crates/model/vaco-pixfmt/src/table.rs";

pub fn run(check: bool) -> Task {
    let formats = expand::expand();
    expand::validate(&formats);
    let text = rustfmt(&emit(&formats))?;

    let dest = repo_root().join(DEST);
    if check {
        let current = std::fs::read_to_string(&dest).unwrap_or_default();
        if current != text {
            return Err(format!(
                "{DEST} is stale; run `cargo xtask gen-pixfmt`\n  \
                 (committed {} bytes, generated {} bytes)",
                current.len(),
                text.len()
            ));
        }
        println!("gen-pixfmt --check: up to date ({} formats)", formats.len());
    } else {
        if let Some(p) = dest.parent() {
            std::fs::create_dir_all(p).map_err(|e| e.to_string())?;
        }
        std::fs::write(&dest, text).map_err(|e| e.to_string())?;
        println!("gen-pixfmt: wrote {} formats to {DEST}", formats.len());
    }
    Ok(())
}

/// Pipe the emitted text through `rustfmt`.
///
/// Without this the committed table would fail `cargo fmt --check`, and every
/// contributor would have a formatter that wants to rewrite a generated file.
/// The big tables carry `#[rustfmt::skip]`, so only the surrounding code is
/// touched and the one-row-per-format layout survives.
fn rustfmt(text: &str) -> Result<String, String> {
    let config = repo_root().join("rustfmt.toml");
    let mut child = Command::new("rustfmt")
        .arg("--edition")
        .arg("2024")
        .arg("--config-path")
        .arg(&config)
        .arg("--emit")
        .arg("stdout")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("could not run rustfmt (a pinned toolchain component): {e}"))?;
    child
        .stdin
        .take()
        .ok_or("rustfmt stdin was not piped")?
        .write_all(text.as_bytes())
        .map_err(|e| format!("writing to rustfmt: {e}"))?;
    let out = child
        .wait_with_output()
        .map_err(|e| format!("waiting for rustfmt: {e}"))?;
    if !out.status.success() {
        return Err(format!(
            "rustfmt rejected the generated table:\n{}",
            String::from_utf8_lossy(&out.stderr)
        ));
    }
    String::from_utf8(out.stdout).map_err(|e| format!("rustfmt emitted non-UTF-8: {e}"))
}

fn flag_expr(flags: &[Flag]) -> String {
    match flags {
        [] => "F::empty()".to_string(),
        [one] => format!("F::{}", one.ident()),
        [first, rest @ ..] => {
            let mut s = format!("F::{}", first.ident());
            for f in rest {
                s.push_str(&format!(".union(F::{})", f.ident()));
            }
            s
        }
    }
}

fn emit(formats: &[Format]) -> String {
    let n = formats.len();
    let mut s = String::new();

    s.push_str(
        "//! The pixel-format table.\n\
         //!\n\
         //! GENERATED by `cargo xtask gen-pixfmt`. Do not edit; edit\n\
         //! `xtask/src/gen_pixfmt/source.rs` and regenerate. `cargo xtask gen-pixfmt --check`\n\
         //! re-runs the generator in CI and fails if this file has drifted.\n\
         //!\n\
         //! Discriminants are dense and assigned in family-declaration order, so\n\
         //! `fmt as usize` indexes every table below directly. They are ours, never\n\
         //! serialised, and never a compatibility surface — the *names* are.\n\n",
    );
    s.push_str("use crate::{Component, PixFmtDescriptor, PixFmtFlags as F};\n\n");

    // ---- the enum
    s.push_str("/// A pixel format.\n");
    s.push_str("///\n");
    s.push_str("/// Non-exhaustive because the generated table grows; matching exhaustively\n");
    s.push_str("/// on ~270 variants is never the right thing for a caller to do anyway —\n");
    s.push_str("/// query the [`PixFmtDescriptor`] instead.\n");
    s.push_str("#[repr(u16)]\n");
    s.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n");
    s.push_str("#[non_exhaustive]\n");
    s.push_str("pub enum PixFmt {\n");
    for (i, f) in formats.iter().enumerate() {
        s.push_str(&format!("    /// `{}`\n", f.name));
        s.push_str(&format!("    {} = {i},\n", f.variant));
    }
    s.push_str("}\n\n");

    // ---- constructors used only by the table below
    s.push_str(
        "#[allow(clippy::too_many_arguments)]\n\
         const fn d(\n    \
             name: &'static str,\n    \
             components: &'static [Component],\n    \
             planes: u8,\n    \
             log2_chroma_w: u8,\n    \
             log2_chroma_h: u8,\n    \
             bits_per_pixel: u8,\n    \
             flags: F,\n\
         ) -> PixFmtDescriptor {\n    \
             PixFmtDescriptor {\n        \
                 name,\n        components,\n        planes,\n        log2_chroma_w,\n        \
                 log2_chroma_h,\n        bits_per_pixel,\n        flags,\n    }\n}\n\n",
    );
    s.push_str(
        "const fn c(plane: u8, step: u8, offset: u8, shift: u8, depth: u8) -> Component {\n    \
             Component { plane, step, offset, shift, depth }\n}\n\n",
    );

    // ---- descriptors
    s.push_str("/// Index-aligned with [`PixFmt`]'s discriminants.\n");
    s.push_str("#[rustfmt::skip]\n");
    s.push_str(&format!(
        "pub(crate) static DESCRIPTORS: [PixFmtDescriptor; {n}] = [\n"
    ));
    for f in formats {
        let comps: Vec<String> = f
            .comps
            .iter()
            .map(|c| {
                format!(
                    "c({},{},{},{},{})",
                    c.plane, c.step, c.offset, c.shift, c.depth
                )
            })
            .collect();
        s.push_str(&format!(
            "    d({:?}, &[{}], {}, {}, {}, {}, {}),\n",
            f.name,
            comps.join(","),
            f.planes,
            f.log2_chroma_w,
            f.log2_chroma_h,
            f.bits_per_pixel,
            flag_expr(&f.flags),
        ));
    }
    s.push_str("];\n\n");

    // ---- every format, in discriminant order
    s.push_str("/// Every format, in discriminant order.\n");
    s.push_str("#[rustfmt::skip]\n");
    s.push_str(&format!("pub(crate) static ALL: [PixFmt; {n}] = [\n"));
    for chunk in formats.chunks(4) {
        let row: Vec<String> = chunk
            .iter()
            .map(|f| format!("PixFmt::{}", f.variant))
            .collect();
        s.push_str(&format!("    {},\n", row.join(", ")));
    }
    s.push_str("];\n\n");

    // ---- name lookup
    let mut names: Vec<(String, String)> = Vec::new();
    for f in formats {
        names.push((f.name.clone(), f.variant.clone()));
        for a in &f.aliases {
            names.push((a.clone(), f.variant.clone()));
        }
    }
    names.sort();
    s.push_str(
        "/// Every accepted spelling, sorted, for `binary_search_by_key`. Includes\n\
         /// aliases, so this is longer than [`ALL`].\n",
    );
    s.push_str("#[rustfmt::skip]\n");
    s.push_str(&format!(
        "pub(crate) static NAMES_SORTED: [(&str, PixFmt); {}] = [\n",
        names.len()
    ));
    for (name, variant) in &names {
        s.push_str(&format!("    ({name:?}, PixFmt::{variant}),\n"));
    }
    s.push_str("];\n\n");

    // ---- endianness siblings
    s.push_str(
        "/// The opposite-endianness sibling of each format, where one exists.\n\
         /// Generated as a table rather than searched for at runtime.\n",
    );
    s.push_str("#[rustfmt::skip]\n");
    s.push_str(&format!(
        "pub(crate) static ENDIAN_SWAP: [Option<PixFmt>; {n}] = [\n"
    ));
    for f in formats {
        let entry = match &f.endian_sibling {
            None => "None".to_string(),
            Some(name) => {
                let v = formats
                    .iter()
                    .find(|o| &o.name == name)
                    .map(|o| o.variant.clone())
                    .unwrap_or_default();
                format!("Some(PixFmt::{v})")
            }
        };
        s.push_str(&format!("    {entry},\n"));
    }
    s.push_str("];\n\n");

    s.push_str(&generated_invariants());
    s
}

/// The self-consistency assertions, emitted next to the table so they cannot
/// drift away from it. Every one is a property of the whole table, checked over
/// every entry, rather than a per-format literal that would have to be
/// regenerated in lockstep with the data it checks.
fn generated_invariants() -> String {
    r#"#[cfg(test)]
mod generated_invariants {
    #![expect(
        clippy::indexing_slicing,
        clippy::integer_division,
        reason = "these assertions index tables the generator guarantees are \
                  index-aligned, and recompute an average that is defined as a \
                  truncating division; a failure here is the test doing its job"
    )]

    use super::{ALL, DESCRIPTORS, ENDIAN_SWAP, NAMES_SORTED};
    use crate::PixFmtFlags as F;

    #[test]
    fn discriminants_index_the_table() {
        for (i, fmt) in ALL.iter().enumerate() {
            assert_eq!(*fmt as usize, i, "{} is not at index {i}", fmt.name());
        }
        assert_eq!(ALL.len(), DESCRIPTORS.len());
        assert_eq!(ALL.len(), ENDIAN_SWAP.len());
    }

    #[test]
    fn planes_and_components_agree() {
        for d in &DESCRIPTORS {
            if d.flags.contains(F::HW_ACCEL) {
                assert_eq!(d.planes, 0, "{}: hw surface with planes", d.name);
                assert!(d.components.is_empty(), "{}: hw surface with components", d.name);
                continue;
            }
            assert!(!d.components.is_empty(), "{}: no components", d.name);
            assert!(d.components.len() <= 4, "{}: too many components", d.name);
            let max = d.components.iter().map(|c| c.plane).max().unwrap_or(0);
            assert_eq!(d.planes, max + 1, "{}: plane count disagrees", d.name);
            for p in 0..d.planes {
                assert!(d.components.iter().any(|c| c.plane == p), "{}: plane {p} unused", d.name);
            }
            assert_eq!(
                d.planes > 1,
                d.flags.contains(F::PLANAR),
                "{}: PLANAR flag disagrees with plane count",
                d.name
            );
        }
    }

    #[test]
    fn components_are_well_formed() {
        for d in &DESCRIPTORS {
            for c in d.components {
                assert!(c.depth > 0, "{}: zero depth", d.name);
                assert!(c.depth <= 32, "{}: depth over 32", d.name);
                assert!(u16::from(c.shift) + u16::from(c.depth) <= 32, "{}: field overruns", d.name);
                assert!(c.plane < d.planes, "{}: component outside plane range", d.name);
                if !d.flags.contains(F::BITSTREAM) {
                    let bytes = c.depth.div_ceil(8);
                    assert!(c.step >= bytes, "{}: step smaller than a sample", d.name);
                    // Bounded against the widest step in the plane, which is the
                    // pixel-group stride. Per-component `offset + bytes <= step`
                    // would be tighter but is false for `uyyvyy411`, whose luma
                    // samples are not evenly spaced and are given the tightest
                    // uniform stride that reaches all of them.
                    let group = d
                        .components
                        .iter()
                        .filter(|o| o.plane == c.plane)
                        .map(|o| o.step)
                        .max()
                        .unwrap_or(c.step);
                    assert!(
                        u16::from(c.offset) + u16::from(bytes) <= u16::from(group),
                        "{}: component overruns the pixel group",
                        d.name
                    );
                }
            }
        }
    }

    #[test]
    fn subsampling_is_sane() {
        for d in &DESCRIPTORS {
            assert!(d.log2_chroma_w <= 2, "{}: absurd horizontal subsampling", d.name);
            assert!(d.log2_chroma_h <= 2, "{}: absurd vertical subsampling", d.name);
            if d.flags.contains(F::RGB) || d.flags.contains(F::HW_ACCEL) {
                assert_eq!((d.log2_chroma_w, d.log2_chroma_h), (0, 0), "{}: subsampled RGB", d.name);
            }
        }
    }

    #[test]
    fn alpha_flag_matches_the_layout() {
        for d in &DESCRIPTORS {
            // Palette formats are exempt. A palettised frame stores one component
            // — the index — while its alpha lives in the palette's RGB32 entries,
            // which the component list does not model at all. So ALPHA is set and
            // the component count is 1, and that is correct rather than a
            // contradiction. Confirmed against the reference, which agrees.
            if d.flags.contains(F::PALETTE) {
                continue;
            }
            let has = d.flags.contains(F::ALPHA);
            let n = d.components.len();
            assert_eq!(has, n == 2 || n == 4, "{}: ALPHA flag disagrees with layout", d.name);
        }
    }

    #[test]
    fn bits_per_pixel_matches_the_components() {
        for d in &DESCRIPTORS {
            if d.flags.contains(F::HW_ACCEL) {
                assert_eq!(d.bits_per_pixel, 0);
                continue;
            }
            let block = 1u32 << (d.log2_chroma_w + d.log2_chroma_h);
            let mut bits = 0u32;
            for (i, c) in d.components.iter().enumerate() {
                bits += if i == 1 || i == 2 { u32::from(c.depth) } else { u32::from(c.depth) * block };
            }
            assert_eq!(
                u32::from(d.bits_per_pixel),
                bits / block,
                "{}: bits_per_pixel disagrees with the components",
                d.name
            );
        }
    }

    #[test]
    fn big_endian_needs_a_multi_byte_sample() {
        for d in &DESCRIPTORS {
            if !d.flags.contains(F::BIG_ENDIAN) {
                continue;
            }
            assert!(
                d.components.iter().any(|c| c.step > 1 || c.depth > 8),
                "{}: BE flag on a format with no multi-byte container",
                d.name
            );
        }
    }

    #[test]
    fn endian_siblings_pair_up() {
        for (i, sib) in ENDIAN_SWAP.iter().enumerate() {
            let Some(sib) = *sib else { continue };
            let a = &DESCRIPTORS[i];
            let b = &DESCRIPTORS[sib as usize];
            assert_ne!(sib as usize, i, "{}: is its own sibling", a.name);
            assert_eq!(ENDIAN_SWAP[sib as usize], Some(ALL[i]), "{}: swap is not an involution", a.name);
            assert_eq!(a.components, b.components, "{}: sibling layout differs", a.name);
            assert_eq!(a.planes, b.planes);
            assert_eq!(a.bits_per_pixel, b.bits_per_pixel);
            assert_ne!(
                a.flags.contains(F::BIG_ENDIAN),
                b.flags.contains(F::BIG_ENDIAN),
                "{}: sibling has the same endianness",
                a.name
            );
            assert_eq!(
                a.flags.difference(F::BIG_ENDIAN),
                b.flags.difference(F::BIG_ENDIAN),
                "{}: siblings differ by more than endianness",
                a.name
            );
        }
    }

    #[test]
    fn names_are_sorted_unique_and_complete() {
        for w in NAMES_SORTED.windows(2) {
            assert!(w[0].0 < w[1].0, "name table is not sorted: {} then {}", w[0].0, w[1].0);
        }
        for fmt in &ALL {
            let name = fmt.name();
            assert!(
                NAMES_SORTED.binary_search_by_key(&name, |e| e.0).is_ok(),
                "{name} is missing from the name table"
            );
        }
    }
}
"#
    .to_string()
}
