//! The `AVOption`/`AVClass` equivalent: typed, introspectable option sets.
//!
//! Every configurable component in Vaco — demuxer, muxer, decoder, encoder,
//! filter, protocol, scaler, resampler — declares its options once with
//! `#[derive(Options)]` and gets parsing, validation, serialisation, help data
//! and runtime mutation for free.
//!
//! # Why this exists rather than `clap`
//!
//! `FFmpeg`'s command line is not a fixed set of flags. Every codec, format and
//! filter contributes its own private options at runtime, and `-h filter=scale`
//! must enumerate them *without instantiating anything*. So the primary object
//! here is not a parser but a [`Schema`]: static metadata reachable from a type
//! through [`HasSchema`], which no builder-style argument parser can model.
//!
//! # The shape
//!
//! * [`OptBase`] — the 20 value bases, plus [`ArrayDesc`] as an orthogonal
//!   modifier, together covering the inventory's 21 `AVOptionType` values.
//! * [`OptValue`] — implemented by every type usable as a field. Layer-1 crates
//!   implement it for `PixelFormat`, `SampleFormat` and `ChannelLayout`, which
//!   is how this crate names those bases without depending on those crates.
//! * [`OptionDesc`] / [`Schema`] — the static table, generated by the derive.
//! * [`Options`] — the object projection: an indexed, type-erased accessor.
//! * [`OptionsExt`] — every generic operation, written once against
//!   `dyn OptValue`.
//!
//! # Example
//!
//! ```
//! use vaco_opts::{Options, OptionsExt, SerializeFlags};
//!
//! #[derive(Debug, Clone, Options)]
//! #[options(name = "scale", help = "scale the input video")]
//! struct Scale {
//!     #[opt(name = "w", help = "output width", default = 0, range = 0..=8192,
//!           flags(video, filtering))]
//!     width: i32,
//!     #[opt(name = "h", help = "output height", default = 0, range = 0..=8192,
//!           flags(video, filtering))]
//!     height: i32,
//! }
//!
//! let mut s = Scale::default();
//! s.set_from_string("1280:720", "=", ":").unwrap();
//! assert_eq!(s.width, 1280);
//! assert_eq!(s.serialize(SerializeFlags::default()), "w=1280:h=720");
//!
//! // Introspection with no instance in hand:
//! assert_eq!(vaco_opts::schema_of::<Scale>().options.len(), 2);
//! ```
//!
//! # Divergences from plan 11 §6
//!
//! Recorded here because contributors will compare the two:
//!
//! * `Dict`, `escape`, `parse::*` and `Rgba` are specified to live in
//!   `vaco-core`. That crate is still a stub without them, so they live here.
//!   Delete and re-export when it catches up.
//! * `Options::children` returns `Vec<&dyn Options>`, not `&[&dyn Options]`,
//!   which no struct can implement.
//! * `Options::as_dyn`/`as_dyn_mut` are new, and `check_range` is a method on
//!   `Options` rather than a separate `rt::RangeCheck` trait.
//! * [`ParseCtx`] and [`SerCtx`] carry the option's `name`.
//! * `OptValue::BASE` moved to a separate [`OptValueKind`] trait: an associated
//!   const makes a trait non-dyn-compatible, and the plan's `where Self: Sized`
//!   escape hatch is still unstable.
//! * `VideoRate` and `Binary` are newtypes, because `Rational` and `Vec<u8>`
//!   can each carry only one `OptValue` impl.

// The derive macro expands to `::vaco_opts::…` paths; this makes those resolve
// inside this crate's own tests and doctests too.
#[allow(unused_extern_crates)]
extern crate self as vaco_opts;

pub mod desc;
pub mod dict;
pub mod error;
pub mod escape;
pub mod flags;
pub mod help;
pub mod kind;
pub mod macros;
pub mod object;
pub mod parse;
pub mod rt;
pub mod value;

pub use desc::{
    ConstDesc, ConstValue, HasSchema, OptEnumConsts, OptId, OptRangeDisplay, OptionDesc, Schema,
    schema_of,
};
pub use dict::{Dict, DictFlags};
pub use error::OptError;
pub use flags::OptFlags;
pub use help::{HelpEntry, help_entries, help_entries_recursive};
pub use kind::{ArrayDesc, OptBase, OptKind};
pub use object::{Options, OptionsExt, SerializeFlags};
pub use parse::{Binary, Rgba, VideoRate};
pub use value::{
    OptValue, OptValueKind, ParseCtx, SerCtx, parse_flag_bits, parse_integer, serialize_flag_bits,
};

/// `#[derive(CliOptionTable)]` — turn a fieldless enum into a
/// `vaco_cli_core::table::OptDesc` argv-flag table. Lives here because this
/// is where the project's derive-macro infrastructure lives, not because the
/// result has anything to do with `Options`/`OptFlags` — see
/// `vaco_cli_core::table::ArgFlags`'s own doc for why the two flag
/// vocabularies are kept apart.
pub use vaco_opts_derive::CliOptionTable;
/// `#[derive(OptEnum)]` — turn a fieldless enum into a unit of named constants.
pub use vaco_opts_derive::OptEnum;
/// `#[derive(Options)]` — project a struct's fields into an option schema.
pub use vaco_opts_derive::Options;

/// Runtime support for macro expansion. Not a stable surface.
#[doc(hidden)]
pub use rt as __rt;
