//! [`Options`]: the object side of the system, and the blanket extension trait
//! that carries every generic operation.
//!
//! `#[derive(Options)]` generates only the projection — an indexed, type-erased
//! accessor over the struct's fields, plus the static table. All the
//! interesting logic lives here, once, operating on `&mut dyn OptValue` and
//! `&OptionDesc`. That is what keeps the macro small and this code ordinary,
//! unit-testable Rust.

use smallvec::SmallVec;

use crate::{
    Dict, DictFlags, OptError, OptFlags, OptId, OptRangeDisplay, OptValue, OptionDesc, ParseCtx,
    Schema, SerCtx, escape,
};

/// The child indices walked to reach the object owning an option.
///
/// Nesting is one or two deep in practice — a filter with a scaler child, a
/// muxer with a protocol child — so this never allocates on the resolution
/// path, which every `set_str` takes.
type Path = SmallVec<[usize; 4]>;

/// Which options [`OptionsExt::serialize`] should emit.
#[derive(Debug, Clone, Copy, Default)]
pub struct SerializeFlags {
    /// Omit options still at their declared default.
    pub skip_defaults: bool,
    /// Omit options flagged [`OptFlags::DEPRECATED`].
    pub skip_deprecated: bool,
    /// When non-empty, emit only options intersecting these flags.
    pub only: OptFlags,
}

/// An object carrying an option table.
///
/// Object-safe, so components can be held as `dyn Options` — which is how the
/// registry stores heterogeneous demuxers, filters and encoders side by side.
pub trait Options: core::fmt::Debug {
    fn schema(&self) -> &'static Schema;
    fn slot(&self, id: OptId) -> Option<&dyn OptValue>;
    fn slot_mut(&mut self, id: OptId) -> Option<&mut dyn OptValue>;

    /// Upcast. Required because a blanket `impl<T: Options + ?Sized>` cannot
    /// coerce `&T` to `&dyn Options` on its own, and every generic operation
    /// below wants to recurse through children as trait objects.
    fn as_dyn(&self) -> &dyn Options;
    fn as_dyn_mut(&mut self) -> &mut dyn Options;

    /// Child objects, for recursive option lookup.
    ///
    /// Plan 11 §6.3 writes this as `-> &[&dyn Options]`, which no struct can
    /// implement: it would have to return a reference to a temporary. `Vec` is
    /// the same shape as the already-`Vec` `children_mut`.
    fn children(&self) -> Vec<&dyn Options> {
        Vec::new()
    }

    fn children_mut(&mut self) -> Vec<&mut dyn Options> {
        Vec::new()
    }

    /// A fresh instance at declared defaults, for `is_set_to_default` and for
    /// `skip_defaults` serialisation.
    fn defaults(&self) -> Box<dyn Options>;

    /// The typed, exact range check for one option.
    ///
    /// Generated by the derive. It is a method on `Options` rather than the
    /// separate `rt::RangeCheck` trait plan 11 §6.5 sketches, because
    /// [`OptionsExt::set_str`] only ever holds a `dyn Options` and could not
    /// reach a non-supertrait.
    ///
    /// # Errors
    ///
    /// [`OptError::OutOfRange`] when the option's value falls outside its
    /// declared range.
    fn check_range(&self, id: OptId) -> Result<(), OptError> {
        let _ = id;
        Ok(())
    }
}

// ------------------------------------------------------------------ resolution

/// Find `name` here or, depth first, in the children, recording the child
/// indices walked.
fn find_path(obj: &dyn Options, name: &str, path: &mut Path) -> Option<&'static OptionDesc> {
    if let Some(d) = obj.schema().find(name) {
        return Some(d);
    }
    for (i, c) in obj.children().into_iter().enumerate() {
        path.push(i);
        if let Some(d) = find_path(c, name, path) {
            return Some(d);
        }
        path.pop();
    }
    None
}

fn descend<'a>(obj: &'a dyn Options, path: &[usize]) -> Option<&'a dyn Options> {
    let mut cur = obj;
    for &i in path {
        cur = cur.children().into_iter().nth(i)?;
    }
    Some(cur)
}

fn descend_mut<'a>(obj: &'a mut dyn Options, path: &[usize]) -> Option<&'a mut dyn Options> {
    let mut cur = obj;
    for &i in path {
        // Move `cur` out first so the reborrow keeps the full outer lifetime.
        let tmp = cur;
        cur = tmp.children_mut().into_iter().nth(i)?;
    }
    Some(cur)
}

fn parse_ctx(desc: &OptionDesc) -> ParseCtx<'_> {
    ParseCtx {
        name: desc.name,
        consts: desc.consts,
        unit: desc.unit,
        range: desc.range,
        array: desc.kind.array,
    }
}

fn ser_ctx(desc: &OptionDesc) -> SerCtx<'_> {
    SerCtx {
        name: desc.name,
        consts: desc.consts,
        unit: desc.unit,
        array: desc.kind.array,
    }
}

/// Parse `value` into `desc`'s slot on `obj`, rolling the slot back if either
/// the parse or the typed range check fails.
///
/// The rollback is what makes "a rejected value leaves the object unmodified"
/// an invariant rather than a hope.
fn apply_value(
    obj: &mut dyn Options,
    desc: &'static OptionDesc,
    value: &str,
) -> Result<(), OptError> {
    let backup = match obj.slot(desc.id) {
        Some(s) => s.clone_box(),
        None => return Err(OptError::not_found(desc.name)),
    };
    {
        let Some(slot) = obj.slot_mut(desc.id) else {
            return Err(OptError::not_found(desc.name));
        };
        if let Err(e) = slot.parse_into(value, &parse_ctx(desc)) {
            slot.assign_from(&*backup);
            return Err(e);
        }
    }
    if let Err(e) = obj.check_range(desc.id) {
        if let Some(slot) = obj.slot_mut(desc.id) {
            slot.assign_from(&*backup);
        }
        return Err(e);
    }
    Ok(())
}

fn escape_err(name: &str, e: &escape::EscapeError) -> OptError {
    OptError::Escape {
        name: name.to_owned(),
        detail: e.to_string(),
    }
}

// ------------------------------------------------------------------ extension

/// Every generic option operation. Available on all [`Options`] implementors
/// and on `dyn Options`.
pub trait OptionsExt: Options {
    /// Set by name from a string, recursing into child objects.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`] for an unknown name, [`OptError::ReadOnly`] for a
    /// read-only option, or whatever the value's parser rejects it with.
    fn set_str(&mut self, name: &str, value: &str) -> Result<(), OptError> {
        let mut path = Path::new();
        let obj = self.as_dyn_mut();
        let Some(desc) = find_path(obj, name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        if desc.flags.contains(OptFlags::READONLY) {
            return Err(OptError::ReadOnly {
                name: name.to_owned(),
            });
        }
        let Some(target) = descend_mut(obj, &path) else {
            return Err(OptError::not_found(name));
        };
        apply_value(target, desc, value)
    }

    /// Render an option's current value in canonical form.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`] for an unknown name.
    fn get_str(&self, name: &str) -> Result<String, OptError> {
        let mut path = Path::new();
        let obj = self.as_dyn();
        let Some(desc) = find_path(obj, name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        let Some(target) = descend(obj, &path) else {
            return Err(OptError::not_found(name));
        };
        let Some(slot) = target.slot(desc.id) else {
            return Err(OptError::not_found(name));
        };
        let mut out = String::new();
        slot.serialize(&mut out, &ser_ctx(desc));
        Ok(out)
    }

    /// The typed fast path. Bypasses parsing entirely; still range-checked.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`], [`OptError::ReadOnly`],
    /// [`OptError::TypeMismatch`] when `T` is not the field's type, or
    /// [`OptError::OutOfRange`].
    fn set_typed<T: OptValue + Clone>(&mut self, name: &str, v: T) -> Result<(), OptError> {
        let mut path = Path::new();
        let obj = self.as_dyn_mut();
        let Some(desc) = find_path(obj, name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        if desc.flags.contains(OptFlags::READONLY) {
            return Err(OptError::ReadOnly {
                name: name.to_owned(),
            });
        }
        let Some(target) = descend_mut(obj, &path) else {
            return Err(OptError::not_found(name));
        };
        let backup = match target.slot(desc.id) {
            Some(s) => s.clone_box(),
            None => return Err(OptError::not_found(name)),
        };
        {
            let Some(slot) = target.slot_mut(desc.id) else {
                return Err(OptError::not_found(name));
            };
            if !slot.assign_from(&v) {
                return Err(OptError::TypeMismatch {
                    name: name.to_owned(),
                });
            }
        }
        if let Err(e) = target.check_range(desc.id) {
            if let Some(slot) = target.slot_mut(desc.id) {
                slot.assign_from(&*backup);
            }
            return Err(e);
        }
        Ok(())
    }

    /// The typed read.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`], or [`OptError::TypeMismatch`] when `T` is not the
    /// field's type.
    fn get_typed<T: OptValue + Clone>(&self, name: &str) -> Result<T, OptError> {
        let mut path = Path::new();
        let obj = self.as_dyn();
        let Some(desc) = find_path(obj, name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        let Some(target) = descend(obj, &path) else {
            return Err(OptError::not_found(name));
        };
        let Some(slot) = target.slot(desc.id) else {
            return Err(OptError::not_found(name));
        };
        slot.as_any()
            .downcast_ref::<T>()
            .cloned()
            .ok_or_else(|| OptError::TypeMismatch {
                name: name.to_owned(),
            })
    }

    /// Parse the filter/protocol/muxer argument grammar, `k=v:k2=v2`.
    ///
    /// Values before the first `=` are positional and map to declaration order;
    /// a positional value after a named one is an error, exactly as in the
    /// filtergraph grammar.
    ///
    /// # Errors
    ///
    /// [`OptError::Escape`] for malformed escaping,
    /// [`OptError::TooManyPositional`] or [`OptError::PositionalAfterNamed`]
    /// for a positional-argument mistake, plus anything `set_str` returns.
    fn set_from_string(&mut self, s: &str, kv: &str, pairs: &str) -> Result<(), OptError> {
        let schema = self.schema();
        let class = schema.class_name;
        let items = escape::split_raw(s, pairs).map_err(|e| escape_err(class, &e))?;
        let mut positional = 0usize;
        let mut seen_named = false;
        for item in items {
            if item.is_empty() {
                continue;
            }
            if let Some((k, v)) =
                escape::split_once_raw(item, kv).map_err(|e| escape_err(class, &e))?
            {
                seen_named = true;
                let key = escape::unescape(k).map_err(|e| escape_err(class, &e))?;
                let val = escape::unescape(v).map_err(|e| escape_err(class, &e))?;
                self.set_str(&key, &val)?;
            } else {
                if seen_named {
                    return Err(OptError::PositionalAfterNamed { class });
                }
                let Some(desc) = schema.options.get(positional) else {
                    return Err(OptError::TooManyPositional { class });
                };
                positional += 1;
                let val = escape::unescape(item).map_err(|e| escape_err(class, &e))?;
                self.set_str(desc.name, &val)?;
            }
        }
        Ok(())
    }

    /// Apply every entry of a dictionary, returning the keys that resolved to
    /// no option.
    ///
    /// Returning the remainder rather than erroring is the contract demuxers
    /// rely on to detect unknown options.
    ///
    /// # Errors
    ///
    /// Whatever `set_str` returns for a key that *did* resolve.
    fn apply_dict(&mut self, d: &Dict) -> Result<Dict, OptError> {
        let mut leftover = Dict::new();
        for (k, v) in d.iter() {
            let mut path = Path::new();
            let known = find_path(self.as_dyn(), k, &mut path).is_some();
            if known {
                self.set_str(k, v)?;
            } else {
                leftover.set_with(k, v, DictFlags::exact());
            }
        }
        Ok(leftover)
    }

    /// The `av_opt_serialize` equivalent. Round-trips through
    /// [`OptionsExt::set_from_string`].
    fn serialize(&self, f: SerializeFlags) -> String {
        self.serialize_with(f, '=', ':')
    }

    /// [`OptionsExt::serialize`] with explicit separators.
    fn serialize_with(&self, f: SerializeFlags, kv: char, pairs: char) -> String {
        let mut out = String::new();
        let mut special = String::new();
        special.push(kv);
        special.push(pairs);
        serialize_into(self.as_dyn(), &mut out, f, kv, pairs, &special);
        out
    }

    /// Whether the option still holds its declared default.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`] for an unknown name.
    fn is_set_to_default(&self, name: &str) -> Result<bool, OptError> {
        let mut path = Path::new();
        let obj = self.as_dyn();
        let Some(desc) = find_path(obj, name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        let defaults = obj.defaults();
        let (Some(here), Some(there)) = (descend(obj, &path), descend(defaults.as_ref(), &path))
        else {
            return Err(OptError::not_found(name));
        };
        let (Some(a), Some(b)) = (here.slot(desc.id), there.slot(desc.id)) else {
            return Err(OptError::not_found(name));
        };
        Ok(a.eq_dyn(b))
    }

    /// The exact rendering of an option's declared default.
    ///
    /// [`OptionDesc::default_repr`] is a best effort computed at macro
    /// expansion time; this walks a real defaults instance and is always right.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`] for an unknown name.
    fn default_repr(&self, name: &str) -> Result<String, OptError> {
        self.as_dyn().defaults().get_str(name)
    }

    /// The display ranges declared for an option.
    ///
    /// # Errors
    ///
    /// [`OptError::NotFound`] for an unknown name.
    fn query_ranges(&self, name: &str) -> Result<Vec<OptRangeDisplay>, OptError> {
        let mut path = Path::new();
        let Some(desc) = find_path(self.as_dyn(), name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        Ok(desc.range.into_iter().collect())
    }

    /// Runtime mutation gate: rejects options without [`OptFlags::RUNTIME`].
    ///
    /// # Errors
    ///
    /// [`OptError::NotRuntime`] when the option lacks the flag, plus anything
    /// `set_str` returns.
    fn process_command(&mut self, name: &str, value: &str) -> Result<(), OptError> {
        let mut path = Path::new();
        let Some(desc) = find_path(self.as_dyn(), name, &mut path) else {
            return Err(OptError::not_found(name));
        };
        if !desc.flags.contains(OptFlags::RUNTIME) {
            return Err(OptError::NotRuntime {
                name: name.to_owned(),
            });
        }
        self.set_str(name, value)
    }
}

impl<T: Options + ?Sized> OptionsExt for T {}

fn serialize_into(
    obj: &dyn Options,
    out: &mut String,
    f: SerializeFlags,
    kv: char,
    pairs: char,
    special: &str,
) {
    let schema = obj.schema();
    let defaults = if f.skip_defaults {
        Some(obj.defaults())
    } else {
        None
    };
    for desc in schema.options {
        if desc.flags.contains(OptFlags::READONLY) {
            continue;
        }
        if f.skip_deprecated && desc.flags.contains(OptFlags::DEPRECATED) {
            continue;
        }
        if !f.only.is_empty() && !desc.flags.intersects(f.only) {
            continue;
        }
        let Some(slot) = obj.slot(desc.id) else {
            continue;
        };
        if defaults
            .as_ref()
            .is_some_and(|d| d.slot(desc.id).is_some_and(|ds| slot.eq_dyn(ds)))
        {
            continue;
        }
        let mut val = String::new();
        slot.serialize(&mut val, &ser_ctx(desc));
        if !out.is_empty() {
            out.push(pairs);
        }
        out.push_str(&escape::escape(desc.name, special, escape::Mode::Auto));
        out.push(kv);
        out.push_str(&escape::escape(&val, special, escape::Mode::Auto));
    }
    for c in obj.children() {
        serialize_into(c, out, f, kv, pairs, special);
    }
}
