//! Bit-allocation model constants. ATSC A/52:2018 Annex A.
//!
//! **Confidence caveat, load-bearing for anyone extending this crate**: the
//! primary specification text was not available in this environment (D7's
//! clean-room policy also rules out reading the reference decoder's source
//! for these), so the values below are reconstructed from the model's
//! well-documented *structure* rather than transcribed from Annex A itself.
//! [`crate::bitalloc`]'s own doc comment explains why that distinction
//! matters here specifically: a masking-curve constant even slightly off
//! desyncs mantissa decoding rather than merely degrading quality, so
//! "structurally right" is not the same claim as "bit-exact," and this file
//! is the latter's weakest link. The follow-up is to get a primary or
//! independently-transcribed copy of Annex A's tables and diff them against
//! this file.
//!
//! `BNDSZ`'s 50 entries and `HTH`'s 150 sum well past the `provenance-check`
//! threshold; both carry a `[[table]]` row in `provenance/vaco-codec-ac3.toml`
//! recording exactly this — `method = "derived"`, not `"transcribed"`.
//!
//! Every table-building `const` block below indexes fixed-size arrays with a
//! loop counter statically bounded by the loop condition, so the indexing
//! and casts clippy's `indexing_slicing`/`cast_*` lints flag here cannot
//! actually panic or lose data; `.get()` is not const-friendly inside these
//! blocks (the compiler's own suggestion says so), so the lints are silenced
//! at each item instead of worked around.

/// Band sizes (in spectral bins) for the model's 50 fixed masking bands,
/// generated by a smooth non-decreasing progression rather than transcribed
/// (see module docs): band widths start at 1 bin and roughly double every
/// few bands, which is the qualitative shape the standard describes
/// (fine resolution at low frequencies, coarser at high). Sums to 253 bins,
/// the maximum a 512-sample transform's coefficient count implies.
pub const BNDSZ: [u16; 50] = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
    3, 6, 6, 6, 6, 6, 6, 6, 12, 12, 12, 12, 12, 12, 12, 24, 24, 24,
];

/// Log-domain addition correction, indexed by the (clamped, 0..=255) gap
/// between two power values already in `psd`'s 128-units-per-6dB scale.
/// Approximated as a monotonic, bounded smoothing ramp with the right
/// endpoints (`latab[0]` largest, decaying to `0` as the gap grows) — the
/// *shape* log-domain addition must have, not a transcription of the
/// standard's own rounding of that function.
#[allow(
    clippy::indexing_slicing,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::integer_division,
    reason = "loop counter is statically bounded by the while condition; see module docs"
)]
pub const LATAB: [u8; 256] = {
    let mut t = [0u8; 256];
    let mut i = 0usize;
    while i < 256 {
        // A steep-then-flat ramp: two power values less than ~2 units (12dB)
        // apart get a real correction, further apart get essentially none —
        // the qualitative behaviour of log-domain addition.
        let gap = i as u32;
        t[i] = if gap >= 32 { 0 } else { (32 - gap) as u8 / 4 };
        i += 1;
    }
    t
};

/// Hearing-threshold table, `[fscod][band]`, in the same 128-units-per-6dB
/// scale as `psd`. Approximated as a broad U-shape (higher threshold — less
/// audible — at the spectrum's extremes, lowest in the 2-5 kHz region),
/// since the standard's absolute threshold-of-hearing curve has that
/// qualitative shape at every sample rate; the per-band breakpoints are not
/// independently verified.
#[allow(
    clippy::indexing_slicing,
    clippy::cast_possible_wrap,
    clippy::cast_possible_truncation,
    reason = "loop counters are statically bounded by the while conditions; see module docs"
)]
pub const HTH: [[i16; 50]; 3] = {
    let mut t = [[0i16; 50]; 3];
    let mut fscod = 0usize;
    while fscod < 3 {
        let mut band = 0usize;
        while band < 50 {
            let centered = band.abs_diff(12);
            t[fscod][band] = -600 + (centered as i16) * 40;
            band += 1;
        }
        fscod += 1;
    }
    t
};

/// Fast/slow decay and gain, dB-per-band-step and dB-offset respectively,
/// indexed by the 2-bit `*decaycod`/`*gaincod` BSI/audblk fields. Ordered so
/// a higher code decays faster / gains more, matching the fields' own
/// monotonic naming; absolute dB values are a reasonable AC-3-scale
/// approximation, not transcribed.
pub const FASTDECAY: [u8; 4] = [10, 15, 20, 30];
pub const SLOWDECAY: [u8; 4] = [5, 7, 10, 15];
pub const FASTGAIN: [u8; 8] = [0, 16, 32, 48, 64, 80, 96, 112];
pub const SLOWGAIN: [u8; 4] = [64, 96, 128, 160];
pub const DBKNEE: [u8; 4] = [24, 32, 40, 48];
pub const FLOOR: [i16; 8] = [-800, -700, -600, -500, -400, -300, -200, -9999];

/// SNR (in the 32-units-per-dB scale [`crate::bitalloc::compute_bap`] shifts
/// into) to `bap`, monotonically non-decreasing. The standard's own table is
/// a fixed lookup; this is a smooth ramp with the same endpoints (`bap=0`
/// at/below the mask, `bap=15` far above it), so it has the right *shape*
/// without claiming to be the exact breakpoints.
#[allow(
    clippy::indexing_slicing,
    clippy::cast_possible_truncation,
    clippy::integer_division,
    reason = "loop counter is statically bounded by the while condition; see module docs"
)]
pub const BAPTAB: [u8; 64] = {
    let mut t = [0u8; 64];
    let mut i = 0usize;
    while i < 64 {
        let v = if i < 4 { 0 } else { ((i - 4) * 15 / 60) as u8 };
        t[i] = if v > 15 { 15 } else { v };
        i += 1;
    }
    t
};
