//! The pixel-format table.
//!
//! GENERATED by `cargo xtask gen-pixfmt`. Do not edit; edit
//! `xtask/src/gen_pixfmt/source.rs` and regenerate. `cargo xtask gen-pixfmt --check`
//! re-runs the generator in CI and fails if this file has drifted.
//!
//! Discriminants are dense and assigned in family-declaration order, so
//! `fmt as usize` indexes every table below directly. They are ours, never
//! serialised, and never a compatibility surface — the *names* are.

use crate::{Component, PixFmtDescriptor, PixFmtFlags as F};

/// A pixel format.
///
/// Non-exhaustive because the generated table grows; matching exhaustively
/// on ~270 variants is never the right thing for a caller to do anyway —
/// query the [`PixFmtDescriptor`] instead.
#[repr(u16)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
#[non_exhaustive]
pub enum PixFmt {
    /// `yuv410p`
    Yuv410p = 0,
    /// `yuv411p`
    Yuv411p = 1,
    /// `yuv420p`
    Yuv420p = 2,
    /// `yuv422p`
    Yuv422p = 3,
    /// `yuv440p`
    Yuv440p = 4,
    /// `yuv444p`
    Yuv444p = 5,
    /// `yuvj411p`
    Yuvj411p = 6,
    /// `yuvj420p`
    Yuvj420p = 7,
    /// `yuvj422p`
    Yuvj422p = 8,
    /// `yuvj440p`
    Yuvj440p = 9,
    /// `yuvj444p`
    Yuvj444p = 10,
    /// `yuva420p`
    Yuva420p = 11,
    /// `yuva422p`
    Yuva422p = 12,
    /// `yuva444p`
    Yuva444p = 13,
    /// `yuv420p9le`
    Yuv420p9le = 14,
    /// `yuv420p9be`
    Yuv420p9be = 15,
    /// `yuv420p10le`
    Yuv420p10le = 16,
    /// `yuv420p10be`
    Yuv420p10be = 17,
    /// `yuv420p12le`
    Yuv420p12le = 18,
    /// `yuv420p12be`
    Yuv420p12be = 19,
    /// `yuv420p14le`
    Yuv420p14le = 20,
    /// `yuv420p14be`
    Yuv420p14be = 21,
    /// `yuv420p16le`
    Yuv420p16le = 22,
    /// `yuv420p16be`
    Yuv420p16be = 23,
    /// `yuv422p9le`
    Yuv422p9le = 24,
    /// `yuv422p9be`
    Yuv422p9be = 25,
    /// `yuv422p10le`
    Yuv422p10le = 26,
    /// `yuv422p10be`
    Yuv422p10be = 27,
    /// `yuv422p12le`
    Yuv422p12le = 28,
    /// `yuv422p12be`
    Yuv422p12be = 29,
    /// `yuv422p14le`
    Yuv422p14le = 30,
    /// `yuv422p14be`
    Yuv422p14be = 31,
    /// `yuv422p16le`
    Yuv422p16le = 32,
    /// `yuv422p16be`
    Yuv422p16be = 33,
    /// `yuv444p9le`
    Yuv444p9le = 34,
    /// `yuv444p9be`
    Yuv444p9be = 35,
    /// `yuv444p10le`
    Yuv444p10le = 36,
    /// `yuv444p10be`
    Yuv444p10be = 37,
    /// `yuv444p12le`
    Yuv444p12le = 38,
    /// `yuv444p12be`
    Yuv444p12be = 39,
    /// `yuv444p14le`
    Yuv444p14le = 40,
    /// `yuv444p14be`
    Yuv444p14be = 41,
    /// `yuv444p16le`
    Yuv444p16le = 42,
    /// `yuv444p16be`
    Yuv444p16be = 43,
    /// `yuv440p10le`
    Yuv440p10le = 44,
    /// `yuv440p10be`
    Yuv440p10be = 45,
    /// `yuv440p12le`
    Yuv440p12le = 46,
    /// `yuv440p12be`
    Yuv440p12be = 47,
    /// `yuv444p10msble`
    Yuv444p10msble = 48,
    /// `yuv444p10msbbe`
    Yuv444p10msbbe = 49,
    /// `yuv444p12msble`
    Yuv444p12msble = 50,
    /// `yuv444p12msbbe`
    Yuv444p12msbbe = 51,
    /// `yuva420p9le`
    Yuva420p9le = 52,
    /// `yuva420p9be`
    Yuva420p9be = 53,
    /// `yuva420p10le`
    Yuva420p10le = 54,
    /// `yuva420p10be`
    Yuva420p10be = 55,
    /// `yuva420p16le`
    Yuva420p16le = 56,
    /// `yuva420p16be`
    Yuva420p16be = 57,
    /// `yuva422p9le`
    Yuva422p9le = 58,
    /// `yuva422p9be`
    Yuva422p9be = 59,
    /// `yuva422p10le`
    Yuva422p10le = 60,
    /// `yuva422p10be`
    Yuva422p10be = 61,
    /// `yuva422p12le`
    Yuva422p12le = 62,
    /// `yuva422p12be`
    Yuva422p12be = 63,
    /// `yuva422p16le`
    Yuva422p16le = 64,
    /// `yuva422p16be`
    Yuva422p16be = 65,
    /// `yuva444p9le`
    Yuva444p9le = 66,
    /// `yuva444p9be`
    Yuva444p9be = 67,
    /// `yuva444p10le`
    Yuva444p10le = 68,
    /// `yuva444p10be`
    Yuva444p10be = 69,
    /// `yuva444p12le`
    Yuva444p12le = 70,
    /// `yuva444p12be`
    Yuva444p12be = 71,
    /// `yuva444p16le`
    Yuva444p16le = 72,
    /// `yuva444p16be`
    Yuva444p16be = 73,
    /// `gbrp`
    Gbrp = 74,
    /// `gbrap`
    Gbrap = 75,
    /// `gbrp9le`
    Gbrp9le = 76,
    /// `gbrp9be`
    Gbrp9be = 77,
    /// `gbrp10le`
    Gbrp10le = 78,
    /// `gbrp10be`
    Gbrp10be = 79,
    /// `gbrp12le`
    Gbrp12le = 80,
    /// `gbrp12be`
    Gbrp12be = 81,
    /// `gbrp14le`
    Gbrp14le = 82,
    /// `gbrp14be`
    Gbrp14be = 83,
    /// `gbrp16le`
    Gbrp16le = 84,
    /// `gbrp16be`
    Gbrp16be = 85,
    /// `gbrp10msble`
    Gbrp10msble = 86,
    /// `gbrp10msbbe`
    Gbrp10msbbe = 87,
    /// `gbrp12msble`
    Gbrp12msble = 88,
    /// `gbrp12msbbe`
    Gbrp12msbbe = 89,
    /// `gbrap10le`
    Gbrap10le = 90,
    /// `gbrap10be`
    Gbrap10be = 91,
    /// `gbrap12le`
    Gbrap12le = 92,
    /// `gbrap12be`
    Gbrap12be = 93,
    /// `gbrap14le`
    Gbrap14le = 94,
    /// `gbrap14be`
    Gbrap14be = 95,
    /// `gbrap16le`
    Gbrap16le = 96,
    /// `gbrap16be`
    Gbrap16be = 97,
    /// `gbrap32le`
    Gbrap32le = 98,
    /// `gbrap32be`
    Gbrap32be = 99,
    /// `gbrpf16le`
    Gbrpf16le = 100,
    /// `gbrpf16be`
    Gbrpf16be = 101,
    /// `gbrapf16le`
    Gbrapf16le = 102,
    /// `gbrapf16be`
    Gbrapf16be = 103,
    /// `gbrpf32le`
    Gbrpf32le = 104,
    /// `gbrpf32be`
    Gbrpf32be = 105,
    /// `gbrapf32le`
    Gbrapf32le = 106,
    /// `gbrapf32be`
    Gbrapf32be = 107,
    /// `nv12`
    Nv12 = 108,
    /// `nv21`
    Nv21 = 109,
    /// `nv16`
    Nv16 = 110,
    /// `nv24`
    Nv24 = 111,
    /// `nv42`
    Nv42 = 112,
    /// `p010le`
    P010le = 113,
    /// `p010be`
    P010be = 114,
    /// `p012le`
    P012le = 115,
    /// `p012be`
    P012be = 116,
    /// `p016le`
    P016le = 117,
    /// `p016be`
    P016be = 118,
    /// `p210le`
    P210le = 119,
    /// `p210be`
    P210be = 120,
    /// `p212le`
    P212le = 121,
    /// `p212be`
    P212be = 122,
    /// `p216le`
    P216le = 123,
    /// `p216be`
    P216be = 124,
    /// `p410le`
    P410le = 125,
    /// `p410be`
    P410be = 126,
    /// `p412le`
    P412le = 127,
    /// `p412be`
    P412be = 128,
    /// `p416le`
    P416le = 129,
    /// `p416be`
    P416be = 130,
    /// `nv20le`
    Nv20le = 131,
    /// `nv20be`
    Nv20be = 132,
    /// `gray`
    Gray8 = 133,
    /// `ya8`
    Ya8 = 134,
    /// `gray9le`
    Gray9le = 135,
    /// `gray9be`
    Gray9be = 136,
    /// `gray10le`
    Gray10le = 137,
    /// `gray10be`
    Gray10be = 138,
    /// `gray12le`
    Gray12le = 139,
    /// `gray12be`
    Gray12be = 140,
    /// `gray14le`
    Gray14le = 141,
    /// `gray14be`
    Gray14be = 142,
    /// `gray16le`
    Gray16le = 143,
    /// `gray16be`
    Gray16be = 144,
    /// `gray32le`
    Gray32le = 145,
    /// `gray32be`
    Gray32be = 146,
    /// `ya16le`
    Ya16le = 147,
    /// `ya16be`
    Ya16be = 148,
    /// `grayf16le`
    Grayf16le = 149,
    /// `grayf16be`
    Grayf16be = 150,
    /// `yaf16le`
    Yaf16le = 151,
    /// `yaf16be`
    Yaf16be = 152,
    /// `grayf32le`
    Grayf32le = 153,
    /// `grayf32be`
    Grayf32be = 154,
    /// `yaf32le`
    Yaf32le = 155,
    /// `yaf32be`
    Yaf32be = 156,
    /// `rgb24`
    Rgb24 = 157,
    /// `bgr24`
    Bgr24 = 158,
    /// `argb`
    Argb = 159,
    /// `rgba`
    Rgba = 160,
    /// `abgr`
    Abgr = 161,
    /// `bgra`
    Bgra = 162,
    /// `0rgb`
    X0rgb = 163,
    /// `rgb0`
    Rgb0 = 164,
    /// `0bgr`
    X0bgr = 165,
    /// `bgr0`
    Bgr0 = 166,
    /// `rgb8`
    Rgb8 = 167,
    /// `bgr8`
    Bgr8 = 168,
    /// `rgb4_byte`
    Rgb4Byte = 169,
    /// `bgr4_byte`
    Bgr4Byte = 170,
    /// `rgb4`
    Rgb4 = 171,
    /// `bgr4`
    Bgr4 = 172,
    /// `rgb444le`
    Rgb444le = 173,
    /// `rgb444be`
    Rgb444be = 174,
    /// `rgb555le`
    Rgb555le = 175,
    /// `rgb555be`
    Rgb555be = 176,
    /// `rgb565le`
    Rgb565le = 177,
    /// `rgb565be`
    Rgb565be = 178,
    /// `bgr444le`
    Bgr444le = 179,
    /// `bgr444be`
    Bgr444be = 180,
    /// `bgr555le`
    Bgr555le = 181,
    /// `bgr555be`
    Bgr555be = 182,
    /// `bgr565le`
    Bgr565le = 183,
    /// `bgr565be`
    Bgr565be = 184,
    /// `x2rgb10le`
    X2rgb10le = 185,
    /// `x2rgb10be`
    X2rgb10be = 186,
    /// `x2bgr10le`
    X2bgr10le = 187,
    /// `x2bgr10be`
    X2bgr10be = 188,
    /// `rgb48le`
    Rgb48le = 189,
    /// `rgb48be`
    Rgb48be = 190,
    /// `bgr48le`
    Bgr48le = 191,
    /// `bgr48be`
    Bgr48be = 192,
    /// `rgba64le`
    Rgba64le = 193,
    /// `rgba64be`
    Rgba64be = 194,
    /// `bgra64le`
    Bgra64le = 195,
    /// `bgra64be`
    Bgra64be = 196,
    /// `rgb96le`
    Rgb96le = 197,
    /// `rgb96be`
    Rgb96be = 198,
    /// `rgba128le`
    Rgba128le = 199,
    /// `rgba128be`
    Rgba128be = 200,
    /// `rgbf16le`
    Rgbf16le = 201,
    /// `rgbf16be`
    Rgbf16be = 202,
    /// `rgbaf16le`
    Rgbaf16le = 203,
    /// `rgbaf16be`
    Rgbaf16be = 204,
    /// `rgbf32le`
    Rgbf32le = 205,
    /// `rgbf32be`
    Rgbf32be = 206,
    /// `rgbaf32le`
    Rgbaf32le = 207,
    /// `rgbaf32be`
    Rgbaf32be = 208,
    /// `xyz12le`
    Xyz12le = 209,
    /// `xyz12be`
    Xyz12be = 210,
    /// `ayuv`
    Ayuv = 211,
    /// `uyva`
    Uyva = 212,
    /// `vuya`
    Vuya = 213,
    /// `vuyx`
    Vuyx = 214,
    /// `vyu444`
    Vyu444 = 215,
    /// `ayuv64le`
    Ayuv64le = 216,
    /// `ayuv64be`
    Ayuv64be = 217,
    /// `xv30le`
    Xv30le = 218,
    /// `xv30be`
    Xv30be = 219,
    /// `xv36le`
    Xv36le = 220,
    /// `xv36be`
    Xv36be = 221,
    /// `xv48le`
    Xv48le = 222,
    /// `xv48be`
    Xv48be = 223,
    /// `v30xle`
    V30xle = 224,
    /// `v30xbe`
    V30xbe = 225,
    /// `bayer_bggr8`
    BayerBggr8 = 226,
    /// `bayer_rggb8`
    BayerRggb8 = 227,
    /// `bayer_gbrg8`
    BayerGbrg8 = 228,
    /// `bayer_grbg8`
    BayerGrbg8 = 229,
    /// `bayer_bggr16le`
    BayerBggr16le = 230,
    /// `bayer_bggr16be`
    BayerBggr16be = 231,
    /// `bayer_rggb16le`
    BayerRggb16le = 232,
    /// `bayer_rggb16be`
    BayerRggb16be = 233,
    /// `bayer_gbrg16le`
    BayerGbrg16le = 234,
    /// `bayer_gbrg16be`
    BayerGbrg16be = 235,
    /// `bayer_grbg16le`
    BayerGrbg16le = 236,
    /// `bayer_grbg16be`
    BayerGrbg16be = 237,
    /// `yuyv422`
    Yuyv422 = 238,
    /// `uyvy422`
    Uyvy422 = 239,
    /// `yvyu422`
    Yvyu422 = 240,
    /// `uyyvyy411`
    Uyyvyy411 = 241,
    /// `y210le`
    Y210le = 242,
    /// `y210be`
    Y210be = 243,
    /// `y212le`
    Y212le = 244,
    /// `y212be`
    Y212be = 245,
    /// `y216le`
    Y216le = 246,
    /// `y216be`
    Y216be = 247,
    /// `monow`
    MonoWhite = 248,
    /// `monob`
    MonoBlack = 249,
    /// `pal8`
    Pal8 = 250,
    /// `vaapi`
    Vaapi = 251,
    /// `dxva2_vld`
    Dxva2Vld = 252,
    /// `d3d11va_vld`
    D3d11vaVld = 253,
    /// `d3d11`
    D3d11 = 254,
    /// `d3d12`
    D3d12 = 255,
    /// `vdpau`
    Vdpau = 256,
    /// `videotoolbox`
    Videotoolbox = 257,
    /// `cuda`
    Cuda = 258,
    /// `qsv`
    Qsv = 259,
    /// `mmal`
    Mmal = 260,
    /// `mediacodec`
    Mediacodec = 261,
    /// `opencl`
    Opencl = 262,
    /// `drm_prime`
    DrmPrime = 263,
    /// `vulkan`
    Vulkan = 264,
    /// `amf_surface`
    AmfSurface = 265,
    /// `ohcodec`
    Ohcodec = 266,
    /// `cuarray`
    Cuarray = 267,
}

#[allow(clippy::too_many_arguments)]
const fn d(
    name: &'static str,
    components: &'static [Component],
    planes: u8,
    log2_chroma_w: u8,
    log2_chroma_h: u8,
    bits_per_pixel: u8,
    flags: F,
) -> PixFmtDescriptor {
    PixFmtDescriptor {
        name,
        components,
        planes,
        log2_chroma_w,
        log2_chroma_h,
        bits_per_pixel,
        flags,
    }
}

const fn c(plane: u8, step: u8, offset: u8, shift: u8, depth: u8) -> Component {
    Component {
        plane,
        step,
        offset,
        shift,
        depth,
    }
}

/// Index-aligned with [`PixFmt`]'s discriminants.
#[rustfmt::skip]
pub(crate) static DESCRIPTORS: [PixFmtDescriptor; 268] = [
    d("yuv410p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 2, 2, 9, F::PLANAR),
    d("yuv411p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 2, 0, 12, F::PLANAR),
    d("yuv420p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 1, 1, 12, F::PLANAR),
    d("yuv422p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 1, 0, 16, F::PLANAR),
    d("yuv440p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 0, 1, 16, F::PLANAR),
    d("yuv444p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 0, 0, 24, F::PLANAR),
    d("yuvj411p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 2, 0, 12, F::PLANAR),
    d("yuvj420p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 1, 1, 12, F::PLANAR),
    d("yuvj422p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 1, 0, 16, F::PLANAR),
    d("yuvj440p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 0, 1, 16, F::PLANAR),
    d("yuvj444p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8)], 3, 0, 0, 24, F::PLANAR),
    d("yuva420p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8),c(3,1,0,0,8)], 4, 1, 1, 20, F::PLANAR.union(F::ALPHA)),
    d("yuva422p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8),c(3,1,0,0,8)], 4, 1, 0, 24, F::PLANAR.union(F::ALPHA)),
    d("yuva444p", &[c(0,1,0,0,8),c(1,1,0,0,8),c(2,1,0,0,8),c(3,1,0,0,8)], 4, 0, 0, 32, F::PLANAR.union(F::ALPHA)),
    d("yuv420p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 1, 1, 13, F::PLANAR),
    d("yuv420p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 1, 1, 13, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv420p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 1, 1, 15, F::PLANAR),
    d("yuv420p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 1, 1, 15, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv420p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 1, 1, 18, F::PLANAR),
    d("yuv420p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 1, 1, 18, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv420p14le", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 1, 1, 21, F::PLANAR),
    d("yuv420p14be", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 1, 1, 21, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv420p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 1, 1, 24, F::PLANAR),
    d("yuv420p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 1, 1, 24, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv422p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 1, 0, 18, F::PLANAR),
    d("yuv422p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 1, 0, 18, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv422p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 1, 0, 20, F::PLANAR),
    d("yuv422p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 1, 0, 20, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv422p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 1, 0, 24, F::PLANAR),
    d("yuv422p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 1, 0, 24, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv422p14le", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 1, 0, 28, F::PLANAR),
    d("yuv422p14be", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 1, 0, 28, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv422p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 1, 0, 32, F::PLANAR),
    d("yuv422p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 1, 0, 32, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 0, 0, 27, F::PLANAR),
    d("yuv444p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9)], 3, 0, 0, 27, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 0, 0, 30, F::PLANAR),
    d("yuv444p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 0, 0, 30, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 0, 0, 36, F::PLANAR),
    d("yuv444p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p14le", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 0, 0, 42, F::PLANAR),
    d("yuv444p14be", &[c(0,2,0,0,14),c(1,2,0,0,14),c(2,2,0,0,14)], 3, 0, 0, 42, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 0, 0, 48, F::PLANAR),
    d("yuv444p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16)], 3, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv440p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 0, 1, 20, F::PLANAR),
    d("yuv440p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10)], 3, 0, 1, 20, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv440p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 0, 1, 24, F::PLANAR),
    d("yuv440p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12)], 3, 0, 1, 24, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p10msble", &[c(0,2,0,6,10),c(1,2,0,6,10),c(2,2,0,6,10)], 3, 0, 0, 30, F::PLANAR),
    d("yuv444p10msbbe", &[c(0,2,0,6,10),c(1,2,0,6,10),c(2,2,0,6,10)], 3, 0, 0, 30, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuv444p12msble", &[c(0,2,0,4,12),c(1,2,0,4,12),c(2,2,0,4,12)], 3, 0, 0, 36, F::PLANAR),
    d("yuv444p12msbbe", &[c(0,2,0,4,12),c(1,2,0,4,12),c(2,2,0,4,12)], 3, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR)),
    d("yuva420p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 1, 1, 22, F::PLANAR.union(F::ALPHA)),
    d("yuva420p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 1, 1, 22, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva420p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 1, 1, 25, F::PLANAR.union(F::ALPHA)),
    d("yuva420p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 1, 1, 25, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva420p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 1, 1, 40, F::PLANAR.union(F::ALPHA)),
    d("yuva420p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 1, 1, 40, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva422p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 1, 0, 27, F::PLANAR.union(F::ALPHA)),
    d("yuva422p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 1, 0, 27, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva422p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 1, 0, 30, F::PLANAR.union(F::ALPHA)),
    d("yuva422p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 1, 0, 30, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva422p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12),c(3,2,0,0,12)], 4, 1, 0, 36, F::PLANAR.union(F::ALPHA)),
    d("yuva422p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12),c(3,2,0,0,12)], 4, 1, 0, 36, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva422p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 1, 0, 48, F::PLANAR.union(F::ALPHA)),
    d("yuva422p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 1, 0, 48, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva444p9le", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 0, 0, 36, F::PLANAR.union(F::ALPHA)),
    d("yuva444p9be", &[c(0,2,0,0,9),c(1,2,0,0,9),c(2,2,0,0,9),c(3,2,0,0,9)], 4, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva444p10le", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 0, 0, 40, F::PLANAR.union(F::ALPHA)),
    d("yuva444p10be", &[c(0,2,0,0,10),c(1,2,0,0,10),c(2,2,0,0,10),c(3,2,0,0,10)], 4, 0, 0, 40, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva444p12le", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12),c(3,2,0,0,12)], 4, 0, 0, 48, F::PLANAR.union(F::ALPHA)),
    d("yuva444p12be", &[c(0,2,0,0,12),c(1,2,0,0,12),c(2,2,0,0,12),c(3,2,0,0,12)], 4, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("yuva444p16le", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::PLANAR.union(F::ALPHA)),
    d("yuva444p16be", &[c(0,2,0,0,16),c(1,2,0,0,16),c(2,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::BIG_ENDIAN.union(F::PLANAR).union(F::ALPHA)),
    d("gbrp", &[c(2,1,0,0,8),c(0,1,0,0,8),c(1,1,0,0,8)], 3, 0, 0, 24, F::PLANAR.union(F::RGB)),
    d("gbrap", &[c(2,1,0,0,8),c(0,1,0,0,8),c(1,1,0,0,8),c(3,1,0,0,8)], 4, 0, 0, 32, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrp9le", &[c(2,2,0,0,9),c(0,2,0,0,9),c(1,2,0,0,9)], 3, 0, 0, 27, F::PLANAR.union(F::RGB)),
    d("gbrp9be", &[c(2,2,0,0,9),c(0,2,0,0,9),c(1,2,0,0,9)], 3, 0, 0, 27, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp10le", &[c(2,2,0,0,10),c(0,2,0,0,10),c(1,2,0,0,10)], 3, 0, 0, 30, F::PLANAR.union(F::RGB)),
    d("gbrp10be", &[c(2,2,0,0,10),c(0,2,0,0,10),c(1,2,0,0,10)], 3, 0, 0, 30, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp12le", &[c(2,2,0,0,12),c(0,2,0,0,12),c(1,2,0,0,12)], 3, 0, 0, 36, F::PLANAR.union(F::RGB)),
    d("gbrp12be", &[c(2,2,0,0,12),c(0,2,0,0,12),c(1,2,0,0,12)], 3, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp14le", &[c(2,2,0,0,14),c(0,2,0,0,14),c(1,2,0,0,14)], 3, 0, 0, 42, F::PLANAR.union(F::RGB)),
    d("gbrp14be", &[c(2,2,0,0,14),c(0,2,0,0,14),c(1,2,0,0,14)], 3, 0, 0, 42, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp16le", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16)], 3, 0, 0, 48, F::PLANAR.union(F::RGB)),
    d("gbrp16be", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16)], 3, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp10msble", &[c(2,2,0,6,10),c(0,2,0,6,10),c(1,2,0,6,10)], 3, 0, 0, 30, F::PLANAR.union(F::RGB)),
    d("gbrp10msbbe", &[c(2,2,0,6,10),c(0,2,0,6,10),c(1,2,0,6,10)], 3, 0, 0, 30, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrp12msble", &[c(2,2,0,4,12),c(0,2,0,4,12),c(1,2,0,4,12)], 3, 0, 0, 36, F::PLANAR.union(F::RGB)),
    d("gbrp12msbbe", &[c(2,2,0,4,12),c(0,2,0,4,12),c(1,2,0,4,12)], 3, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB)),
    d("gbrap10le", &[c(2,2,0,0,10),c(0,2,0,0,10),c(1,2,0,0,10),c(3,2,0,0,10)], 4, 0, 0, 40, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrap10be", &[c(2,2,0,0,10),c(0,2,0,0,10),c(1,2,0,0,10),c(3,2,0,0,10)], 4, 0, 0, 40, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA)),
    d("gbrap12le", &[c(2,2,0,0,12),c(0,2,0,0,12),c(1,2,0,0,12),c(3,2,0,0,12)], 4, 0, 0, 48, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrap12be", &[c(2,2,0,0,12),c(0,2,0,0,12),c(1,2,0,0,12),c(3,2,0,0,12)], 4, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA)),
    d("gbrap14le", &[c(2,2,0,0,14),c(0,2,0,0,14),c(1,2,0,0,14),c(3,2,0,0,14)], 4, 0, 0, 56, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrap14be", &[c(2,2,0,0,14),c(0,2,0,0,14),c(1,2,0,0,14),c(3,2,0,0,14)], 4, 0, 0, 56, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA)),
    d("gbrap16le", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrap16be", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA)),
    d("gbrap32le", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32),c(3,4,0,0,32)], 4, 0, 0, 128, F::PLANAR.union(F::RGB).union(F::ALPHA)),
    d("gbrap32be", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32),c(3,4,0,0,32)], 4, 0, 0, 128, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA)),
    d("gbrpf16le", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16)], 3, 0, 0, 48, F::PLANAR.union(F::RGB).union(F::FLOAT)),
    d("gbrpf16be", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16)], 3, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::FLOAT)),
    d("gbrapf16le", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::PLANAR.union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("gbrapf16be", &[c(2,2,0,0,16),c(0,2,0,0,16),c(1,2,0,0,16),c(3,2,0,0,16)], 4, 0, 0, 64, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("gbrpf32le", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32)], 3, 0, 0, 96, F::PLANAR.union(F::RGB).union(F::FLOAT)),
    d("gbrpf32be", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32)], 3, 0, 0, 96, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::FLOAT)),
    d("gbrapf32le", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32),c(3,4,0,0,32)], 4, 0, 0, 128, F::PLANAR.union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("gbrapf32be", &[c(2,4,0,0,32),c(0,4,0,0,32),c(1,4,0,0,32),c(3,4,0,0,32)], 4, 0, 0, 128, F::BIG_ENDIAN.union(F::PLANAR).union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("nv12", &[c(0,1,0,0,8),c(1,2,0,0,8),c(1,2,1,0,8)], 2, 1, 1, 12, F::PLANAR),
    d("nv21", &[c(0,1,0,0,8),c(1,2,1,0,8),c(1,2,0,0,8)], 2, 1, 1, 12, F::PLANAR),
    d("nv16", &[c(0,1,0,0,8),c(1,2,0,0,8),c(1,2,1,0,8)], 2, 1, 0, 16, F::PLANAR),
    d("nv24", &[c(0,1,0,0,8),c(1,2,0,0,8),c(1,2,1,0,8)], 2, 0, 0, 24, F::PLANAR),
    d("nv42", &[c(0,1,0,0,8),c(1,2,1,0,8),c(1,2,0,0,8)], 2, 0, 0, 24, F::PLANAR),
    d("p010le", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 1, 1, 15, F::PLANAR),
    d("p010be", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 1, 1, 15, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p012le", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 1, 1, 18, F::PLANAR),
    d("p012be", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 1, 1, 18, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p016le", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 1, 1, 24, F::PLANAR),
    d("p016be", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 1, 1, 24, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p210le", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 1, 0, 20, F::PLANAR),
    d("p210be", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 1, 0, 20, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p212le", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 1, 0, 24, F::PLANAR),
    d("p212be", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 1, 0, 24, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p216le", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 1, 0, 32, F::PLANAR),
    d("p216be", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 1, 0, 32, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p410le", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 0, 0, 30, F::PLANAR),
    d("p410be", &[c(0,2,0,6,10),c(1,4,0,6,10),c(1,4,2,6,10)], 2, 0, 0, 30, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p412le", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 0, 0, 36, F::PLANAR),
    d("p412be", &[c(0,2,0,4,12),c(1,4,0,4,12),c(1,4,2,4,12)], 2, 0, 0, 36, F::BIG_ENDIAN.union(F::PLANAR)),
    d("p416le", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 0, 0, 48, F::PLANAR),
    d("p416be", &[c(0,2,0,0,16),c(1,4,0,0,16),c(1,4,2,0,16)], 2, 0, 0, 48, F::BIG_ENDIAN.union(F::PLANAR)),
    d("nv20le", &[c(0,2,0,0,10),c(1,4,0,0,10),c(1,4,2,0,10)], 2, 1, 0, 20, F::PLANAR),
    d("nv20be", &[c(0,2,0,0,10),c(1,4,0,0,10),c(1,4,2,0,10)], 2, 1, 0, 20, F::BIG_ENDIAN.union(F::PLANAR)),
    d("gray", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::empty()),
    d("ya8", &[c(0,2,0,0,8),c(0,2,1,0,8)], 1, 0, 0, 16, F::ALPHA),
    d("gray9le", &[c(0,2,0,0,9)], 1, 0, 0, 9, F::empty()),
    d("gray9be", &[c(0,2,0,0,9)], 1, 0, 0, 9, F::BIG_ENDIAN),
    d("gray10le", &[c(0,2,0,0,10)], 1, 0, 0, 10, F::empty()),
    d("gray10be", &[c(0,2,0,0,10)], 1, 0, 0, 10, F::BIG_ENDIAN),
    d("gray12le", &[c(0,2,0,0,12)], 1, 0, 0, 12, F::empty()),
    d("gray12be", &[c(0,2,0,0,12)], 1, 0, 0, 12, F::BIG_ENDIAN),
    d("gray14le", &[c(0,2,0,0,14)], 1, 0, 0, 14, F::empty()),
    d("gray14be", &[c(0,2,0,0,14)], 1, 0, 0, 14, F::BIG_ENDIAN),
    d("gray16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::empty()),
    d("gray16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN),
    d("gray32le", &[c(0,4,0,0,32)], 1, 0, 0, 32, F::empty()),
    d("gray32be", &[c(0,4,0,0,32)], 1, 0, 0, 32, F::BIG_ENDIAN),
    d("ya16le", &[c(0,4,0,0,16),c(0,4,2,0,16)], 1, 0, 0, 32, F::ALPHA),
    d("ya16be", &[c(0,4,0,0,16),c(0,4,2,0,16)], 1, 0, 0, 32, F::BIG_ENDIAN.union(F::ALPHA)),
    d("grayf16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::FLOAT),
    d("grayf16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::FLOAT)),
    d("yaf16le", &[c(0,4,0,0,16),c(0,4,2,0,16)], 1, 0, 0, 32, F::ALPHA.union(F::FLOAT)),
    d("yaf16be", &[c(0,4,0,0,16),c(0,4,2,0,16)], 1, 0, 0, 32, F::BIG_ENDIAN.union(F::ALPHA).union(F::FLOAT)),
    d("grayf32le", &[c(0,4,0,0,32)], 1, 0, 0, 32, F::FLOAT),
    d("grayf32be", &[c(0,4,0,0,32)], 1, 0, 0, 32, F::BIG_ENDIAN.union(F::FLOAT)),
    d("yaf32le", &[c(0,8,0,0,32),c(0,8,4,0,32)], 1, 0, 0, 64, F::ALPHA.union(F::FLOAT)),
    d("yaf32be", &[c(0,8,0,0,32),c(0,8,4,0,32)], 1, 0, 0, 64, F::BIG_ENDIAN.union(F::ALPHA).union(F::FLOAT)),
    d("rgb24", &[c(0,3,0,0,8),c(0,3,1,0,8),c(0,3,2,0,8)], 1, 0, 0, 24, F::RGB),
    d("bgr24", &[c(0,3,2,0,8),c(0,3,1,0,8),c(0,3,0,0,8)], 1, 0, 0, 24, F::RGB),
    d("argb", &[c(0,4,1,0,8),c(0,4,2,0,8),c(0,4,3,0,8),c(0,4,0,0,8)], 1, 0, 0, 32, F::RGB.union(F::ALPHA)),
    d("rgba", &[c(0,4,0,0,8),c(0,4,1,0,8),c(0,4,2,0,8),c(0,4,3,0,8)], 1, 0, 0, 32, F::RGB.union(F::ALPHA)),
    d("abgr", &[c(0,4,3,0,8),c(0,4,2,0,8),c(0,4,1,0,8),c(0,4,0,0,8)], 1, 0, 0, 32, F::RGB.union(F::ALPHA)),
    d("bgra", &[c(0,4,2,0,8),c(0,4,1,0,8),c(0,4,0,0,8),c(0,4,3,0,8)], 1, 0, 0, 32, F::RGB.union(F::ALPHA)),
    d("0rgb", &[c(0,4,1,0,8),c(0,4,2,0,8),c(0,4,3,0,8)], 1, 0, 0, 24, F::RGB),
    d("rgb0", &[c(0,4,0,0,8),c(0,4,1,0,8),c(0,4,2,0,8)], 1, 0, 0, 24, F::RGB),
    d("0bgr", &[c(0,4,3,0,8),c(0,4,2,0,8),c(0,4,1,0,8)], 1, 0, 0, 24, F::RGB),
    d("bgr0", &[c(0,4,2,0,8),c(0,4,1,0,8),c(0,4,0,0,8)], 1, 0, 0, 24, F::RGB),
    d("rgb8", &[c(0,1,0,0,3),c(0,1,0,3,3),c(0,1,0,6,2)], 1, 0, 0, 8, F::RGB),
    d("bgr8", &[c(0,1,0,6,2),c(0,1,0,3,3),c(0,1,0,0,3)], 1, 0, 0, 8, F::RGB),
    d("rgb4_byte", &[c(0,1,0,0,1),c(0,1,0,1,2),c(0,1,0,3,1)], 1, 0, 0, 4, F::RGB),
    d("bgr4_byte", &[c(0,1,0,3,1),c(0,1,0,1,2),c(0,1,0,0,1)], 1, 0, 0, 4, F::RGB),
    d("rgb4", &[c(0,4,0,0,1),c(0,4,0,1,2),c(0,4,0,3,1)], 1, 0, 0, 4, F::BITSTREAM.union(F::RGB)),
    d("bgr4", &[c(0,4,0,3,1),c(0,4,0,1,2),c(0,4,0,0,1)], 1, 0, 0, 4, F::BITSTREAM.union(F::RGB)),
    d("rgb444le", &[c(0,2,0,8,4),c(0,2,0,4,4),c(0,2,0,0,4)], 1, 0, 0, 12, F::RGB),
    d("rgb444be", &[c(0,2,0,8,4),c(0,2,0,4,4),c(0,2,0,0,4)], 1, 0, 0, 12, F::BIG_ENDIAN.union(F::RGB)),
    d("rgb555le", &[c(0,2,0,10,5),c(0,2,0,5,5),c(0,2,0,0,5)], 1, 0, 0, 15, F::RGB),
    d("rgb555be", &[c(0,2,0,10,5),c(0,2,0,5,5),c(0,2,0,0,5)], 1, 0, 0, 15, F::BIG_ENDIAN.union(F::RGB)),
    d("rgb565le", &[c(0,2,0,11,5),c(0,2,0,5,6),c(0,2,0,0,5)], 1, 0, 0, 16, F::RGB),
    d("rgb565be", &[c(0,2,0,11,5),c(0,2,0,5,6),c(0,2,0,0,5)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB)),
    d("bgr444le", &[c(0,2,0,0,4),c(0,2,0,4,4),c(0,2,0,8,4)], 1, 0, 0, 12, F::RGB),
    d("bgr444be", &[c(0,2,0,0,4),c(0,2,0,4,4),c(0,2,0,8,4)], 1, 0, 0, 12, F::BIG_ENDIAN.union(F::RGB)),
    d("bgr555le", &[c(0,2,0,0,5),c(0,2,0,5,5),c(0,2,0,10,5)], 1, 0, 0, 15, F::RGB),
    d("bgr555be", &[c(0,2,0,0,5),c(0,2,0,5,5),c(0,2,0,10,5)], 1, 0, 0, 15, F::BIG_ENDIAN.union(F::RGB)),
    d("bgr565le", &[c(0,2,0,0,5),c(0,2,0,5,6),c(0,2,0,11,5)], 1, 0, 0, 16, F::RGB),
    d("bgr565be", &[c(0,2,0,0,5),c(0,2,0,5,6),c(0,2,0,11,5)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB)),
    d("x2rgb10le", &[c(0,4,0,20,10),c(0,4,0,10,10),c(0,4,0,0,10)], 1, 0, 0, 30, F::RGB),
    d("x2rgb10be", &[c(0,4,0,20,10),c(0,4,0,10,10),c(0,4,0,0,10)], 1, 0, 0, 30, F::BIG_ENDIAN.union(F::RGB)),
    d("x2bgr10le", &[c(0,4,0,0,10),c(0,4,0,10,10),c(0,4,0,20,10)], 1, 0, 0, 30, F::RGB),
    d("x2bgr10be", &[c(0,4,0,0,10),c(0,4,0,10,10),c(0,4,0,20,10)], 1, 0, 0, 30, F::BIG_ENDIAN.union(F::RGB)),
    d("rgb48le", &[c(0,6,0,0,16),c(0,6,2,0,16),c(0,6,4,0,16)], 1, 0, 0, 48, F::RGB),
    d("rgb48be", &[c(0,6,0,0,16),c(0,6,2,0,16),c(0,6,4,0,16)], 1, 0, 0, 48, F::BIG_ENDIAN.union(F::RGB)),
    d("bgr48le", &[c(0,6,4,0,16),c(0,6,2,0,16),c(0,6,0,0,16)], 1, 0, 0, 48, F::RGB),
    d("bgr48be", &[c(0,6,4,0,16),c(0,6,2,0,16),c(0,6,0,0,16)], 1, 0, 0, 48, F::BIG_ENDIAN.union(F::RGB)),
    d("rgba64le", &[c(0,8,0,0,16),c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::RGB.union(F::ALPHA)),
    d("rgba64be", &[c(0,8,0,0,16),c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::BIG_ENDIAN.union(F::RGB).union(F::ALPHA)),
    d("bgra64le", &[c(0,8,4,0,16),c(0,8,2,0,16),c(0,8,0,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::RGB.union(F::ALPHA)),
    d("bgra64be", &[c(0,8,4,0,16),c(0,8,2,0,16),c(0,8,0,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::BIG_ENDIAN.union(F::RGB).union(F::ALPHA)),
    d("rgb96le", &[c(0,12,0,0,32),c(0,12,4,0,32),c(0,12,8,0,32)], 1, 0, 0, 96, F::RGB),
    d("rgb96be", &[c(0,12,0,0,32),c(0,12,4,0,32),c(0,12,8,0,32)], 1, 0, 0, 96, F::BIG_ENDIAN.union(F::RGB)),
    d("rgba128le", &[c(0,16,0,0,32),c(0,16,4,0,32),c(0,16,8,0,32),c(0,16,12,0,32)], 1, 0, 0, 128, F::RGB.union(F::ALPHA)),
    d("rgba128be", &[c(0,16,0,0,32),c(0,16,4,0,32),c(0,16,8,0,32),c(0,16,12,0,32)], 1, 0, 0, 128, F::BIG_ENDIAN.union(F::RGB).union(F::ALPHA)),
    d("rgbf16le", &[c(0,6,0,0,16),c(0,6,2,0,16),c(0,6,4,0,16)], 1, 0, 0, 48, F::RGB.union(F::FLOAT)),
    d("rgbf16be", &[c(0,6,0,0,16),c(0,6,2,0,16),c(0,6,4,0,16)], 1, 0, 0, 48, F::BIG_ENDIAN.union(F::RGB).union(F::FLOAT)),
    d("rgbaf16le", &[c(0,8,0,0,16),c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::RGB.union(F::ALPHA).union(F::FLOAT)),
    d("rgbaf16be", &[c(0,8,0,0,16),c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16)], 1, 0, 0, 64, F::BIG_ENDIAN.union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("rgbf32le", &[c(0,12,0,0,32),c(0,12,4,0,32),c(0,12,8,0,32)], 1, 0, 0, 96, F::RGB.union(F::FLOAT)),
    d("rgbf32be", &[c(0,12,0,0,32),c(0,12,4,0,32),c(0,12,8,0,32)], 1, 0, 0, 96, F::BIG_ENDIAN.union(F::RGB).union(F::FLOAT)),
    d("rgbaf32le", &[c(0,16,0,0,32),c(0,16,4,0,32),c(0,16,8,0,32),c(0,16,12,0,32)], 1, 0, 0, 128, F::RGB.union(F::ALPHA).union(F::FLOAT)),
    d("rgbaf32be", &[c(0,16,0,0,32),c(0,16,4,0,32),c(0,16,8,0,32),c(0,16,12,0,32)], 1, 0, 0, 128, F::BIG_ENDIAN.union(F::RGB).union(F::ALPHA).union(F::FLOAT)),
    d("xyz12le", &[c(0,6,0,4,12),c(0,6,2,4,12),c(0,6,4,4,12)], 1, 0, 0, 36, F::RGB.union(F::XYZ)),
    d("xyz12be", &[c(0,6,0,4,12),c(0,6,2,4,12),c(0,6,4,4,12)], 1, 0, 0, 36, F::BIG_ENDIAN.union(F::RGB).union(F::XYZ)),
    d("ayuv", &[c(0,4,1,0,8),c(0,4,2,0,8),c(0,4,3,0,8),c(0,4,0,0,8)], 1, 0, 0, 32, F::ALPHA),
    d("uyva", &[c(0,4,1,0,8),c(0,4,0,0,8),c(0,4,2,0,8),c(0,4,3,0,8)], 1, 0, 0, 32, F::ALPHA),
    d("vuya", &[c(0,4,2,0,8),c(0,4,1,0,8),c(0,4,0,0,8),c(0,4,3,0,8)], 1, 0, 0, 32, F::ALPHA),
    d("vuyx", &[c(0,4,2,0,8),c(0,4,1,0,8),c(0,4,0,0,8)], 1, 0, 0, 24, F::empty()),
    d("vyu444", &[c(0,3,1,0,8),c(0,3,2,0,8),c(0,3,0,0,8)], 1, 0, 0, 24, F::empty()),
    d("ayuv64le", &[c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16),c(0,8,0,0,16)], 1, 0, 0, 64, F::ALPHA),
    d("ayuv64be", &[c(0,8,2,0,16),c(0,8,4,0,16),c(0,8,6,0,16),c(0,8,0,0,16)], 1, 0, 0, 64, F::BIG_ENDIAN.union(F::ALPHA)),
    d("xv30le", &[c(0,4,0,10,10),c(0,4,0,0,10),c(0,4,0,20,10)], 1, 0, 0, 30, F::empty()),
    d("xv30be", &[c(0,4,0,10,10),c(0,4,0,0,10),c(0,4,0,20,10)], 1, 0, 0, 30, F::BIG_ENDIAN),
    d("xv36le", &[c(0,8,2,4,12),c(0,8,0,4,12),c(0,8,4,4,12)], 1, 0, 0, 36, F::empty()),
    d("xv36be", &[c(0,8,2,4,12),c(0,8,0,4,12),c(0,8,4,4,12)], 1, 0, 0, 36, F::BIG_ENDIAN),
    d("xv48le", &[c(0,8,2,0,16),c(0,8,0,0,16),c(0,8,4,0,16)], 1, 0, 0, 48, F::empty()),
    d("xv48be", &[c(0,8,2,0,16),c(0,8,0,0,16),c(0,8,4,0,16)], 1, 0, 0, 48, F::BIG_ENDIAN),
    d("v30xle", &[c(0,4,0,12,10),c(0,4,0,2,10),c(0,4,0,22,10)], 1, 0, 0, 30, F::empty()),
    d("v30xbe", &[c(0,4,0,12,10),c(0,4,0,2,10),c(0,4,0,22,10)], 1, 0, 0, 30, F::BIG_ENDIAN),
    d("bayer_bggr8", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::RGB.union(F::BAYER)),
    d("bayer_rggb8", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::RGB.union(F::BAYER)),
    d("bayer_gbrg8", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::RGB.union(F::BAYER)),
    d("bayer_grbg8", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::RGB.union(F::BAYER)),
    d("bayer_bggr16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::RGB.union(F::BAYER)),
    d("bayer_bggr16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB).union(F::BAYER)),
    d("bayer_rggb16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::RGB.union(F::BAYER)),
    d("bayer_rggb16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB).union(F::BAYER)),
    d("bayer_gbrg16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::RGB.union(F::BAYER)),
    d("bayer_gbrg16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB).union(F::BAYER)),
    d("bayer_grbg16le", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::RGB.union(F::BAYER)),
    d("bayer_grbg16be", &[c(0,2,0,0,16)], 1, 0, 0, 16, F::BIG_ENDIAN.union(F::RGB).union(F::BAYER)),
    d("yuyv422", &[c(0,2,0,0,8),c(0,4,1,0,8),c(0,4,3,0,8)], 1, 1, 0, 16, F::empty()),
    d("uyvy422", &[c(0,2,1,0,8),c(0,4,0,0,8),c(0,4,2,0,8)], 1, 1, 0, 16, F::empty()),
    d("yvyu422", &[c(0,2,0,0,8),c(0,4,3,0,8),c(0,4,1,0,8)], 1, 1, 0, 16, F::empty()),
    d("uyyvyy411", &[c(0,1,1,0,8),c(0,6,0,0,8),c(0,6,3,0,8)], 1, 2, 0, 12, F::empty()),
    d("y210le", &[c(0,4,0,6,10),c(0,8,2,6,10),c(0,8,6,6,10)], 1, 1, 0, 20, F::empty()),
    d("y210be", &[c(0,4,0,6,10),c(0,8,2,6,10),c(0,8,6,6,10)], 1, 1, 0, 20, F::BIG_ENDIAN),
    d("y212le", &[c(0,4,0,4,12),c(0,8,2,4,12),c(0,8,6,4,12)], 1, 1, 0, 24, F::empty()),
    d("y212be", &[c(0,4,0,4,12),c(0,8,2,4,12),c(0,8,6,4,12)], 1, 1, 0, 24, F::BIG_ENDIAN),
    d("y216le", &[c(0,4,0,0,16),c(0,8,2,0,16),c(0,8,6,0,16)], 1, 1, 0, 32, F::empty()),
    d("y216be", &[c(0,4,0,0,16),c(0,8,2,0,16),c(0,8,6,0,16)], 1, 1, 0, 32, F::BIG_ENDIAN),
    d("monow", &[c(0,1,0,0,1)], 1, 0, 0, 1, F::BITSTREAM),
    d("monob", &[c(0,1,0,0,1)], 1, 0, 0, 1, F::BITSTREAM),
    d("pal8", &[c(0,1,0,0,8)], 1, 0, 0, 8, F::PALETTE),
    d("vaapi", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("dxva2_vld", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("d3d11va_vld", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("d3d11", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("d3d12", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("vdpau", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("videotoolbox", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("cuda", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("qsv", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("mmal", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("mediacodec", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("opencl", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("drm_prime", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("vulkan", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("amf_surface", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("ohcodec", &[], 0, 0, 0, 0, F::HW_ACCEL),
    d("cuarray", &[], 0, 0, 0, 0, F::HW_ACCEL),
];

/// Every format, in discriminant order.
#[rustfmt::skip]
pub(crate) static ALL: [PixFmt; 268] = [
    PixFmt::Yuv410p, PixFmt::Yuv411p, PixFmt::Yuv420p, PixFmt::Yuv422p,
    PixFmt::Yuv440p, PixFmt::Yuv444p, PixFmt::Yuvj411p, PixFmt::Yuvj420p,
    PixFmt::Yuvj422p, PixFmt::Yuvj440p, PixFmt::Yuvj444p, PixFmt::Yuva420p,
    PixFmt::Yuva422p, PixFmt::Yuva444p, PixFmt::Yuv420p9le, PixFmt::Yuv420p9be,
    PixFmt::Yuv420p10le, PixFmt::Yuv420p10be, PixFmt::Yuv420p12le, PixFmt::Yuv420p12be,
    PixFmt::Yuv420p14le, PixFmt::Yuv420p14be, PixFmt::Yuv420p16le, PixFmt::Yuv420p16be,
    PixFmt::Yuv422p9le, PixFmt::Yuv422p9be, PixFmt::Yuv422p10le, PixFmt::Yuv422p10be,
    PixFmt::Yuv422p12le, PixFmt::Yuv422p12be, PixFmt::Yuv422p14le, PixFmt::Yuv422p14be,
    PixFmt::Yuv422p16le, PixFmt::Yuv422p16be, PixFmt::Yuv444p9le, PixFmt::Yuv444p9be,
    PixFmt::Yuv444p10le, PixFmt::Yuv444p10be, PixFmt::Yuv444p12le, PixFmt::Yuv444p12be,
    PixFmt::Yuv444p14le, PixFmt::Yuv444p14be, PixFmt::Yuv444p16le, PixFmt::Yuv444p16be,
    PixFmt::Yuv440p10le, PixFmt::Yuv440p10be, PixFmt::Yuv440p12le, PixFmt::Yuv440p12be,
    PixFmt::Yuv444p10msble, PixFmt::Yuv444p10msbbe, PixFmt::Yuv444p12msble, PixFmt::Yuv444p12msbbe,
    PixFmt::Yuva420p9le, PixFmt::Yuva420p9be, PixFmt::Yuva420p10le, PixFmt::Yuva420p10be,
    PixFmt::Yuva420p16le, PixFmt::Yuva420p16be, PixFmt::Yuva422p9le, PixFmt::Yuva422p9be,
    PixFmt::Yuva422p10le, PixFmt::Yuva422p10be, PixFmt::Yuva422p12le, PixFmt::Yuva422p12be,
    PixFmt::Yuva422p16le, PixFmt::Yuva422p16be, PixFmt::Yuva444p9le, PixFmt::Yuva444p9be,
    PixFmt::Yuva444p10le, PixFmt::Yuva444p10be, PixFmt::Yuva444p12le, PixFmt::Yuva444p12be,
    PixFmt::Yuva444p16le, PixFmt::Yuva444p16be, PixFmt::Gbrp, PixFmt::Gbrap,
    PixFmt::Gbrp9le, PixFmt::Gbrp9be, PixFmt::Gbrp10le, PixFmt::Gbrp10be,
    PixFmt::Gbrp12le, PixFmt::Gbrp12be, PixFmt::Gbrp14le, PixFmt::Gbrp14be,
    PixFmt::Gbrp16le, PixFmt::Gbrp16be, PixFmt::Gbrp10msble, PixFmt::Gbrp10msbbe,
    PixFmt::Gbrp12msble, PixFmt::Gbrp12msbbe, PixFmt::Gbrap10le, PixFmt::Gbrap10be,
    PixFmt::Gbrap12le, PixFmt::Gbrap12be, PixFmt::Gbrap14le, PixFmt::Gbrap14be,
    PixFmt::Gbrap16le, PixFmt::Gbrap16be, PixFmt::Gbrap32le, PixFmt::Gbrap32be,
    PixFmt::Gbrpf16le, PixFmt::Gbrpf16be, PixFmt::Gbrapf16le, PixFmt::Gbrapf16be,
    PixFmt::Gbrpf32le, PixFmt::Gbrpf32be, PixFmt::Gbrapf32le, PixFmt::Gbrapf32be,
    PixFmt::Nv12, PixFmt::Nv21, PixFmt::Nv16, PixFmt::Nv24,
    PixFmt::Nv42, PixFmt::P010le, PixFmt::P010be, PixFmt::P012le,
    PixFmt::P012be, PixFmt::P016le, PixFmt::P016be, PixFmt::P210le,
    PixFmt::P210be, PixFmt::P212le, PixFmt::P212be, PixFmt::P216le,
    PixFmt::P216be, PixFmt::P410le, PixFmt::P410be, PixFmt::P412le,
    PixFmt::P412be, PixFmt::P416le, PixFmt::P416be, PixFmt::Nv20le,
    PixFmt::Nv20be, PixFmt::Gray8, PixFmt::Ya8, PixFmt::Gray9le,
    PixFmt::Gray9be, PixFmt::Gray10le, PixFmt::Gray10be, PixFmt::Gray12le,
    PixFmt::Gray12be, PixFmt::Gray14le, PixFmt::Gray14be, PixFmt::Gray16le,
    PixFmt::Gray16be, PixFmt::Gray32le, PixFmt::Gray32be, PixFmt::Ya16le,
    PixFmt::Ya16be, PixFmt::Grayf16le, PixFmt::Grayf16be, PixFmt::Yaf16le,
    PixFmt::Yaf16be, PixFmt::Grayf32le, PixFmt::Grayf32be, PixFmt::Yaf32le,
    PixFmt::Yaf32be, PixFmt::Rgb24, PixFmt::Bgr24, PixFmt::Argb,
    PixFmt::Rgba, PixFmt::Abgr, PixFmt::Bgra, PixFmt::X0rgb,
    PixFmt::Rgb0, PixFmt::X0bgr, PixFmt::Bgr0, PixFmt::Rgb8,
    PixFmt::Bgr8, PixFmt::Rgb4Byte, PixFmt::Bgr4Byte, PixFmt::Rgb4,
    PixFmt::Bgr4, PixFmt::Rgb444le, PixFmt::Rgb444be, PixFmt::Rgb555le,
    PixFmt::Rgb555be, PixFmt::Rgb565le, PixFmt::Rgb565be, PixFmt::Bgr444le,
    PixFmt::Bgr444be, PixFmt::Bgr555le, PixFmt::Bgr555be, PixFmt::Bgr565le,
    PixFmt::Bgr565be, PixFmt::X2rgb10le, PixFmt::X2rgb10be, PixFmt::X2bgr10le,
    PixFmt::X2bgr10be, PixFmt::Rgb48le, PixFmt::Rgb48be, PixFmt::Bgr48le,
    PixFmt::Bgr48be, PixFmt::Rgba64le, PixFmt::Rgba64be, PixFmt::Bgra64le,
    PixFmt::Bgra64be, PixFmt::Rgb96le, PixFmt::Rgb96be, PixFmt::Rgba128le,
    PixFmt::Rgba128be, PixFmt::Rgbf16le, PixFmt::Rgbf16be, PixFmt::Rgbaf16le,
    PixFmt::Rgbaf16be, PixFmt::Rgbf32le, PixFmt::Rgbf32be, PixFmt::Rgbaf32le,
    PixFmt::Rgbaf32be, PixFmt::Xyz12le, PixFmt::Xyz12be, PixFmt::Ayuv,
    PixFmt::Uyva, PixFmt::Vuya, PixFmt::Vuyx, PixFmt::Vyu444,
    PixFmt::Ayuv64le, PixFmt::Ayuv64be, PixFmt::Xv30le, PixFmt::Xv30be,
    PixFmt::Xv36le, PixFmt::Xv36be, PixFmt::Xv48le, PixFmt::Xv48be,
    PixFmt::V30xle, PixFmt::V30xbe, PixFmt::BayerBggr8, PixFmt::BayerRggb8,
    PixFmt::BayerGbrg8, PixFmt::BayerGrbg8, PixFmt::BayerBggr16le, PixFmt::BayerBggr16be,
    PixFmt::BayerRggb16le, PixFmt::BayerRggb16be, PixFmt::BayerGbrg16le, PixFmt::BayerGbrg16be,
    PixFmt::BayerGrbg16le, PixFmt::BayerGrbg16be, PixFmt::Yuyv422, PixFmt::Uyvy422,
    PixFmt::Yvyu422, PixFmt::Uyyvyy411, PixFmt::Y210le, PixFmt::Y210be,
    PixFmt::Y212le, PixFmt::Y212be, PixFmt::Y216le, PixFmt::Y216be,
    PixFmt::MonoWhite, PixFmt::MonoBlack, PixFmt::Pal8, PixFmt::Vaapi,
    PixFmt::Dxva2Vld, PixFmt::D3d11vaVld, PixFmt::D3d11, PixFmt::D3d12,
    PixFmt::Vdpau, PixFmt::Videotoolbox, PixFmt::Cuda, PixFmt::Qsv,
    PixFmt::Mmal, PixFmt::Mediacodec, PixFmt::Opencl, PixFmt::DrmPrime,
    PixFmt::Vulkan, PixFmt::AmfSurface, PixFmt::Ohcodec, PixFmt::Cuarray,
];

/// Every accepted spelling, sorted, for `binary_search_by_key`. Includes
/// aliases, so this is longer than [`ALL`].
#[rustfmt::skip]
pub(crate) static NAMES_SORTED: [(&str, PixFmt); 274] = [
    ("0bgr", PixFmt::X0bgr),
    ("0rgb", PixFmt::X0rgb),
    ("abgr", PixFmt::Abgr),
    ("amf_surface", PixFmt::AmfSurface),
    ("argb", PixFmt::Argb),
    ("ayuv", PixFmt::Ayuv),
    ("ayuv64be", PixFmt::Ayuv64be),
    ("ayuv64le", PixFmt::Ayuv64le),
    ("bayer_bggr16be", PixFmt::BayerBggr16be),
    ("bayer_bggr16le", PixFmt::BayerBggr16le),
    ("bayer_bggr8", PixFmt::BayerBggr8),
    ("bayer_gbrg16be", PixFmt::BayerGbrg16be),
    ("bayer_gbrg16le", PixFmt::BayerGbrg16le),
    ("bayer_gbrg8", PixFmt::BayerGbrg8),
    ("bayer_grbg16be", PixFmt::BayerGrbg16be),
    ("bayer_grbg16le", PixFmt::BayerGrbg16le),
    ("bayer_grbg8", PixFmt::BayerGrbg8),
    ("bayer_rggb16be", PixFmt::BayerRggb16be),
    ("bayer_rggb16le", PixFmt::BayerRggb16le),
    ("bayer_rggb8", PixFmt::BayerRggb8),
    ("bgr0", PixFmt::Bgr0),
    ("bgr24", PixFmt::Bgr24),
    ("bgr4", PixFmt::Bgr4),
    ("bgr444be", PixFmt::Bgr444be),
    ("bgr444le", PixFmt::Bgr444le),
    ("bgr48be", PixFmt::Bgr48be),
    ("bgr48le", PixFmt::Bgr48le),
    ("bgr4_byte", PixFmt::Bgr4Byte),
    ("bgr555be", PixFmt::Bgr555be),
    ("bgr555le", PixFmt::Bgr555le),
    ("bgr565be", PixFmt::Bgr565be),
    ("bgr565le", PixFmt::Bgr565le),
    ("bgr8", PixFmt::Bgr8),
    ("bgra", PixFmt::Bgra),
    ("bgra64be", PixFmt::Bgra64be),
    ("bgra64le", PixFmt::Bgra64le),
    ("cuarray", PixFmt::Cuarray),
    ("cuda", PixFmt::Cuda),
    ("d3d11", PixFmt::D3d11),
    ("d3d11va_vld", PixFmt::D3d11vaVld),
    ("d3d12", PixFmt::D3d12),
    ("drm_prime", PixFmt::DrmPrime),
    ("dxva2_vld", PixFmt::Dxva2Vld),
    ("gbr24p", PixFmt::Gbrp),
    ("gbrap", PixFmt::Gbrap),
    ("gbrap10be", PixFmt::Gbrap10be),
    ("gbrap10le", PixFmt::Gbrap10le),
    ("gbrap12be", PixFmt::Gbrap12be),
    ("gbrap12le", PixFmt::Gbrap12le),
    ("gbrap14be", PixFmt::Gbrap14be),
    ("gbrap14le", PixFmt::Gbrap14le),
    ("gbrap16be", PixFmt::Gbrap16be),
    ("gbrap16le", PixFmt::Gbrap16le),
    ("gbrap32be", PixFmt::Gbrap32be),
    ("gbrap32le", PixFmt::Gbrap32le),
    ("gbrapf16be", PixFmt::Gbrapf16be),
    ("gbrapf16le", PixFmt::Gbrapf16le),
    ("gbrapf32be", PixFmt::Gbrapf32be),
    ("gbrapf32le", PixFmt::Gbrapf32le),
    ("gbrp", PixFmt::Gbrp),
    ("gbrp10be", PixFmt::Gbrp10be),
    ("gbrp10le", PixFmt::Gbrp10le),
    ("gbrp10msbbe", PixFmt::Gbrp10msbbe),
    ("gbrp10msble", PixFmt::Gbrp10msble),
    ("gbrp12be", PixFmt::Gbrp12be),
    ("gbrp12le", PixFmt::Gbrp12le),
    ("gbrp12msbbe", PixFmt::Gbrp12msbbe),
    ("gbrp12msble", PixFmt::Gbrp12msble),
    ("gbrp14be", PixFmt::Gbrp14be),
    ("gbrp14le", PixFmt::Gbrp14le),
    ("gbrp16be", PixFmt::Gbrp16be),
    ("gbrp16le", PixFmt::Gbrp16le),
    ("gbrp9be", PixFmt::Gbrp9be),
    ("gbrp9le", PixFmt::Gbrp9le),
    ("gbrpf16be", PixFmt::Gbrpf16be),
    ("gbrpf16le", PixFmt::Gbrpf16le),
    ("gbrpf32be", PixFmt::Gbrpf32be),
    ("gbrpf32le", PixFmt::Gbrpf32le),
    ("gray", PixFmt::Gray8),
    ("gray10be", PixFmt::Gray10be),
    ("gray10le", PixFmt::Gray10le),
    ("gray12be", PixFmt::Gray12be),
    ("gray12le", PixFmt::Gray12le),
    ("gray14be", PixFmt::Gray14be),
    ("gray14le", PixFmt::Gray14le),
    ("gray16be", PixFmt::Gray16be),
    ("gray16le", PixFmt::Gray16le),
    ("gray32be", PixFmt::Gray32be),
    ("gray32le", PixFmt::Gray32le),
    ("gray8", PixFmt::Gray8),
    ("gray8a", PixFmt::Ya8),
    ("gray9be", PixFmt::Gray9be),
    ("gray9le", PixFmt::Gray9le),
    ("grayf16be", PixFmt::Grayf16be),
    ("grayf16le", PixFmt::Grayf16le),
    ("grayf32be", PixFmt::Grayf32be),
    ("grayf32le", PixFmt::Grayf32le),
    ("mediacodec", PixFmt::Mediacodec),
    ("mmal", PixFmt::Mmal),
    ("monob", PixFmt::MonoBlack),
    ("monoblack", PixFmt::MonoBlack),
    ("monow", PixFmt::MonoWhite),
    ("monowhite", PixFmt::MonoWhite),
    ("nv12", PixFmt::Nv12),
    ("nv16", PixFmt::Nv16),
    ("nv20be", PixFmt::Nv20be),
    ("nv20le", PixFmt::Nv20le),
    ("nv21", PixFmt::Nv21),
    ("nv24", PixFmt::Nv24),
    ("nv42", PixFmt::Nv42),
    ("ohcodec", PixFmt::Ohcodec),
    ("opencl", PixFmt::Opencl),
    ("p010be", PixFmt::P010be),
    ("p010le", PixFmt::P010le),
    ("p012be", PixFmt::P012be),
    ("p012le", PixFmt::P012le),
    ("p016be", PixFmt::P016be),
    ("p016le", PixFmt::P016le),
    ("p210be", PixFmt::P210be),
    ("p210le", PixFmt::P210le),
    ("p212be", PixFmt::P212be),
    ("p212le", PixFmt::P212le),
    ("p216be", PixFmt::P216be),
    ("p216le", PixFmt::P216le),
    ("p410be", PixFmt::P410be),
    ("p410le", PixFmt::P410le),
    ("p412be", PixFmt::P412be),
    ("p412le", PixFmt::P412le),
    ("p416be", PixFmt::P416be),
    ("p416le", PixFmt::P416le),
    ("pal8", PixFmt::Pal8),
    ("qsv", PixFmt::Qsv),
    ("rgb0", PixFmt::Rgb0),
    ("rgb24", PixFmt::Rgb24),
    ("rgb4", PixFmt::Rgb4),
    ("rgb444be", PixFmt::Rgb444be),
    ("rgb444le", PixFmt::Rgb444le),
    ("rgb48be", PixFmt::Rgb48be),
    ("rgb48le", PixFmt::Rgb48le),
    ("rgb4_byte", PixFmt::Rgb4Byte),
    ("rgb555be", PixFmt::Rgb555be),
    ("rgb555le", PixFmt::Rgb555le),
    ("rgb565be", PixFmt::Rgb565be),
    ("rgb565le", PixFmt::Rgb565le),
    ("rgb8", PixFmt::Rgb8),
    ("rgb96be", PixFmt::Rgb96be),
    ("rgb96le", PixFmt::Rgb96le),
    ("rgba", PixFmt::Rgba),
    ("rgba128be", PixFmt::Rgba128be),
    ("rgba128le", PixFmt::Rgba128le),
    ("rgba64be", PixFmt::Rgba64be),
    ("rgba64le", PixFmt::Rgba64le),
    ("rgbaf16be", PixFmt::Rgbaf16be),
    ("rgbaf16le", PixFmt::Rgbaf16le),
    ("rgbaf32be", PixFmt::Rgbaf32be),
    ("rgbaf32le", PixFmt::Rgbaf32le),
    ("rgbf16be", PixFmt::Rgbf16be),
    ("rgbf16le", PixFmt::Rgbf16le),
    ("rgbf32be", PixFmt::Rgbf32be),
    ("rgbf32le", PixFmt::Rgbf32le),
    ("uyva", PixFmt::Uyva),
    ("uyvy422", PixFmt::Uyvy422),
    ("uyyvyy411", PixFmt::Uyyvyy411),
    ("v30xbe", PixFmt::V30xbe),
    ("v30xle", PixFmt::V30xle),
    ("vaapi", PixFmt::Vaapi),
    ("vdpau", PixFmt::Vdpau),
    ("videotoolbox", PixFmt::Videotoolbox),
    ("vulkan", PixFmt::Vulkan),
    ("vuya", PixFmt::Vuya),
    ("vuyx", PixFmt::Vuyx),
    ("vyu444", PixFmt::Vyu444),
    ("x2bgr10be", PixFmt::X2bgr10be),
    ("x2bgr10le", PixFmt::X2bgr10le),
    ("x2rgb10be", PixFmt::X2rgb10be),
    ("x2rgb10le", PixFmt::X2rgb10le),
    ("xv30be", PixFmt::Xv30be),
    ("xv30le", PixFmt::Xv30le),
    ("xv36be", PixFmt::Xv36be),
    ("xv36le", PixFmt::Xv36le),
    ("xv48be", PixFmt::Xv48be),
    ("xv48le", PixFmt::Xv48le),
    ("xyz12be", PixFmt::Xyz12be),
    ("xyz12le", PixFmt::Xyz12le),
    ("y210be", PixFmt::Y210be),
    ("y210le", PixFmt::Y210le),
    ("y212be", PixFmt::Y212be),
    ("y212le", PixFmt::Y212le),
    ("y216be", PixFmt::Y216be),
    ("y216le", PixFmt::Y216le),
    ("y400a", PixFmt::Ya8),
    ("ya16be", PixFmt::Ya16be),
    ("ya16le", PixFmt::Ya16le),
    ("ya8", PixFmt::Ya8),
    ("yaf16be", PixFmt::Yaf16be),
    ("yaf16le", PixFmt::Yaf16le),
    ("yaf32be", PixFmt::Yaf32be),
    ("yaf32le", PixFmt::Yaf32le),
    ("yuv410p", PixFmt::Yuv410p),
    ("yuv411p", PixFmt::Yuv411p),
    ("yuv420p", PixFmt::Yuv420p),
    ("yuv420p10be", PixFmt::Yuv420p10be),
    ("yuv420p10le", PixFmt::Yuv420p10le),
    ("yuv420p12be", PixFmt::Yuv420p12be),
    ("yuv420p12le", PixFmt::Yuv420p12le),
    ("yuv420p14be", PixFmt::Yuv420p14be),
    ("yuv420p14le", PixFmt::Yuv420p14le),
    ("yuv420p16be", PixFmt::Yuv420p16be),
    ("yuv420p16le", PixFmt::Yuv420p16le),
    ("yuv420p9be", PixFmt::Yuv420p9be),
    ("yuv420p9le", PixFmt::Yuv420p9le),
    ("yuv422p", PixFmt::Yuv422p),
    ("yuv422p10be", PixFmt::Yuv422p10be),
    ("yuv422p10le", PixFmt::Yuv422p10le),
    ("yuv422p12be", PixFmt::Yuv422p12be),
    ("yuv422p12le", PixFmt::Yuv422p12le),
    ("yuv422p14be", PixFmt::Yuv422p14be),
    ("yuv422p14le", PixFmt::Yuv422p14le),
    ("yuv422p16be", PixFmt::Yuv422p16be),
    ("yuv422p16le", PixFmt::Yuv422p16le),
    ("yuv422p9be", PixFmt::Yuv422p9be),
    ("yuv422p9le", PixFmt::Yuv422p9le),
    ("yuv440p", PixFmt::Yuv440p),
    ("yuv440p10be", PixFmt::Yuv440p10be),
    ("yuv440p10le", PixFmt::Yuv440p10le),
    ("yuv440p12be", PixFmt::Yuv440p12be),
    ("yuv440p12le", PixFmt::Yuv440p12le),
    ("yuv444p", PixFmt::Yuv444p),
    ("yuv444p10be", PixFmt::Yuv444p10be),
    ("yuv444p10le", PixFmt::Yuv444p10le),
    ("yuv444p10msbbe", PixFmt::Yuv444p10msbbe),
    ("yuv444p10msble", PixFmt::Yuv444p10msble),
    ("yuv444p12be", PixFmt::Yuv444p12be),
    ("yuv444p12le", PixFmt::Yuv444p12le),
    ("yuv444p12msbbe", PixFmt::Yuv444p12msbbe),
    ("yuv444p12msble", PixFmt::Yuv444p12msble),
    ("yuv444p14be", PixFmt::Yuv444p14be),
    ("yuv444p14le", PixFmt::Yuv444p14le),
    ("yuv444p16be", PixFmt::Yuv444p16be),
    ("yuv444p16le", PixFmt::Yuv444p16le),
    ("yuv444p9be", PixFmt::Yuv444p9be),
    ("yuv444p9le", PixFmt::Yuv444p9le),
    ("yuva420p", PixFmt::Yuva420p),
    ("yuva420p10be", PixFmt::Yuva420p10be),
    ("yuva420p10le", PixFmt::Yuva420p10le),
    ("yuva420p16be", PixFmt::Yuva420p16be),
    ("yuva420p16le", PixFmt::Yuva420p16le),
    ("yuva420p9be", PixFmt::Yuva420p9be),
    ("yuva420p9le", PixFmt::Yuva420p9le),
    ("yuva422p", PixFmt::Yuva422p),
    ("yuva422p10be", PixFmt::Yuva422p10be),
    ("yuva422p10le", PixFmt::Yuva422p10le),
    ("yuva422p12be", PixFmt::Yuva422p12be),
    ("yuva422p12le", PixFmt::Yuva422p12le),
    ("yuva422p16be", PixFmt::Yuva422p16be),
    ("yuva422p16le", PixFmt::Yuva422p16le),
    ("yuva422p9be", PixFmt::Yuva422p9be),
    ("yuva422p9le", PixFmt::Yuva422p9le),
    ("yuva444p", PixFmt::Yuva444p),
    ("yuva444p10be", PixFmt::Yuva444p10be),
    ("yuva444p10le", PixFmt::Yuva444p10le),
    ("yuva444p12be", PixFmt::Yuva444p12be),
    ("yuva444p12le", PixFmt::Yuva444p12le),
    ("yuva444p16be", PixFmt::Yuva444p16be),
    ("yuva444p16le", PixFmt::Yuva444p16le),
    ("yuva444p9be", PixFmt::Yuva444p9be),
    ("yuva444p9le", PixFmt::Yuva444p9le),
    ("yuvj411p", PixFmt::Yuvj411p),
    ("yuvj420p", PixFmt::Yuvj420p),
    ("yuvj422p", PixFmt::Yuvj422p),
    ("yuvj440p", PixFmt::Yuvj440p),
    ("yuvj444p", PixFmt::Yuvj444p),
    ("yuyv422", PixFmt::Yuyv422),
    ("yvyu422", PixFmt::Yvyu422),
];

/// The opposite-endianness sibling of each format, where one exists.
/// Generated as a table rather than searched for at runtime.
#[rustfmt::skip]
pub(crate) static ENDIAN_SWAP: [Option<PixFmt>; 268] = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(PixFmt::Yuv420p9be),
    Some(PixFmt::Yuv420p9le),
    Some(PixFmt::Yuv420p10be),
    Some(PixFmt::Yuv420p10le),
    Some(PixFmt::Yuv420p12be),
    Some(PixFmt::Yuv420p12le),
    Some(PixFmt::Yuv420p14be),
    Some(PixFmt::Yuv420p14le),
    Some(PixFmt::Yuv420p16be),
    Some(PixFmt::Yuv420p16le),
    Some(PixFmt::Yuv422p9be),
    Some(PixFmt::Yuv422p9le),
    Some(PixFmt::Yuv422p10be),
    Some(PixFmt::Yuv422p10le),
    Some(PixFmt::Yuv422p12be),
    Some(PixFmt::Yuv422p12le),
    Some(PixFmt::Yuv422p14be),
    Some(PixFmt::Yuv422p14le),
    Some(PixFmt::Yuv422p16be),
    Some(PixFmt::Yuv422p16le),
    Some(PixFmt::Yuv444p9be),
    Some(PixFmt::Yuv444p9le),
    Some(PixFmt::Yuv444p10be),
    Some(PixFmt::Yuv444p10le),
    Some(PixFmt::Yuv444p12be),
    Some(PixFmt::Yuv444p12le),
    Some(PixFmt::Yuv444p14be),
    Some(PixFmt::Yuv444p14le),
    Some(PixFmt::Yuv444p16be),
    Some(PixFmt::Yuv444p16le),
    Some(PixFmt::Yuv440p10be),
    Some(PixFmt::Yuv440p10le),
    Some(PixFmt::Yuv440p12be),
    Some(PixFmt::Yuv440p12le),
    Some(PixFmt::Yuv444p10msbbe),
    Some(PixFmt::Yuv444p10msble),
    Some(PixFmt::Yuv444p12msbbe),
    Some(PixFmt::Yuv444p12msble),
    Some(PixFmt::Yuva420p9be),
    Some(PixFmt::Yuva420p9le),
    Some(PixFmt::Yuva420p10be),
    Some(PixFmt::Yuva420p10le),
    Some(PixFmt::Yuva420p16be),
    Some(PixFmt::Yuva420p16le),
    Some(PixFmt::Yuva422p9be),
    Some(PixFmt::Yuva422p9le),
    Some(PixFmt::Yuva422p10be),
    Some(PixFmt::Yuva422p10le),
    Some(PixFmt::Yuva422p12be),
    Some(PixFmt::Yuva422p12le),
    Some(PixFmt::Yuva422p16be),
    Some(PixFmt::Yuva422p16le),
    Some(PixFmt::Yuva444p9be),
    Some(PixFmt::Yuva444p9le),
    Some(PixFmt::Yuva444p10be),
    Some(PixFmt::Yuva444p10le),
    Some(PixFmt::Yuva444p12be),
    Some(PixFmt::Yuva444p12le),
    Some(PixFmt::Yuva444p16be),
    Some(PixFmt::Yuva444p16le),
    None,
    None,
    Some(PixFmt::Gbrp9be),
    Some(PixFmt::Gbrp9le),
    Some(PixFmt::Gbrp10be),
    Some(PixFmt::Gbrp10le),
    Some(PixFmt::Gbrp12be),
    Some(PixFmt::Gbrp12le),
    Some(PixFmt::Gbrp14be),
    Some(PixFmt::Gbrp14le),
    Some(PixFmt::Gbrp16be),
    Some(PixFmt::Gbrp16le),
    Some(PixFmt::Gbrp10msbbe),
    Some(PixFmt::Gbrp10msble),
    Some(PixFmt::Gbrp12msbbe),
    Some(PixFmt::Gbrp12msble),
    Some(PixFmt::Gbrap10be),
    Some(PixFmt::Gbrap10le),
    Some(PixFmt::Gbrap12be),
    Some(PixFmt::Gbrap12le),
    Some(PixFmt::Gbrap14be),
    Some(PixFmt::Gbrap14le),
    Some(PixFmt::Gbrap16be),
    Some(PixFmt::Gbrap16le),
    Some(PixFmt::Gbrap32be),
    Some(PixFmt::Gbrap32le),
    Some(PixFmt::Gbrpf16be),
    Some(PixFmt::Gbrpf16le),
    Some(PixFmt::Gbrapf16be),
    Some(PixFmt::Gbrapf16le),
    Some(PixFmt::Gbrpf32be),
    Some(PixFmt::Gbrpf32le),
    Some(PixFmt::Gbrapf32be),
    Some(PixFmt::Gbrapf32le),
    None,
    None,
    None,
    None,
    None,
    Some(PixFmt::P010be),
    Some(PixFmt::P010le),
    Some(PixFmt::P012be),
    Some(PixFmt::P012le),
    Some(PixFmt::P016be),
    Some(PixFmt::P016le),
    Some(PixFmt::P210be),
    Some(PixFmt::P210le),
    Some(PixFmt::P212be),
    Some(PixFmt::P212le),
    Some(PixFmt::P216be),
    Some(PixFmt::P216le),
    Some(PixFmt::P410be),
    Some(PixFmt::P410le),
    Some(PixFmt::P412be),
    Some(PixFmt::P412le),
    Some(PixFmt::P416be),
    Some(PixFmt::P416le),
    Some(PixFmt::Nv20be),
    Some(PixFmt::Nv20le),
    None,
    None,
    Some(PixFmt::Gray9be),
    Some(PixFmt::Gray9le),
    Some(PixFmt::Gray10be),
    Some(PixFmt::Gray10le),
    Some(PixFmt::Gray12be),
    Some(PixFmt::Gray12le),
    Some(PixFmt::Gray14be),
    Some(PixFmt::Gray14le),
    Some(PixFmt::Gray16be),
    Some(PixFmt::Gray16le),
    Some(PixFmt::Gray32be),
    Some(PixFmt::Gray32le),
    Some(PixFmt::Ya16be),
    Some(PixFmt::Ya16le),
    Some(PixFmt::Grayf16be),
    Some(PixFmt::Grayf16le),
    Some(PixFmt::Yaf16be),
    Some(PixFmt::Yaf16le),
    Some(PixFmt::Grayf32be),
    Some(PixFmt::Grayf32le),
    Some(PixFmt::Yaf32be),
    Some(PixFmt::Yaf32le),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    Some(PixFmt::Rgb444be),
    Some(PixFmt::Rgb444le),
    Some(PixFmt::Rgb555be),
    Some(PixFmt::Rgb555le),
    Some(PixFmt::Rgb565be),
    Some(PixFmt::Rgb565le),
    Some(PixFmt::Bgr444be),
    Some(PixFmt::Bgr444le),
    Some(PixFmt::Bgr555be),
    Some(PixFmt::Bgr555le),
    Some(PixFmt::Bgr565be),
    Some(PixFmt::Bgr565le),
    Some(PixFmt::X2rgb10be),
    Some(PixFmt::X2rgb10le),
    Some(PixFmt::X2bgr10be),
    Some(PixFmt::X2bgr10le),
    Some(PixFmt::Rgb48be),
    Some(PixFmt::Rgb48le),
    Some(PixFmt::Bgr48be),
    Some(PixFmt::Bgr48le),
    Some(PixFmt::Rgba64be),
    Some(PixFmt::Rgba64le),
    Some(PixFmt::Bgra64be),
    Some(PixFmt::Bgra64le),
    Some(PixFmt::Rgb96be),
    Some(PixFmt::Rgb96le),
    Some(PixFmt::Rgba128be),
    Some(PixFmt::Rgba128le),
    Some(PixFmt::Rgbf16be),
    Some(PixFmt::Rgbf16le),
    Some(PixFmt::Rgbaf16be),
    Some(PixFmt::Rgbaf16le),
    Some(PixFmt::Rgbf32be),
    Some(PixFmt::Rgbf32le),
    Some(PixFmt::Rgbaf32be),
    Some(PixFmt::Rgbaf32le),
    Some(PixFmt::Xyz12be),
    Some(PixFmt::Xyz12le),
    None,
    None,
    None,
    None,
    None,
    Some(PixFmt::Ayuv64be),
    Some(PixFmt::Ayuv64le),
    Some(PixFmt::Xv30be),
    Some(PixFmt::Xv30le),
    Some(PixFmt::Xv36be),
    Some(PixFmt::Xv36le),
    Some(PixFmt::Xv48be),
    Some(PixFmt::Xv48le),
    Some(PixFmt::V30xbe),
    Some(PixFmt::V30xle),
    None,
    None,
    None,
    None,
    Some(PixFmt::BayerBggr16be),
    Some(PixFmt::BayerBggr16le),
    Some(PixFmt::BayerRggb16be),
    Some(PixFmt::BayerRggb16le),
    Some(PixFmt::BayerGbrg16be),
    Some(PixFmt::BayerGbrg16le),
    Some(PixFmt::BayerGrbg16be),
    Some(PixFmt::BayerGrbg16le),
    None,
    None,
    None,
    None,
    Some(PixFmt::Y210be),
    Some(PixFmt::Y210le),
    Some(PixFmt::Y212be),
    Some(PixFmt::Y212le),
    Some(PixFmt::Y216be),
    Some(PixFmt::Y216le),
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
];

#[cfg(test)]
mod generated_invariants {
    #![expect(
        clippy::indexing_slicing,
        clippy::integer_division,
        reason = "these assertions index tables the generator guarantees are \
                  index-aligned, and recompute an average that is defined as a \
                  truncating division; a failure here is the test doing its job"
    )]

    use super::{ALL, DESCRIPTORS, ENDIAN_SWAP, NAMES_SORTED};
    use crate::PixFmtFlags as F;

    #[test]
    fn discriminants_index_the_table() {
        for (i, fmt) in ALL.iter().enumerate() {
            assert_eq!(*fmt as usize, i, "{} is not at index {i}", fmt.name());
        }
        assert_eq!(ALL.len(), DESCRIPTORS.len());
        assert_eq!(ALL.len(), ENDIAN_SWAP.len());
    }

    #[test]
    fn planes_and_components_agree() {
        for d in &DESCRIPTORS {
            if d.flags.contains(F::HW_ACCEL) {
                assert_eq!(d.planes, 0, "{}: hw surface with planes", d.name);
                assert!(
                    d.components.is_empty(),
                    "{}: hw surface with components",
                    d.name
                );
                continue;
            }
            assert!(!d.components.is_empty(), "{}: no components", d.name);
            assert!(d.components.len() <= 4, "{}: too many components", d.name);
            let max = d.components.iter().map(|c| c.plane).max().unwrap_or(0);
            assert_eq!(d.planes, max + 1, "{}: plane count disagrees", d.name);
            for p in 0..d.planes {
                assert!(
                    d.components.iter().any(|c| c.plane == p),
                    "{}: plane {p} unused",
                    d.name
                );
            }
            assert_eq!(
                d.planes > 1,
                d.flags.contains(F::PLANAR),
                "{}: PLANAR flag disagrees with plane count",
                d.name
            );
        }
    }

    #[test]
    fn components_are_well_formed() {
        for d in &DESCRIPTORS {
            for c in d.components {
                assert!(c.depth > 0, "{}: zero depth", d.name);
                assert!(c.depth <= 32, "{}: depth over 32", d.name);
                assert!(
                    u16::from(c.shift) + u16::from(c.depth) <= 32,
                    "{}: field overruns",
                    d.name
                );
                assert!(
                    c.plane < d.planes,
                    "{}: component outside plane range",
                    d.name
                );
                if !d.flags.contains(F::BITSTREAM) {
                    let bytes = c.depth.div_ceil(8);
                    assert!(c.step >= bytes, "{}: step smaller than a sample", d.name);
                    // Bounded against the widest step in the plane, which is the
                    // pixel-group stride. Per-component `offset + bytes <= step`
                    // would be tighter but is false for `uyyvyy411`, whose luma
                    // samples are not evenly spaced and are given the tightest
                    // uniform stride that reaches all of them.
                    let group = d
                        .components
                        .iter()
                        .filter(|o| o.plane == c.plane)
                        .map(|o| o.step)
                        .max()
                        .unwrap_or(c.step);
                    assert!(
                        u16::from(c.offset) + u16::from(bytes) <= u16::from(group),
                        "{}: component overruns the pixel group",
                        d.name
                    );
                }
            }
        }
    }

    #[test]
    fn subsampling_is_sane() {
        for d in &DESCRIPTORS {
            assert!(
                d.log2_chroma_w <= 2,
                "{}: absurd horizontal subsampling",
                d.name
            );
            assert!(
                d.log2_chroma_h <= 2,
                "{}: absurd vertical subsampling",
                d.name
            );
            if d.flags.contains(F::RGB) || d.flags.contains(F::HW_ACCEL) {
                assert_eq!(
                    (d.log2_chroma_w, d.log2_chroma_h),
                    (0, 0),
                    "{}: subsampled RGB",
                    d.name
                );
            }
        }
    }

    #[test]
    fn alpha_flag_matches_the_layout() {
        for d in &DESCRIPTORS {
            let has = d.flags.contains(F::ALPHA);
            let n = d.components.len();
            assert_eq!(
                has,
                n == 2 || n == 4,
                "{}: ALPHA flag disagrees with layout",
                d.name
            );
        }
    }

    #[test]
    fn bits_per_pixel_matches_the_components() {
        for d in &DESCRIPTORS {
            if d.flags.contains(F::HW_ACCEL) {
                assert_eq!(d.bits_per_pixel, 0);
                continue;
            }
            let block = 1u32 << (d.log2_chroma_w + d.log2_chroma_h);
            let mut bits = 0u32;
            for (i, c) in d.components.iter().enumerate() {
                bits += if i == 1 || i == 2 {
                    u32::from(c.depth)
                } else {
                    u32::from(c.depth) * block
                };
            }
            assert_eq!(
                u32::from(d.bits_per_pixel),
                bits / block,
                "{}: bits_per_pixel disagrees with the components",
                d.name
            );
        }
    }

    #[test]
    fn big_endian_needs_a_multi_byte_sample() {
        for d in &DESCRIPTORS {
            if !d.flags.contains(F::BIG_ENDIAN) {
                continue;
            }
            assert!(
                d.components.iter().any(|c| c.step > 1 || c.depth > 8),
                "{}: BE flag on a format with no multi-byte container",
                d.name
            );
        }
    }

    #[test]
    fn endian_siblings_pair_up() {
        for (i, sib) in ENDIAN_SWAP.iter().enumerate() {
            let Some(sib) = *sib else { continue };
            let a = &DESCRIPTORS[i];
            let b = &DESCRIPTORS[sib as usize];
            assert_ne!(sib as usize, i, "{}: is its own sibling", a.name);
            assert_eq!(
                ENDIAN_SWAP[sib as usize],
                Some(ALL[i]),
                "{}: swap is not an involution",
                a.name
            );
            assert_eq!(
                a.components, b.components,
                "{}: sibling layout differs",
                a.name
            );
            assert_eq!(a.planes, b.planes);
            assert_eq!(a.bits_per_pixel, b.bits_per_pixel);
            assert_ne!(
                a.flags.contains(F::BIG_ENDIAN),
                b.flags.contains(F::BIG_ENDIAN),
                "{}: sibling has the same endianness",
                a.name
            );
            assert_eq!(
                a.flags.difference(F::BIG_ENDIAN),
                b.flags.difference(F::BIG_ENDIAN),
                "{}: siblings differ by more than endianness",
                a.name
            );
        }
    }

    #[test]
    fn names_are_sorted_unique_and_complete() {
        for w in NAMES_SORTED.windows(2) {
            assert!(
                w[0].0 < w[1].0,
                "name table is not sorted: {} then {}",
                w[0].0,
                w[1].0
            );
        }
        for fmt in &ALL {
            let name = fmt.name();
            assert!(
                NAMES_SORTED.binary_search_by_key(&name, |e| e.0).is_ok(),
                "{name} is missing from the name table"
            );
        }
    }
}
